### ISSUE TITLE
Typo in xgboost_example.py?

### ISSUE THREAD

**Issue by pford221** [fmfn/BayesianOptimization#101]
Hi,

There may be a typo in line 25 where it reads `params['cosample_bytree'] = max(min(colsample_bytree, 1), 0)`. 

Also, is there a reason to make the maxmin of parameters that are not allowed to explore outside those values? For example `colsample_bytree ` is constrained to be between `(0.1, 1)` in line 75. So, do we need the maxmin bit in line 25?

**Comment by fmfn** [comment]
I don't see the typo, but feel free to submit a PR with a fix for it.

The reason for `max(min(,))` is to avoid float point fluctuations that could lead to assertion errors downstream.
