### ISSUE TITLE
bo.X != bo.res['all']

### ISSUE THREAD

**Issue by mhqo** [fmfn/BayesianOptimization#103]
Hi,

I noticed that bo.X does not equal bo.res['all']['parameters'] ( minus the random runs ofc).

The columns of bo.X are messed up and do not represent the initial input order. (See testcode below)

I feel that bo.X is more important than bo.res['all']['parameters'] since it shows ALL evaluated points !

```
from bayes_opt import BayesianOptimization
from scipy.optimize import rosen

# rosen as obj
def ro(x1, x2, x3):
    return -1*rosen([x1, x2])

# opt
bo = BayesianOptimization(ro, pbounds={'x1' : (-1.0, 5.0), 
                                  'x2' : (-1.0, 5.0), 'x3' : (-1.0, 5.0)}, random_state=1)
# max
bo.maximize(1, 3, acq='poi')

# test fails !
[ro(*x) for x in bo.X] == bo.Y.tolist()

# as one can see x2 is actually bo.X[:,0], x3 is bo.X[:,2] and x3 is bo.X[:,1]
bo.X[1:]
array([[ 2.18624627,  2.86252285,  0.70825166],
       [ 4.72179023,  2.96300164,  3.01753416],
       [-0.78524179,  0.15640738,  4.37775389]])

bo.res['all']['params']
[{'x1': 0.7082516567114334, 'x2': 2.186246270050328, 'x3': 2.8625228467524133},
 {'x1': 3.017534156171836, 'x2': 4.721790227135369, 'x3': 2.963001639364344},
 {'x1': 4.377753890676444,
  'x2': -0.7852417897346731,
  'x3': 0.1564073832944104}]

```

i think it would be great to have the same order as the obj_func input parameters.

Thanks in advance.

**Comment by fmfn** [comment]
Thanks for bringing it up. Organizing how results are exposed is part of the next release.

**Comment by fmfn** [comment]
This issue was resolved in the upcoming release branch. See https://github.com/fmfn/BayesianOptimization/pull/118
