### ISSUE TITLE
ValueError: setting an array element with a sequence.

### ISSUE THREAD

**Issue by bywbilly** [fmfn/BayesianOptimization#113]
Hi,

Thanks for providing us with such excellent repo. I have some problems in using BO on XGBoost.

I got ValueError: setting an array element with a sequence when I am running the program, and here is the related code snippet:

![image](https://user-images.githubusercontent.com/10766902/46679204-7e668580-cbb4-11e8-8e1c-ab36fe548fc3.png)

The python interpreter said the error occurred at this part: 

![image](https://user-images.githubusercontent.com/10766902/46679295-a950d980-cbb4-11e8-8355-c8f169ccc2ef.png)

Thanks!

**Comment by fmfn** [comment]
`'colsample_bytree': (0,1 ,1)` is likely the culprit.
