### ISSUE TITLE
Applying bayesian optimization to higher dimension

### ISSUE THREAD

**Issue by chenjiunhan** [fmfn/BayesianOptimization#124]
Hi, 
This BayesianOptimization module is great and example is newbie friendly! Thanks!

I try to apply bayesian optimization in about 58 dimensions, but it seems that it needs a while to generate new generation. Is it possible that I can reduce the time usage? The following is the code I modified from usage.py in this repository and the optimization progress with 30 dimensions:

    8 | 00m21s |   14.70665 |    0.5000 |    0.5000 |    0.4741 |    0.4363 |    0.5000 |    0.4873 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4709 |    0.5000 |    0.5000 |    0.4992 |    0.5000 |    0.3945 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4763 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4680 | 
    9 | 00m43s |   14.74567 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4737 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4734 |    0.5000 |    0.5000 |    0.5000 |    0.4197 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.4309 |    0.5000 |    0.4480 |    0.5000 |    0.5000 |    0.5000 |    0.5000 |    0.5000 | 

```
"""Example of how to use this bayesian optimization package."""
import numpy as np
import sys
sys.path.append("./")
from bayes_opt import BayesianOptimization

import warnings
warnings.filterwarnings("ignore")

NUM_WEIGHTS = 30

def optimization_function_BAYESIAN(**weights):

    x = [0] * NUM_WEIGHTS

    for key in weights.keys():
        x[int(key[1:])] = weights[key]

    x = np.array(x)
    
    return np.sum(x)    

weights = {}
weights_explore = {}
for i in range(NUM_WEIGHTS):
    weights['w' + str(i)] = (-0.5, 0.5)
    weights_explore['w' + str(i)] = [-0.5, 0.5]

bo = BayesianOptimization(optimization_function_BAYESIAN, weights)

bo.explore(weights_explore)

gp_params = {'kernel': None,
             'alpha': 1e-5}

bo.maximize(init_points=5, n_iter=15, kappa=2)

print(bo.res['max'])

```

**Comment by chenjiunhan** [comment]
Supplementary explanation: the question that I want to ask is if the time consuming is normal? or I did something wrong?

**Comment by fmfn** [comment]
Nothing you can do really.

This algorithm is suitable for optimization of functions that are very expensive to evaluate. If evaluating you function at some arbitrary parameters takes several minutes/hours/days you don't really care for the extra 2min overhead added by running bayesian optimization.

If, however, evaluating your function if fast/cheap, you're better off with any other traditional optimization algorithm.
