### ISSUE TITLE
Optimsation not following acquisition function suggestion.

### ISSUE THREAD

**Issue by Bacoknight** [fmfn/BayesianOptimization#134]
Hi fmfn,

I want to start by thanking you for this very nice implementation of Bayesian optimisation that I've found very useful. 

I've tried to visualise the 'thought process' of this optimisation method, and so tried to follow the code given [here](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb). Instead of ucb however, I've been using poi as my acquisition function as it seemed to work better for my specific problem. 

Similar to the notebook, I've plotted the utility function underneath, marking the maximal point as that should be the next point probed. However, after the next iteration a different point seems to be probed, even if it has a worse acquisition function value than the other point. 

I'm relatively new to the game of black box optimisation, even moreso for BO, so is this intentional or am I doing something wrong? Below I've attached the animation that I've generated to show the method in action [I've zipped it up as .mp4 are not supported here.], and there are certain points where the next best point (as predicted by the poi acquisition function) is not the next point that is actually probed.

Here is the code I am using to create the animation:
     
 
        # Define parameters used for the optimisation algorithm.
        acqFunc = "poi"
        acqKappa = 5
        acqXi = 0.1

        # Start by plotting the objective function being optimised. This could take a while.
        xVals = np.linspace(0, 1e4, num = 5000)

        yList = []

        for x in xVals:
                yList.append(BayesianObjective1D(x))

        # Begin the figure plot.
        fig = plt.figure("Optimisation Animation")

        acqAxis = plt.subplot(2, 1, 2)
        yAxis = plt.subplot(2, 1, 1, sharex = acqAxis)

        # Create optimisers.
        inputBounds = {"x1": (0, 1e4)}
        optimiser = BayesianOptimization(BayesianObjective1D, inputBounds, random_state = np.random.randint(1, 1e4), verbose = 0)

        # Initialise optimisation with 1 random point.
        optimiser.maximize(init_points = 1, n_iter = 0, acq = acqFunc, kappa = acqKappa, xi = acqXi)

        # Use points to generate initial prediction graph data.
        mean, stdDev = optimiser._gp.predict(xVals.reshape(-1, 1), return_std = True)
        # The utility function is used to choose the next point to query.
        utilFunction = UtilityFunction(kind = acqFunc, kappa = acqKappa, xi = acqXi)
        util = utilFunction.utility(bVals.reshape(-1, 1), optimiser._gp, 0)
        predictX, predictY = xVals[np.argmax(util)], np.max(util)
        
        # Create lists to store objects at each iteration.
        # Observed points. To be marked.
        obsList = [(optimiser.space.params.flatten(), optimiser.space.target)]
        # How the optimiser sees the function.
        gpList = [mean]
        # How the optimiser will pick its next point, and the point it picked.
        utilList = [(util, predictX, predictY)]
        # Store the polygons representing the confidence levels at each iteration. We multiply the standard deviation by 1.96 to get the 95% confidence interval.
        confidenceList = [yAxis.fill_between(xVals, mean + (1.96 * stdDev), mean - (1.96 * stdDev), alpha = 0.3, visible = False, color = "c")]

        # Iterate the optimiser to see how it evolves.
        for iteration in range(numIters):
                # Run the same code as above.
                optimiser.maximize(init_points = 0, n_iter = 1, acq = acqFunc, kappa = acqKappa, xi = acqXi)

                mean, stdDev = optimiser._gp.predict(xVals.reshape(-1, 1), return_std = True)
                util = utilFunction.utility(xVals.reshape(-1, 1), optimiser._gp, 0)
                predictX, predictY = xVals[np.argmax(util)], np.max(util)

                # Add the obtained values to the various lists.
                obsList.append((optimiser.space.params.flatten(), optimiser.space.target))
                gpList.append(mean)
                utilList.append((util, predictB, predictFoM))
                confidenceList.append(fomAxis.fill_between(xVals, mean + (1.96 * stdDev), mean - (1.96 * stdDev), alpha = 0.3, visible = False, color = "c"))

        yAxis.set(xlim = (0, 1e4), ylim = (-0.5, 1.1))
        acqAxis.set(xlim = (0, 1e4), ylim = (0, 1.1))
        yAxis.set_ylabel("FoM")
        acqAxis.set_ylabel("Probability of Improvement")
        acqAxis.set_xlabel("Magnetic field strength (Gauss)") 

        # Plot the functions that won't change with each frame.
        yAxis.plot(xVals, yList, color = "b", linewidth = 3)

        # Plot the changing graphs with their inital values.
        meanLine = yAxis.plot(xVals, gpList[0], color = "k", linestyle = "--")[0]
        acqLine = acqAxis.plot(xVals, utilList[0][0], color = "purple")[0]
        probedScat = yAxis.scatter(obsList[0][0], obsList[0][1], marker = "v", color = "r")
        predScat = acqAxis.scatter(utilList[0][1], utilList[0][2], marker = "^", color = "r")
        confidenceList[0].set_visible(True)

        def animate(i):
                # Define what the graph does on each frame.
                meanLine.set_ydata(gpList[i])
                acqLine.set_ydata(utilList[i][0])
                probedScat.set_offsets(np.c_[obsList[i][0], obsList[i][1]])
                predScat.set_offsets(np.c_[utilList[i][1], utilList[i][2]])
                confidenceList[i - 1].set_visible(False)
                confidenceList[i].set_visible(True)

                return meanLine, acqLine, probedScat, predScat, confidenceList[i]
        
        animator = FuncAnimation(fig, animate, frames = len(obsList), interval = 1e3, blit = True)

        # Set up formatting for the movie files
        Writer = writers['ffmpeg']
        writer = Writer(bitrate = 1800)

        animator.save("show_opt.mp4", writer = writer)
[show_opt.zip](https://github.com/fmfn/BayesianOptimization/files/2659234/show_opt.zip)

**Comment by fmfn** [comment]
Try passing the actual current `y_max` value to `util = utilFunction.utility(xVals.reshape(-1, 1), optimiser._gp, 0)` instead of 0.

**Comment by majichang** [comment]
@Bacoknight hallo, Clould you tell me your function BayesianObjective1D how to create

**Comment by Bacoknight** [comment]
@majichang The BayesianObjective1D function is a python function which has only 1 variable. In my specific case, it's a black box function which calls upon another program that I did not write, but which returns a value that I then change a little bit and it returns a single value. The function could be anything however. [This example](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb) shows an example of a 1D function which you could use. 
Hopefully that answers your question.
