### ISSUE TITLE
import Error

### ISSUE THREAD

**Issue by Great1414** [fmfn/BayesianOptimization#140]
There has an error  'ImportError: cannot import name 'BayesianOptimization'.
But, I have installed this package successfully.
So, I didn't find the solution about this question.
Please , help!

**Comment by fmfn** [comment]
Try `from bayes_opt import BayesianOptimization`

**Comment by asiliskins** [comment]
same error :(

**Comment by MJfadeaway** [comment]
Still error when I try from bayes_opt import BayesianOptimization
