### ISSUE TITLE
Performance Considerations

### ISSUE THREAD

**Issue by olokobayusuf** [fmfn/BayesianOptimization#141]
Hi there. First off, I want to say a big thank you for creating this amazing library. I'm working on an imaging application that greatly relies on it. There's just one thing I need to ask about: performance. I haven't looked through the sources, but I was wondering if you this is a priority and if it can be improved upon. The optimization stepping takes quite a while (even when the objective function is trivial to compute). Let me know your thoughts on this.

**Comment by fmfn** [comment]
The bottlenecks of the optimization process are two-fold:
1. Fitting the gaussian process to the parameter-observation data.
2. Looking for the maximum of the acquisition function.

One is the most time consuming step and there's not much that can be done about that. At least nothing that won't have an effect of the performance of the algorithm. Your best bet here is to call `optimizer.set_gp_params.(n_restarts_optimizer=n)` where `n` is whatever number works for you. By default `n=25`.

Two is not as time consuming as fitting the GP, but does have an impact. However tinkering with it can also break the whole thing, so the parameters dictating how hard the algorithm tries to find this surrogate maximum are not exposed. Nevertheless, if you're really having issues with it, you can navigate to `util.py` and look at the definition of the `acq_max` function. By decreasing either `n_warmup` or `n_iter` you can speed up this step. By default they are `n_warmup=100000`, and `n_iter=250`.

These are the two ways you can speed things up. Neither is recommended, do so at your own peril.

**Comment by olokobayusuf** [comment]
Thank you for the excellent explanation!
