### ISSUE TITLE
Required black box function?

### ISSUE THREAD

**Issue by nikhilwbhatia** [fmfn/BayesianOptimization#143]
Could this library be used to shell out to from another language without a black box function? I would like to keep a stateless optimizer that I can re-initialize at every iteration and re-register all previous points to get the next suggested value. This would mean the evaluation step would be performed outside the script and all I would like to do is register a set of points with the optimizer. Is there a way to initialize the optimizer without the black box function and just do the above steps to retrieve next points?

**Comment by fmfn** [comment]
Absolutely, I just answered a similar question in another issue, so I'll refer you there first: https://github.com/fmfn/BayesianOptimization/issues/142. Let me know if it doesn't answer your question.

PS: Session 4 of the [basic tour](https://github.com/fmfn/BayesianOptimization/blob/master/examples/basic-tour.ipynb) talks about how you can save/load progress. Combined with Suggest-Evaluate-Register, you should be able to do what you want.

**Comment by nikhilwbhatia** [comment]
The suggest-evaluate-register paradigm is essentially everything I need, I was just confused as to how I should initialize the optimizer if I don't want to specify a black_box_function to the f field:

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds={'x': (-2, 2), 'y': (-3, 3)},
    verbose=2,
    random_state=1,
)

 Is this field necessary for the optimizer to build its acquisition function? Or is initializing an optimizer without this function and merely engaging through suggest/evaluate/register calls enough? Sorry not super familiar with the math behind this.
