### ISSUE TITLE
blackbox function input values

### ISSUE THREAD

**Issue by NiklasDL** [fmfn/BayesianOptimization#146]
My blackbox function requires additional arguments, such as directories (e.g. where to grab data or where to find the corresponding model), which I do not want to hardcode into the function.

Assume I have two variables I want to optimize:

``
my_bounds = {'x': (0, 1), 'y': (0,10)}
``

but my blackbox function requires two additional arguments, e.g.

``
def my_blackbox_fun(my_dir, my_other_dir, x, y):
   ...
``

Can I still use the package without hardcoding the directories into my blackbox function? 
Unfortunately, I was not able to figure out how to ..

**Comment by fmfn** [comment]
Just use a partial function.
```
from functools import partial
func_to_optimize = partial(my_blackbox_fun, my_dir="./", my_other_dir="../")
```

**Comment by NiklasDL** [comment]
Thank you :)
