### ISSUE TITLE
BayesianOptimization with Multiprocessing

### ISSUE THREAD

**Issue by LucaCappelletti94** [fmfn/BayesianOptimization#153]
Hello!

First of all thank you for making this awesome library. We are loving it! I wanted to ask you if there is any way to make it work with multiprocessing, for exploring multiple parameters at the same time.

Also, there is any support for multi-machine optimization?

If there are no such feature, which other library would you suggest using?

**Comment by fmfn** [comment]
Yes, it is certainly possible. Before going down this path I suggest you take a look at the [advanced tour](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) notebook, in particular the Suggest-Evaluate-Register paradigm, which goes over the methods needed to have this sort of flexibility.

After that, checkout the discussion in this (now closed) [issue](https://github.com/fmfn/BayesianOptimization/issues/138), I believe it will make it a bit more clear. The gist is: register right before asking for a suggestion. So, if you have concurrent (not just parallel) workers, just make sure that each, on their on, register their last result before asking for a new probe point.

Also this [script](https://github.com/fmfn/BayesianOptimization/blob/master/examples/async_optimization.py) is a fully working example of using this library in a distributed fashion, take a look at it and see if it helps.
