### ISSUE TITLE
reproducibility

### ISSUE THREAD

**Issue by jiayeah9508** [fmfn/BayesianOptimization#157]
Hi!
  I am a student and l have used your library  to find the best parameters in my project  ，to be honest, your code is excellent but  I found that when  I  use the same object funtion , same parameter bounds, same init point, same step number,  and random_state (the only one thing about random control in your code ) , the result is consistent in single machine , but different in different machine, though the numpy, scipy and scikitlearn are all same version.
  Because reproducibility is important for paper, so I`ll appreciate it if you can tell me how to deal with this problem!

**Comment by jiayeah9508** [comment]
import numpy as np
from bayes_opt import BayesianOptimization  

def black_box_function(x):
    return (-1.0/2.0)*x*x

pbounds = { 'x':(-1,1)}




optimizer =  BayesianOptimization(
    f=black_box_function,  
    pbounds=pbounds,
    random_state=1,   
    verbose = 2        
    
)

optimizer.maximize(
    init_points=5, 
    n_iter=5,   
)

different results in different machine...

**Comment by jiayeah9508** [comment]
import numpy as np
from bayes_opt import BayesianOptimization  
def black_box_function(x):
    return (-1.0/2.0)*x*x

pbounds = { 'x':(-1,1)}




optimizer =  BayesianOptimization(
    f=black_box_function,  
    pbounds=pbounds,
    random_state=1,   
    verbose = 2      
    
)

optimizer.maximize(
    init_points=5, 
    n_iter=5, 
)

**Comment by jiayeah9508** [comment]
import numpy as np
from bayes_opt import BayesianOptimization  
def black_box_function(x):
    return (-1.0/2.0)*x*x

pbounds = { 'x':(-1,1)}




optimizer =  BayesianOptimization(
    f=black_box_function,  
    pbounds=pbounds,
    random_state=1,   
    verbose = 2      
    
)

optimizer.maximize(
    init_points=5, 
    n_iter=5, 
)

**Comment by jiayeah9508** [comment]
import numpy as np
from bayes_opt import BayesianOptimization  
def black_box_function(x):
    return -pow(x,2)

pbounds = { 'x':(-1,1)}

seed = np.random.RandomState(1)


optimizer =  BayesianOptimization(
    f=black_box_function,  
    pbounds=pbounds,
    random_state=seed,   
    verbose = 2       
    
)

optimizer.maximize(
    init_points=5, 
    n_iter=5,   
)

different results on different machines

**Comment by fmfn** [comment]
Someone recently also raised this [issue](https://github.com/fmfn/BayesianOptimization/issues/155). To be honest, I'm not sure who the culprit is. To my knowledge the package is setting a seed to all possible sources of randomness that allow for seed control. I suspect [`scipy.minimize`](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/util.py#L55) might be the source of problem here, but, as I said, not sure.

Help with debugging this is more than appreciated. I won't have the opportunity to chase this bug down for a little while still.

**Comment by fmfn** [comment]
Closing this to keep all relevant discussion in #155 .
