### ISSUE TITLE
Add `RandomOptimization`

### ISSUE THREAD

**Issue by sotte** [fmfn/BayesianOptimization#162]
I really like this the interface of this package!
Sometimes I wish there was `RandomOptimization` class so that I can do a random search with the same interface as `BayesianOptimization` (and maybe even parallelize it on all my cores).

If there is interest in this feature I could implement it.

**Comment by fmfn** [comment]
Far from a clean solution, but you could accomplish that with by running `optimizer.maximize(init_points=however_many_you_like, n_iter=0)`.

Or if you want more control (in order to parallelize over multiple machines, for example) you can also get sample by calling `optimizer.space.random_sample()`.

That being said PRs are always welcome! 😄

**Comment by sotte** [comment]
`optimizer.maximize(init_points=however_many_you_like, n_iter=0)` thats exactly what I did so far :)

I looked at the code real quick and evaluating the target function is a bit deeper down the level of abstractions than I would have liked in order to quickly implement this feature. For reference: https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/target_space.py#L169

That being said, something along these lines (of pseudo code) would do the trick.
```python
class RandomOptimization(Observable):
    ...
    def maximize(self, n_iter=25):
        self._prime_subscriptions()
        self.dispatch(Events.OPTMIZATION_START)

        for i in range(n_iter):
            self.probe(self.suggest(), lazy=True)

        def f(x):
            # TODO properly handly x conversion, see target_space.py
            y = self.space.target_func(x)
            return x, y

        with concurrent.futures.ProcessPoolExecutor(self.n_workers) as executor:
            for x, y in executor.map(f, self._queue)):
                self.register(x, y)

        self.dispatch(Events.OPTMIZATION_END)
```
