### ISSUE TITLE
Utility function to create `OptimizeResult` to reuse skopts plotting functions

### ISSUE THREAD

**Issue by sotte** [fmfn/BayesianOptimization#164]
`skopt` can create some nice visualizations for an optimization run.
![image](https://user-images.githubusercontent.com/79138/57539914-d1bbd480-734b-11e9-9155-d3115cee6564.png)
See https://scikit-optimize.github.io/notebooks/visualizing-results.html for more.

It would be nice if BayesianOptimization would also support this feature.

The plotting functions of skopt require a simple [`OptimizeResult`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.optimize.OptimizeResult.html) from scipy. If we turn the the results of BayesianOptimization into an `OptimizeResult` we could use the plotting functionality of skopt. I simple utility function could do the trick.

What do you think?

**Comment by sotte** [comment]
I just found an already existing implementation for this. It's part of neptune.ml tracking: https://neptune-contrib.readthedocs.io/user_guide/hpo/utils.html#hyper-parameter-optimization-utils

**Comment by fmfn** [comment]
Haha, wow, that's great news. 

Hum, those plots do look nice, and I would certainly not object to implementing them and adding it to the library. I'm not too familiar with partial dependence plots, but now I'm curious to know how they are built.

In any case a PR here would be greatly welcomed. Unfortunately I won't be able to dedicate any time to this feature in the foreseeable future.
