### ISSUE TITLE
Dealing with conditional hyperparameters

### ISSUE THREAD

**Issue by jredondopizarro** [fmfn/BayesianOptimization#168]
Greetings.

I would like to set up an experiment with  `number_of_layers` and `number_of_neurons_per_each_layer` hyperparameters, so I would need, for example, to exclude from the search space  the `number_of_neurons_in layer_4th` if the `number_of_layers` is < 4.
Is there some way of doing this?

Thanks in advance.

**Comment by fmfn** [comment]
Not elegantly, no.

However you could simply ignore the parameter `number_of_neurons_in_layer_4` within your function and rely on the algorithm picking up on the fact that the direction along `number_of_neurons_in_layer_4` is flat when `number_of_layers` < 4. 

As I said, not elegant, but to be honest conditional hyperparameters lies a bit outside the scope of this project. I'm not sure how (if) other libraries deal with it, but I suggest taking a look around.
