### ISSUE TITLE
Limitation of the probe points

### ISSUE THREAD

**Issue by rafaelpadilla** [fmfn/BayesianOptimization#169]
@fmfn,

First of all, thanks for the nice project.

I am trying to optimize a function with 4 variables and I have tried myself a great number of combinations among the space. I have about 1800 parameters to guide the optimization process and I am adding them with the `probe`  function before calling the `optimizer.maximize`.

The process starts well, the probes are all being tested normally. But the probe 180th is tested multiple times, as if it was repeated. Please, check the print below. Is there a limitation of the amount of predefined points we can pass to the optimizer?

![image](https://user-images.githubusercontent.com/31217453/58903888-d2425380-86dc-11e9-8f7f-18067adff5f6.png)

I really appreciate your help.

Regards

**Comment by fmfn** [comment]
What are the bounds for each of the four variables?

There are no explicit limitations on the number of probe points one can pass before starting the optimization. My suspicion here is that the process is done, the amount of uncertainty anywhere else is very small and due to numerical challenges the algorithm is trapped in this edge obsession ( I'm guessing (120, 0.5, 150, 0) is a boundary point, is that right?).

**Comment by rafaelpadilla** [comment]
@fmfn ,

Thanks for your reply. The bounds are (10, 120), (.4, .6), (1, 150), (0, 100) -> the order is as they appear in the image. These are the points I provide the process myself. The process hasn't attempted their points yet.

I already have those points beforehand. So, as the instruction says, I want to run those points with `optimizer.probe` to help the process, giving it an overview of my function before it starts trying their own values.

My list of probe points has only one occurrence of each with a total of 1800 points. The process is not even trying them all and keeps testing the 180th point multiple times.

I really appreciate your help.

**Comment by fmfn** [comment]
That sounds really weird. When `optimizer.probe` is called (with the parameter `lazy=True`, which is the default) the point is simply added to a queue. Points in the cue are probed first when calling `optimizer.maximize`, so what you're seeing really shouldn't happen.

You can check that all your points were added to the queue by making sure `assert len(optimizer._queue) == 1800` doesn't raise an error.

To get to the bottom of this I think I would need to look at the entire code you're trying to run.
