### ISSUE TITLE
Returning n points

### ISSUE THREAD

**Issue by SalemAmeen** [fmfn/BayesianOptimization#17]
If the goal return n points the maximize the unknown function, is it possible to use Bayesian optimization in this package. For example, I tried with function (x-1)**2 (( x mines one square)), it is always return one number. Do any one has an idea how implement it to return n points?

PS: I am sorry this is not an issue but I could not find any other place to ask.

**Comment by fmfn** [comment]
I'm not exactly sure I understood your question. Are asking if (how) the BayesianOptimization object could return more than one point at each iteration?

**Comment by SalemAmeen** [comment]
Yes, please

**Comment by fmfn** [comment]
Hum, the method doesn't naturally accommodate multiple suggestions per step; it is supposed to be applied in an online fashion, as implemented.

One could come up with some hacks such as returning not only the maximum of the acquisition function, but other optimal values as well. However deciding which non-maximal values are useful (far enough from the maximum) is a challenging question.

I believe there some research on this subject that generalizes this method in various different ways, unfortunately I am not too familiar with it, so maybe searching the appropriate references could be a good place to start.

**Comment by SalemAmeen** [comment]
MANY Thanks @fmfn
