### ISSUE TITLE
Data type for points

### ISSUE THREAD

**Issue by kellertobias** [fmfn/BayesianOptimization#171]
I am having an optimization problem where some parameters are integers (such as the amount of lookahead steps).

Is there a way to tell the optimizer that one of the parameters is no float or does it not matter?

**Comment by fmfn** [comment]
It does matter, but the solution (adopted in this library) is not particularly elegant, see the [advanced tour notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) (2. Dealing with discrete parameters).

**Comment by syrte** [comment]
I think @fmfn 's proposed solution is well supported by a recent paper [Karlsson et al 2020 - Continuous surrogate-based optimization algorithms are well-suited for expensive discrete problems](https://arxiv.org/abs/2011.03431). I quote their conclusion here 
> Based on the results from these two problems, it appears that BO works well on ordinal structures. ... the naive approach with BO outperforms the other state-of-the-art discrete algorithms on the problems that we have discussed so far.  

A slightly more complicated scheme with better performance is [Garrido-Merchan & Hernandez-Lobato 2018 - Dealing with Categorical and Integer-valued Variables in Bayesian Optimization with Gaussian Processes](https://arxiv.org/abs/1805.03463). They also provide comparison of the two schemes. Both are rather easy to implement in the framework of the package BayesianOptimization.

Related issues: https://github.com/fmfn/BayesianOptimization/issues/24 https://github.com/fmfn/BayesianOptimization/issues/63 https://github.com/fmfn/BayesianOptimization/issues/81 https://github.com/fmfn/BayesianOptimization/issues/191

Here I just want to summarize what I have just learnt, which might be helpful for interested users.
