### ISSUE TITLE
Passing a list of parameters and results

### ISSUE THREAD

**Issue by rafaelpadilla** [fmfn/BayesianOptimization#172]
@fmfn,

I really appreciate your help on this point:

Let's say that during the optimization process I want to give the optimizer already **known** points and their target values. For instance:

During the optimization process I realize the following points (that were not probed by the tool) have known target values:
{'target': -4.44, 'params': {'y': 1, 'x': 2}}
{'target': -3.12, 'params': {'y': 2, 'x': 3}}

How can I inform the process that I have a set of parameters with their respective target values (that were externally generated)? How to make it consider these points when probing next points?

I might have to use the TargetSpace class, but I am not sure if I just pass the values to the function `register` is enough. Will it just add them in  the `_cache` tested points? Or will it also consider those points in the next iterations?

Thanks in advance,
Rafael

**Comment by fmfn** [comment]
`optimizer.register(params={'x': 2, 'y': 1}, target=-4.44)`

It will register this observation and use it next time you ask for a suggestion and/or run the `maximize` method. See the advanced tour notebook (1. Suggest-Evaluate-Register Paradigm) for more details.
