### ISSUE TITLE
The optimizer does not return the parameters regarding the largest target value!

### ISSUE THREAD

**Issue by SongWang2017** [fmfn/BayesianOptimization#173]
Hi there! Thanks for implementing this terrific tool, which greatly reduce my work.

When I tried the example scripts titled sklearn_example.py (https://github.com/fmfn/BayesianOptimization/blob/master/examples/sklearn_example.py).
The original code is working as expected and return the parameters regarding the best target value.

I modified my code to try the regression problem, and modified the code to try svr, the terminal outputed 15 rounds of evaluation(with initial points set to 5 and n_iter = 10), then I can see the first 8 rounds moves in the direction of maximize target. However the 9th round output a target value significantly smaller (two orders smaller), and then from 9th round to 15th round, the target value again was increasing, and the output returned the maximum value found in the latter rounds and is clearly much smaller than the value find in the first 8 rounds.

Would anyone kindly have a look at the code and output listed below and offer some suggestions?

the code: 
*def get_data():
    """Synthetic binary classification dataset."""
    data, targets = make_regression(
        n_samples=1000,
        n_features=12,
        n_informative=12,
        random_state=134985745,
    )
    scaler = preprocessing.StandardScaler().fit(data)
    data = scaler.transform(data)
    return data, targets*

*def svr_cv(C, gamma, data, targets):
    """SVC cross validation.
    This function will instantiate a SVC classifier with parameters C and
    gamma. Combined with data and targets this will in turn be used to perform
    cross validation. The result of cross validation is returned.
    Our goal is to find combinations of C and gamma that maximizes the roc_auc
    metric.
    """
    # estimator = SVR(C=C, gamma=gamma, random_state=2)
    estimator = SVR(C=C, gamma=gamma)
    cval = cross_val_score(estimator, data, targets, scoring= 'neg_mean_squared_error', cv=4, n_jobs=-1)
    return cval.mean()*

*def optimize_svr(data, targets):
    """Apply Bayesian Optimization to SVC parameters."""
    def svr_crossval(expC, expGamma):
        """Wrapper of SVC cross validation.
        Notice how we transform between regular and log scale. While this
        is not technically necessary, it greatly improves the performance
        of the optimizer.
        """
        C = 10 ** expC
        gamma = 10 ** expGamma
        return svr_cv(C=C, gamma=gamma, data=data, targets=targets)

    optimizer = BayesianOptimization(
        f=svr_crossval,
        pbounds={"expC": (-3, 2), "expGamma": (-4, -1)},
        random_state=1234,
        verbose=2
    )
    # optimizer.maximize(
    #     init_points=2,
    #     n_iter=3,
    # )
    optimizer.maximize(init_points=5, n_iter=10)

    print("Final result:", optimizer.max)*

*if __name__ == "__main__":
    data, targets = get_data()
    print(data[:5, :])
    print(targets[:5])
    print(Colours.yellow("--- Optimizing SVM ---"))
    optimize_svr(data, targets)*

and the output:
--- Optimizing SVM ---
|   iter    |  target   |   expC    | expGamma  |
-------------------------------------------------
|  1        | -4.167e+0 | -2.042    | -2.134    |
|  2        | -4.082e+0 | -0.8114   | -1.644    |
|  3        | -3.939e+0 |  0.8999   | -3.182    |
|  4        | -4.155e+0 | -1.618    | -1.594    |
|  5        | -1.466e+0 |  1.791    | -1.372    |
|  6        | -1.483e+0 |  1.793    | -1.368    |
|  7        | -1.344e+0 |  1.77     | -1.402    |
|  8        | -1.208e+0 |  1.752    | -1.437    |
|  9        | -781.3    |  1.844    | -1.545    |
|  10       | -777.3    |  1.829    | -1.549    |
|  11       | -754.2    |  1.831    | -1.557    |
|  12       | -572.5    |  1.864    | -1.628    |
|  13       | -448.3    |  1.926    | -1.686    |
|  14       | -393.7    |  1.977    | -1.714    |
|  15       | -379.2    |  2.0      | -1.721    |
=================================================
Final result: {'target': -379.21250753066306, 'params': {'expC': 2.0, 'expGamma': -1.7207328291072168}}

**Comment by fmfn** [comment]
If you call `optimizer.res` you will see what's going on. Basically what's being printed is misleading, those are not `e+0`, but `e+04` and so on.

Thanks for finding this, I will tinker with the width of the target column to avoid this confusion.
