### ISSUE TITLE
optimization over samples

### ISSUE THREAD

**Issue by nshervt** [fmfn/BayesianOptimization#174]
I have a set of samples with 2 dimensions and have a continuous function that calculates their target value and would like to find the maximum of this function moving only on these points. Figure below shows my samples, colored by their target values. 
![image](https://user-images.githubusercontent.com/30446938/61496135-3ec19b00-a989-11e9-83f7-ef53ed90d560.png)

I tried using prob to find the maximum, but it looks like that this just evaluates the value and probably constructs a prior for iterations. 

![image](https://user-images.githubusercontent.com/30446938/61496126-379a8d00-a989-11e9-8c35-8793600e033a.png)

I was wondering if there is a way to do the optimization process only among samples. Thanks!

**Comment by aljubrmj** [comment]
You could suggest, round to nearest sample, evaluate, then register--and repeat
