### ISSUE TITLE
A magic error about KeyError

### ISSUE THREAD

**Issue by UCASJingKun** [fmfn/BayesianOptimization#175]
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-244-da9dc47137ae> in <module>
      1 optimizer.maximize(
      2     init_points=0,
----> 3     n_iter=10,
      4 )

~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
    172                 iteration += 1
    173 
--> 174             self.probe(x_probe, lazy=False)
    175 
    176         self.dispatch(Events.OPTMIZATION_END)

~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py in probe(self, params, lazy)
    110             self._queue.add(params)
    111         else:
--> 112             self._space.probe(params)
    113             self.dispatch(Events.OPTMIZATION_STEP)
    114 

~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/target_space.py in probe(self, params)
    192         except KeyError:
    193             params = dict(zip(self._keys, x))
--> 194             target = self.target_func(**params)
    195             self.register(x, target)
    196         return target

<ipython-input-241-146e107cd9d9> in black_box_function(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta)
    126     while epoch < args.epochs + 1:
    127         epoch_start_time = time.time()
--> 128         train()
    129         if 't0' in optimizer.param_groups[0]:
    130             tmp = {}

~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/target_space.py in probe(self, params)
    189 
    190         try:
--> 191             target = self._cache[_hashable(x)]
    192         except KeyError:
    193             params = dict(zip(self._keys, x))

KeyError: (0.0, 1.0, 0.99, 0.99, 0.99, 0.0, 0.99, 20.0)

------------------------------------------------------------
'(0.0, 1.0, 0.99, 0.99, 0.99, 0.0, 0.99, 20.0)' is the parameter of my black_box_function.
Why did it throw a KeyError instead of entering the 'except' in line 191 of 'target_space.py'?

**Comment by UCASJingKun** [comment]
@fmfn I try my best to find the problem, but I am still not sure where the problem is. When the function is simple, such as:
def black_box_function(x,y):
    return x+x/y
, it's OK.

**Comment by fmfn** [comment]
Can you share the function definition, please? And the optimizer constructor call? Hard to figure out what's happening without either. I can say that your parameter looks suspicious, each parameter should (most likely) be a single number, not a tuple.

**Comment by UCASJingKun** [comment]
> Can you share the function definition, please? And the optimizer constructor call? Hard to figure out what's happening without either. I can say that your parameter looks suspicious, each parameter should (most likely) be a single number, not a tuple.

The function is too long. It's a function of training and evaluation neural network. Its return is -loss.
`# function
def update_superpara(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta):
    args.lr = lr
    args.dropout = dropout
    args.dropouth = dropouth
    args.dropoutx = dropoutx
    args.dropouti = dropouti
    args.dropoute = dropoute
    args.alpha = alpha
    args.beta = beta

genotype = eval("genotypes.%s" % args.arch)
logging.info('Genotype: {}'.format(genotype))

def black_box_function(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta):
    update_superpara(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta)
    
    # Get model.
    ntokens = len(corpus.dictionary)
    model = RNNModel(ntokens, args.emsize, args.nhid, args.nhidlast, 
                       args.dropout, args.dropouth, args.dropoutx, args.dropouti, args.dropoute, 
                       cell_cls=DARTSCell, genotype=genotype)
    parallel_model = model.cuda()
    # Log model info.
    total_params = sum(x.data.nelement() for x in model.parameters())
    logging.info('Args: {}'.format(args))
    logging.info('Model total parameters: {}'.format(total_params))
    
    # Training and evaluation.
    def evaluate(data_source, batch_size=10):
        # Turn on evaluation mode which disables dropout.
        model.eval()
        total_loss = 0
        ntokens = len(corpus.dictionary)
        hidden = model.init_hidden(batch_size)
        for i in range(0, data_source.size(0) - 1, args.bptt):
            data, targets = get_batch(data_source, i, args, evaluation=True)
            targets = targets.view(-1)

            log_prob, hidden = parallel_model(data, hidden)
            loss = nn.functional.nll_loss(log_prob.view(-1, log_prob.size(2)), targets).data

            total_loss += loss * len(data)

            hidden = repackage_hidden(hidden)
        return total_loss[0] / len(data_source)

    def train():
        assert args.batch_size % args.small_batch_size == 0, 'batch_size must be divisible by small_batch_size'

        # Turn on training mode which enables dropout.
        total_loss = 0
        start_time = time.time()
        ntokens = len(corpus.dictionary)
        hidden = [model.init_hidden(args.small_batch_size) for _ in range(args.batch_size // args.small_batch_size)]
        batch, i = 0, 0
        while i < train_data.size(0) - 1 - 1:
            bptt = args.bptt if np.random.random() < 0.95 else args.bptt / 2.
            # Prevent excessively small or negative sequence lengths
            seq_len = max(5, int(np.random.normal(bptt, 5)))
            # There's a very small chance that it could select a very long sequence length resulting in OOM
            seq_len = min(seq_len, args.bptt + args.max_seq_len_delta)

            lr2 = optimizer.param_groups[0]['lr']
            optimizer.param_groups[0]['lr'] = lr2 * seq_len / args.bptt
            model.train()
            data, targets = get_batch(train_data, i, args, seq_len=seq_len)

            optimizer.zero_grad()

            start, end, s_id = 0, args.small_batch_size, 0
            while start < args.batch_size:
                cur_data, cur_targets = data[:, start: end], targets[:, start: end].contiguous().view(-1)

                # Starting each batch, we detach the hidden state from how it was previously produced.
                # If we didn't, the model would try backpropagating all the way to start of the dataset.
                hidden[s_id] = repackage_hidden(hidden[s_id])

                log_prob, hidden[s_id], rnn_hs, dropped_rnn_hs = parallel_model(cur_data, hidden[s_id], return_h=True)
                raw_loss = nn.functional.nll_loss(log_prob.view(-1, log_prob.size(2)), cur_targets)

                loss = raw_loss
                '''# Activiation Regularization
                if args.alpha > 0:
                    loss = loss + sum(args.alpha * dropped_rnn_h.pow(2).mean() for dropped_rnn_h in dropped_rnn_hs[-1:])
                # Temporal Activation Regularization (slowness)
                loss = loss + sum(args.beta * (rnn_h[1:] - rnn_h[:-1]).pow(2).mean() for rnn_h in rnn_hs[-1:])'''
                loss *= args.small_batch_size / args.batch_size
                total_loss += raw_loss.data * args.small_batch_size / args.batch_size
                loss.backward()

                s_id += 1
                start = end
                end = start + args.small_batch_size

                gc.collect()

            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs.
            torch.nn.utils.clip_grad_norm(model.parameters(), args.clip)
            optimizer.step()

            # total_loss += raw_loss.data
            optimizer.param_groups[0]['lr'] = lr2

            if np.isnan(total_loss[0]):
                print('total_loss is nan')
                raise

            if batch % args.log_interval == 0 and batch > 0:
                cur_loss = total_loss[0] / args.log_interval
                elapsed = time.time() - start_time
                logging.info('| epoch {:3d} | {:5d}/{:5d} batches | lr {:02.2f} | ms/batch {:5.2f} | '
                        'loss {:5.2f} | ppl {:8.2f}'.format(
                    epoch, batch, len(train_data) // args.bptt, optimizer.param_groups[0]['lr'],
                    elapsed * 1000 / args.log_interval, cur_loss, math.exp(cur_loss)))
                total_loss = 0
                start_time = time.time()
            batch += 1
            i += seq_len
    
    # Loop over epochs.
    lr = args.lr
    best_val_loss = []
    stored_loss = 100000000
    optimizer = torch.optim.SGD(model.parameters(), lr=args.lr, weight_decay=args.wdecay)
    epoch = 1
    while epoch < args.epochs + 1:
        epoch_start_time = time.time()
        train()
        if 't0' in optimizer.param_groups[0]:
            tmp = {}
            for prm in model.parameters():
                tmp[prm] = prm.data.clone()
                prm.data = optimizer.state[prm]['ax'].clone()

            val_loss2 = evaluate(val_data)
            logging.info('-' * 89)
            logging.info('| end of epoch {:3d} | time: {:5.2f}s | valid loss {:5.2f} | '
                    'valid ppl {:8.2f}'.format(epoch, (time.time() - epoch_start_time),
                                               val_loss2, math.exp(val_loss2)))
            logging.info('-' * 89)

            if val_loss2 < stored_loss:
                stored_loss = val_loss2

            for prm in model.parameters():
                prm.data = tmp[prm].clone()

        else:
            val_loss = evaluate(val_data, eval_batch_size)
            logging.info('-' * 89)
            logging.info('| end of epoch {:3d} | time: {:5.2f}s | valid loss {:5.2f} | '
                    'valid ppl {:8.2f}'.format(epoch, (time.time() - epoch_start_time),
                                               val_loss, math.exp(val_loss)))
            logging.info('-' * 89)

            if val_loss < stored_loss:
                stored_loss = val_loss

            if 't0' not in optimizer.param_groups[0] and (len(best_val_loss)>args.nonmono and val_loss > min(best_val_loss[:-args.nonmono])):
                logging.info('Switching!')
                optimizer = torch.optim.ASGD(model.parameters(), lr=args.lr, t0=0, lambd=0., weight_decay=args.wdecay)
            best_val_loss.append(val_loss)

        epoch += 1
    
    return -stored_loss

# optimizer
pbounds = {'lr': (1e-6, 20), 'dropout': (0, 0.99), 'dropouth': (0, 0.99), 'dropoutx': (0, 0.99), 'dropouti': (0, 0.99), 'dropoute': (0, 0.99), 'alpha': (0, 1), 'beta': (0, 1)}
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=2, # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
    random_state=1,
)

optimizer.maximize(
    init_points=0,
    n_iter=10,
)`

**Comment by UCASJingKun** [comment]
> Can you share the function definition, please? And the optimizer constructor call? Hard to figure out what's happening without either. I can say that your parameter looks suspicious, each parameter should (most likely) be a single number, not a tuple.

The function is too long. It's a function of training and evaluation neural network. Its return is -loss.
`def update_superpara(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta):
    args.lr = lr
    args.dropout = dropout
    args.dropouth = dropouth
    args.dropoutx = dropoutx
    args.dropouti = dropouti
    args.dropoute = dropoute
    args.alpha = alpha
    args.beta = beta

genotype = eval("genotypes.%s" % args.arch)
logging.info('Genotype: {}'.format(genotype))

def black_box_function(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta):
    update_superpara(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta)
    
    # Get model.
    ntokens = len(corpus.dictionary)
    model = RNNModel(ntokens, args.emsize, args.nhid, args.nhidlast, 
                       args.dropout, args.dropouth, args.dropoutx, args.dropouti, args.dropoute, 
                       cell_cls=DARTSCell, genotype=genotype)
    parallel_model = model.cuda()
    # Log model info.
    total_params = sum(x.data.nelement() for x in model.parameters())
    logging.info('Args: {}'.format(args))
    logging.info('Model total parameters: {}'.format(total_params))
    
    # Training and evaluation.
    def evaluate(data_source, batch_size=10):
        # Turn on evaluation mode which disables dropout.
        model.eval()
        total_loss = 0
        ntokens = len(corpus.dictionary)
        hidden = model.init_hidden(batch_size)
        for i in range(0, data_source.size(0) - 1, args.bptt):
            data, targets = get_batch(data_source, i, args, evaluation=True)
            targets = targets.view(-1)

            log_prob, hidden = parallel_model(data, hidden)
            loss = nn.functional.nll_loss(log_prob.view(-1, log_prob.size(2)), targets).data

            total_loss += loss * len(data)

            hidden = repackage_hidden(hidden)
        return total_loss[0] / len(data_source)

    def train():
        assert args.batch_size % args.small_batch_size == 0, 'batch_size must be divisible by small_batch_size'

        # Turn on training mode which enables dropout.
        total_loss = 0
        start_time = time.time()
        ntokens = len(corpus.dictionary)
        hidden = [model.init_hidden(args.small_batch_size) for _ in range(args.batch_size // args.small_batch_size)]
        batch, i = 0, 0
        while i < train_data.size(0) - 1 - 1:
            bptt = args.bptt if np.random.random() < 0.95 else args.bptt / 2.
            # Prevent excessively small or negative sequence lengths
            seq_len = max(5, int(np.random.normal(bptt, 5)))
            # There's a very small chance that it could select a very long sequence length resulting in OOM
            seq_len = min(seq_len, args.bptt + args.max_seq_len_delta)

            lr2 = optimizer.param_groups[0]['lr']
            optimizer.param_groups[0]['lr'] = lr2 * seq_len / args.bptt
            model.train()
            data, targets = get_batch(train_data, i, args, seq_len=seq_len)

            optimizer.zero_grad()

            start, end, s_id = 0, args.small_batch_size, 0
            while start < args.batch_size:
                cur_data, cur_targets = data[:, start: end], targets[:, start: end].contiguous().view(-1)

                # Starting each batch, we detach the hidden state from how it was previously produced.
                # If we didn't, the model would try backpropagating all the way to start of the dataset.
                hidden[s_id] = repackage_hidden(hidden[s_id])

                log_prob, hidden[s_id], rnn_hs, dropped_rnn_hs = parallel_model(cur_data, hidden[s_id], return_h=True)
                raw_loss = nn.functional.nll_loss(log_prob.view(-1, log_prob.size(2)), cur_targets)

                loss = raw_loss
                '''# Activiation Regularization
                if args.alpha > 0:
                    loss = loss + sum(args.alpha * dropped_rnn_h.pow(2).mean() for dropped_rnn_h in dropped_rnn_hs[-1:])
                # Temporal Activation Regularization (slowness)
                loss = loss + sum(args.beta * (rnn_h[1:] - rnn_h[:-1]).pow(2).mean() for rnn_h in rnn_hs[-1:])'''
                loss *= args.small_batch_size / args.batch_size
                total_loss += raw_loss.data * args.small_batch_size / args.batch_size
                #loss.backward()

                s_id += 1
                start = end
                end = start + args.small_batch_size

                gc.collect()

            # `clip_grad_norm` helps prevent the exploding gradient problem in RNNs.
            #torch.nn.utils.clip_grad_norm(model.parameters(), args.clip)
            #optimizer.step()

            # total_loss += raw_loss.data
            optimizer.param_groups[0]['lr'] = lr2

            if np.isnan(total_loss[0]):
                print('total_loss is nan')
                raise

            if batch % args.log_interval == 0 and batch > 0:
                cur_loss = total_loss[0] / args.log_interval
                elapsed = time.time() - start_time
                logging.info('| epoch {:3d} | {:5d}/{:5d} batches | lr {:02.2f} | ms/batch {:5.2f} | '
                        'loss {:5.2f} | ppl {:8.2f}'.format(
                    epoch, batch, len(train_data) // args.bptt, optimizer.param_groups[0]['lr'],
                    elapsed * 1000 / args.log_interval, cur_loss, math.exp(cur_loss)))
                total_loss = 0
                start_time = time.time()
            batch += 1
            i += seq_len
    
    # Loop over epochs.
    lr = args.lr
    best_val_loss = []
    stored_loss = 100000000
    optimizer = torch.optim.SGD(model.parameters(), lr=args.lr, weight_decay=args.wdecay)
    epoch = 1
    while epoch < args.epochs + 1:
        epoch_start_time = time.time()
        #train()
        if 't0' in optimizer.param_groups[0]:
            tmp = {}
            for prm in model.parameters():
                tmp[prm] = prm.data.clone()
                prm.data = optimizer.state[prm]['ax'].clone()

            val_loss2 = evaluate(val_data)
            logging.info('-' * 89)
            logging.info('| end of epoch {:3d} | time: {:5.2f}s | valid loss {:5.2f} | '
                    'valid ppl {:8.2f}'.format(epoch, (time.time() - epoch_start_time),
                                               val_loss2, math.exp(val_loss2)))
            logging.info('-' * 89)

            if val_loss2 < stored_loss:
                stored_loss = val_loss2

            for prm in model.parameters():
                prm.data = tmp[prm].clone()

        else:
            val_loss = evaluate(val_data, eval_batch_size)
            logging.info('-' * 89)
            logging.info('| end of epoch {:3d} | time: {:5.2f}s | valid loss {:5.2f} | '
                    'valid ppl {:8.2f}'.format(epoch, (time.time() - epoch_start_time),
                                               val_loss, math.exp(val_loss)))
            logging.info('-' * 89)

            if val_loss < stored_loss:
                stored_loss = val_loss

            if 't0' not in optimizer.param_groups[0] and (len(best_val_loss)>args.nonmono and val_loss > min(best_val_loss[:-args.nonmono])):
                logging.info('Switching!')
                optimizer = torch.optim.ASGD(model.parameters(), lr=args.lr, t0=0, lambd=0., weight_decay=args.wdecay)
            best_val_loss.append(val_loss)

        epoch += 1
    
    return -stored_loss`

`pbounds = {'lr': (1e-6, 20), 'dropout': (0, 0.99), 'dropouth': (0, 0.99), 'dropoutx': (0, 0.99), 'dropouti': (0, 0.99), 'dropoute': (0, 0.99), 'alpha': (0, 1), 'beta': (0, 1)}
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=2, # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
    random_state=1,
)
optimizer.maximize(
    init_points=0,
    n_iter=10,
)`

**Comment by UCASJingKun** [comment]
> Can you share the function definition, please? And the optimizer constructor call? Hard to figure out what's happening without either. I can say that your parameter looks suspicious, each parameter should (most likely) be a single number, not a tuple.

The function is too long. It's a function of training and evaluation of neural network. Its return is -loss.
`pbounds = {'lr': (1e-6, 20), 'dropout': (0, 0.99), 'dropouth': (0, 0.99), 'dropoutx': (0, 0.99), 'dropouti': (0, 0.99), 'dropoute': (0, 0.99), 'alpha': (0, 1), 'beta': (0, 1)}
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=2, # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
    random_state=1,
)
optimizer.maximize(
    init_points=0,
    n_iter=10,
)`

**Comment by themrzmaster** [comment]
Did you manage to fix this? i am having the same problem, i guess its a concurrency issue in my case

**Comment by atisman89** [comment]
Hello, I got a similar problem while I was using this framework to tune up hyper-parameters of an ML training process in Keras-TensorFlow. The stack trace is below:

```
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/contextlib.py", line 99, in __exit__
    self.gen.throw(type, value, traceback)
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 5652, in get_controller
    yield g
  File "/home/ubuntu/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/bayes_opt/target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.7, 1e-07, 0.01, 0.0)
```

My pbounds looks like:
```
pbounds = {'init_lr': (1e-3, 1e-2), 'final_lr': (1e-7, 1e-3), 'dropout': (0.3, 0.7), 'leaky_relu_slope': (0.0, 0.3)}
```

The error didn't happen when I first tried with the first three parameters but it happens when I added the fourth parameter `leaky_relu_slope`. I made sure that the fourth parameter is added to the optimization function.

The original issue was closed but it was not mentioned how it was resolved. @UCASJingKun, @fmfn, any input would be appreciated.

**Comment by AlexWan0** [comment]
When I got this error, it was because there was an error within my optimized function. Maybe try building the model separately and seeing if anything pops up?

**Comment by sk-sabit-faisal** [comment]
I got the same error,
File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (-0.331911981189704, 1.3219469606529488)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BayesianOptimization/BayesOptProblem2.py", line 64, in <module>
    optimizer.maximize(
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 195, in probe
    self.register(x, target)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 167, in register
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (-0.331911981189704, 1.3219469606529488)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BayesianOptimization/BayesOptProblem2.py", line 64, in <module>
    optimizer.maximize(
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\bayesian_optimization.py", line 174, in maximize
    self.probe(x_probe, lazy=False)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\bayesian_optimization.py", line 112, in probe
    self._space.probe(params)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 195, in probe
    self.register(x, target)
  File "C:\Users\faisal.sk\AppData\Local\Programs\Python\Python38\lib\site-packages\bayes_opt\target_space.py", line 167, in register
    self._target = np.concatenate([self._target, [target]])
  File "<__array_function__ internals>", line 5, in concatenate
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

the function defination is:
def black_box_function(x, y):
    v_x = phi(v(x))
 
    print(v_x)
    f_1 = (1/2)*np.dot(v_x, Q*v_x)
    print(f_1)
    f_2 = np.dot(lmbda, g(v_x))
    print(f_2)
    print("The thing we are sending in F, ", -(f_1 + f_2))
    return -(f_1 + f_2)

**Comment by sk-sabit-faisal** [comment]
> KeyError Traceback (most recent call last)
> in
> 1 optimizer.maximize(
> 2 init_points=0,
> ----> 3 n_iter=10,
> 4 )
> 
> ~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
> 172 iteration += 1
> 173
> --> 174 self.probe(x_probe, lazy=False)
> 175
> 176 self.dispatch(Events.OPTMIZATION_END)
> 
> ~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/bayesian_optimization.py in probe(self, params, lazy)
> 110 self._queue.add(params)
> 111 else:
> --> 112 self._space.probe(params)
> 113 self.dispatch(Events.OPTMIZATION_STEP)
> 114
> 
> ~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/target_space.py in probe(self, params)
> 192 except KeyError:
> 193 params = dict(zip(self._keys, x))
> --> 194 target = self.target_func(**params)
> 195 self.register(x, target)
> 196 return target
> 
> in black_box_function(lr, dropout, dropouth, dropoutx, dropouti, dropoute, alpha, beta)
> 126 while epoch < args.epochs + 1:
> 127 epoch_start_time = time.time()
> --> 128 train()
> 129 if 't0' in optimizer.param_groups[0]:
> 130 tmp = {}
> 
> ~/anaconda2/envs/pytorch0.3.1/lib/python3.6/site-packages/bayes_opt/target_space.py in probe(self, params)
> 189
> 190 try:
> --> 191 target = self._cache[_hashable(x)]
> 192 except KeyError:
> 193 params = dict(zip(self._keys, x))
> 
> KeyError: (0.0, 1.0, 0.99, 0.99, 0.99, 0.0, 0.99, 20.0)
> 
> '(0.0, 1.0, 0.99, 0.99, 0.99, 0.0, 0.99, 20.0)' is the parameter of my black_box_function.
> Why did it throw a KeyError instead of entering the 'except' in line 191 of 'target_space.py'?

I faced the same problem. as UCASJingKun  told previously, your parameter passing is wrong- you need to send only one value not a list or vector of values.

**Comment by tempdeltavalue** [comment]
```
d_train = lgb.Dataset(X_train, label=y_train)

def cross_val(
              num_leaves=8,
              ):
  
    N_FOLDS = 3
    MAX_BOOST_ROUNDS = 700

    params = {
    'objective': 'regression',
    'metric': 'tweedie' ,     
    'num_leaves': int(num_leaves),
    }

    cv_results = lgb.cv(params, 
                        d_train, 
                        num_boost_round=MAX_BOOST_ROUNDS, 
                        stratified=False # needed for continuous 
                        )
    
    return cv_results["tweedie-mean"] #tweedie-stdv
    
    
    
from bayes_opt import BayesianOptimization

space = {
    'num_leaves':(2,16),
    }


optimiser = BayesianOptimization(
    f = cross_val,
    pbounds = space,
    )
    
  optimiser.maximize()
```
  
  
  
  KeyError                                  Traceback (most recent call last)
[/usr/local/lib/python3.7/dist-packages/bayes_opt/target_space.py](https://localhost:8080/#) in probe(self, params)
    190         try:
--> 191             target = self._cache[_hashable(x)]
    192         except KeyError:

KeyError: (7.345870488081978,)

During handling of the above exception, another exception occurred:

ValueError                                Traceback (most recent call last)
4 frames
[/usr/local/lib/python3.7/dist-packages/bayes_opt/target_space.py](https://localhost:8080/#) in register(self, params, target)
    165 
    166         self._params = np.concatenate([self._params, x.reshape(1, -1)])
--> 167         self._target = np.concatenate([self._target, [target]])
    168 
    169     def probe(self, params):

<__array_function__ internals> in concatenate(*args, **kwargs)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)
