### ISSUE TITLE
Can no longer access .max attribute of BayesianOptimization object

### ISSUE THREAD

**Issue by bsehra** [fmfn/BayesianOptimization#177]
I've had no issues with this previously, but recently I ran a script to optimize random forest hyperparameters for maximum classification accuracy. The run is normal apart from when I wish to print out the set of parameters which maximise the accuracy score through the .max attribute.

Now I get an error:
AttributeError: 'BayesianOptimization' object has no attribute 'max'

Here is the relevent part of the code (I took your online script as a test):
    optimizer = BayesianOptimization(
        f=rfc_crossval,
        pbounds={
            "n_estimators": (100, 250),
            "min_samples_split": (2, 17),
            "max_features": (0, 1)
        },
        random_state=1234,
        verbose=1
    )
    optimizer.maximize(init_points=10, n_iter=25)

    print("Final result:", optimizer.max)

Error message:
print("Final result:", optimizer.max)
AttributeError: 'BayesianOptimization' object has no attribute 'max'

I've run older scripts and they also now give me the same error when they didn't before. Any idea what may have gone wrong?

**Comment by fmfn** [comment]
What version are you working with?

**Comment by stoplime** [comment]
How was this resolved? I have the same issue just from running the tutorials https://github.com/fmfn/BayesianOptimization/blob/master/examples/basic-tour.ipynb
print(optimizer.max)
AttributeError: 'BayesianOptimization' object has no attribute 'max'

I am running on version 1.0.1

**Comment by bsehra** [comment]
I upgraded my version to 1.0.0 after my initial post and it began to work for me again. I have yet to test version 1.0.1..

**Comment by grceliu** [comment]
Hi, I found the optimized parameters in optimizer.res['max']['max_params']
I'm in version 0.6.0 though.

**Comment by rahulvudari** [comment]
I am getting this error

AttributeError: 'BayesianOptimization' object has no attribute 'add_param_group'

**Comment by mp675** [comment]
I'm having a similar issue but with the Events
`logger = JSONLogger(path='.\notebooks\logs_single_fold_04202023.json')
screen_logger = ScreenLogger()
screen_logger._default_cell_size = 13
optimizer.subscribe(Events.OPTMIZATION_START, logger)
optimizer.subscribe(Events.OPTMIZATION_START, screen_logger)
optimizer.subscribe(Events.OPTMIZATION_END, logger)
optimizer.subscribe(Events.OPTMIZATION_END, screen_logger)
optimizer.subscribe(Events.OPTMIZATION_STEP, logger)
optimizer.subscribe(Events.OPTMIZATION_STEP, screen_logger)`

AttributeError                            Traceback (most recent call last)
Cell In[16], line 4
      2 screen_logger = ScreenLogger()
      3 screen_logger._default_cell_size = 13
----> 4 optimizer.subscribe(Events.OPTMIZATION_START, logger)
      5 optimizer.subscribe(Events.OPTMIZATION_START, screen_logger)
      6 optimizer.subscribe(Events.OPTMIZATION_END, logger)

AttributeError: type object 'Events' has no attribute 'OPTMIZATION_START'
