### ISSUE TITLE
NaN found and optimization stopped

### ISSUE THREAD

**Issue by Sceki** [fmfn/BayesianOptimization#180]
Hello, I am trying to do hyperparameter optimization using Bayesian optimization for neural networks. However, I encountered this issue: 
ValueError: Input contains NaN, infinity or a value too large for dtype('float64'). 

The weird thing is that when I try to run the same net where Bayesian optimization stops in a separate network (without optimization) I do not have any issue (no NaN’s found as mean squared error, i.e. the fitness, or anything else).

Do you know where this error come from?

(Similar issue to #178 , why was this closed?)

**Comment by Sceki** [comment]
With further investigation I found out that I was not seeding properly my script: when I did seed it properly I obtained the NaN also in the RNN w/o optimization. So this is not a proble related to your library, but rather a problem of the RNN (the gradient explodes, as pointed out here: https://stackoverflow.com/questions/37232782/nan-loss-when-training-regression-network).

However, I think it would still be helpful for users not to make the optimization crash when it encounters NaN or Inf.

**Comment by jablesblack** [comment]
Hi Sceki, I ran into the same issue. When the Bayesian optimizer gets a nan value for the mse (e.g, for one of the hyperparameter groups selected), it sometimes crashed with this error. Is this not an issue with the tuner itself? Shouldn't it be able to handle this case?
