### ISSUE TITLE
For discrete values, is rounding better than truncating?

### ISSUE THREAD

**Issue by yogi-dmt** [fmfn/BayesianOptimization#182]
The proposal to deal with discrete params with this library is just to create a wrapper function which casts to int. Would rounding make more sense as it doesn't favor upward or downward motion? By truncating a float dont you make it harder for the model to move up a value as opposed to down since you need to move much further from the best value?

**Comment by fmfn** [comment]
I think the difference will be negligible and/or situation dependent. A more principled approach is beyond the scope of this package (which is meant to be a simple, easy to use, BO tool).
