### ISSUE TITLE
How is parameter ranges determined?

### ISSUE THREAD

**Issue by ben-arnao** [fmfn/BayesianOptimization#183]
Obviously different params operate on different scales. So they require different scales of adjustment. I assume that the same scale isnt use for all parameters? If the range of search space and optimization is parameter specific. Is this determined by the bounds you supply for a parameter? Is there a way to manually set this value independent of bounds?

**Comment by fmfn** [comment]
This library is deliberately simple, so no, parameters scales are not taken care for you. And you are correct, if you're optimizing some parameter `alpha` in the `(0, 10000)` range you should probably transform it to log scale. So you would have something like this:

```
def my_func(alpha):
    ....

pbounds = {'alpha': (0, 10000)}
```
becoming:
```
def my_transformed_func(log_alpha):
    return my_func(exp(alpha))

pbounds = {'log_alpha': (0, log(10000))}
```
