### ISSUE TITLE
Adaptive Sampling on Functions with Multiple Output 

### ISSUE THREAD

**Issue by aljubrmj** [fmfn/BayesianOptimization#184]
Can you use this package only for adaptive sampling purposes (away from optimization) where I just want to fit the surface correctly with smallest number of points possible? Also, how can I use the package when my function has multiple outputs?

**Comment by fmfn** [comment]
> Also, how can I use the package when my function has multiple outputs?
You can't. The package is target towards optimization of single output black box functions.

> Can you use this package only for adaptive sampling purposes (away from optimization) where I just want to fit the surface correctly with smallest number of points possible?
I'm not sure exactly what you mean, but it sounds like this package will not help you much.
