### ISSUE TITLE
Supplying the optimizer with known values of the objective function

### ISSUE THREAD

**Issue by MateuszEggink** [fmfn/BayesianOptimization#186]
Assume you know the values of the objective function for e.g. 50 combinations of hyperparameters. Is it possible to supply those values to the optimiser during initialisation?

This is important in a situation when I ran the optimiser, collected the logs, and now (after some time) want to supply those logs to the optimiser and run it from there.

If it is possible, how could this be done?

**Comment by fmfn** [comment]
Yes. Checkout both [basic](https://github.com/fmfn/BayesianOptimization/blob/master/examples/basic-tour.ipynb) and [advanced](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) tours, they cover what you want.
