### ISSUE TITLE
scikit-learn's Gaussian Process bug might be affecting your results

### ISSUE THREAD

**Issue by Amir-Arsalan** [fmfn/BayesianOptimization#188]
This is not necessarily an issue with `bayes_opt` but it's highly related and therefore I thought I should let you know about it.

Recently, I found a bug that I recently [found](https://github.com/scikit-learn/scikit-learn/issues/15612) in scikit-learn's Gaussian Process module that might be affecting the results you get from `bayes_opt` since `bayes_opt` uses scikit-learn's GP module as the surrogate model. However, in case `bayes_opt` only depends on the _relative_ standard deviation values, which I think is the case, you will be safe and probably the bug won't be affecting you that much. That's why I asked the scikit-learn developers in [one of the comments](https://github.com/scikit-learn/scikit-learn/issues/15612#issuecomment-555082985) to add a flag whose `False` value will basically return the _relative_ std values that are within [0, 1]. But in case `bayes_opt` depends on the actual values of the standard deviation it is almost certain that you need to run your experiments again once this bug is fixed.

Also, the scikit-learn developers say they are busy at the moment and who knows when they're gonna be able to fix the issue. So maybe you can help them fix the bug and fix this issue as soon as possible.

**Comment by Amir-Arsalan** [comment]
@fmfn Could you confirm if `bayes_opt` only cares about _relative_ standard deviation values or does it actually matter for the GP module to return the actual std values?

**Comment by fmfn** [comment]
Thanks for bringing this up! I will investigate further, but a quick glance seems to indicate it may be affecting this package.

**Comment by Amir-Arsalan** [comment]
@fmfn Sorry to ask again but I need make sure whether `bayes_opt` needs the actual standard deviation values or not. Could you clarify this? In case `bayes_opt` needs the actual std valus, do you know if there is a way to get the actual std values from the predicted std values of scikit-learn's GP that are within the range [0-1]?

**Comment by raff7** [comment]
i noticed that it's a big problem when the output of your black box function are in a range for which a STD of 1 is way to small to be an appropriate prior. I went around this by basically adding a parameter of "expected y range" and then normalizing the output of the black box function so that a standard deviation of 1 is appropriate

**Comment by Amir-Arsalan** [comment]
The scikit-learn developers are fixing this issue. [Here](https://github.com/scikit-learn/scikit-learn/pull/15782#discussion_r368518368)'s a pull request for it.

**Comment by ben-arnao** [comment]
@Amir-Arsalan This bug has been fixed. Would you mind closing the issue as to not confuse anyone? Thank you.
