### ISSUE TITLE
How to add constraint that inputs must add up to a certain number?

### ISSUE THREAD

**Issue by vivekraja07** [fmfn/BayesianOptimization#190]
For example, how do I say that x + y, each between 0 and 1, must sum to 1?

**Comment by Atarust** [comment]
f=lambda x: f(x=x,y=(x-1))

**Comment by vivekraja07** [comment]
@Atarust , thank you so much for your input, but I am still a little confused on the exact syntax. To be more precise on the exact problem I am facing. My function takes 4 weights, w1, w2, w3, and w4. I want each of these weights to be between 0 and 1, and the sum of the 4 to be 1.  However, I know that I would only want w1, w2, and w3 to be the parameters my function optimizes on, since w4 can be defined as 1 - sum(w1,w2,w3)

**Comment by Atarust** [comment]
I think, If multiple values need to add up to 1 the problem becomes much harder.  It looks like constrained optimization. The problem is, just sampling w1,w2,w3 from the interval [0,1] might already give a sum greater than 1 - so there is no way to choose a positive w4 such that it adds up to one. For the case where we only had w1, that did not happen. I am unsure what to do about it.

**Comment by Arktius** [comment]
I have a problem that is related to yours. I'm going to train Autoencoders and I want to optimize the number of neurons for the decoder and encoder part. My condition is:

d := number of neurons for decoder
e := number of neurons for encoder

d >= e and both have to be a multiple of 8.

This is what I wrote:

f=lambda DecNeurons,EncNeurons: AE(NeuronConstraint(DecNeurons,EncNeurons))

As you can see from my output, it works.

   iter      target    **DecNeu**  **EncNeu** 
|  1        | -0.7086   |  **52.02**    |  **66.58**    |
NEURONS:  [**72**, **64**, 16, 64, 72]

I now have the problem, that the optimizer doesn't work with the actual parameters. So how can I change the used parameters of the optimizer?

To tackle your problem, write a function that deals with your parameters:
f=lambda a,b,c,d: f(YOURFUNCTION(a,b,c,d))

def YOURFUNCTION(a,b,c,d):
#calculate a,b,c,d to be one summed up
return a,b,c,d

**Comment by Arktius** [comment]
Check out the advances tour [(URL)](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb).
It's explained there how to suggest the next point, to evaluate and to register the point+target. You just have to alter the point that you want to evaluate.
