### ISSUE TITLE
Giving previous output to Bayesian Optimiser

### ISSUE THREAD

**Issue by DG6666666** [fmfn/BayesianOptimization#192]
Can we give the input in csv to Bayesian Optimiser to start the iterations considering the previous outputs? How can we do this?

**Comment by rty2018** [comment]
Did you solve it？I have the same question.

**Comment by DG6666666** [comment]
Refer https://github.com/fmfn/BayesianOptimization/blob/master/examples/basic-tour.ipynb

**Comment by rty2018** [comment]
my previous outputs is xlsx,not json

> Refer https://github.com/fmfn/BayesianOptimization/blob/master/examples/basic-tour.ipynb
