### ISSUE TITLE
TypeError: 'int' object is not subscriptable , after several iteration

### ISSUE THREAD

**Issue by nchos88** [fmfn/BayesianOptimization#193]
![image](https://user-images.githubusercontent.com/36718545/71148216-6be2e400-226e-11ea-9755-96d037c99e64.png)

os : windows 10 64bits
python : 3.7
Lib : xgboost , sklearn

I got this error randomly.

**Comment by ben-arnao** [comment]
I think it is telling you right there...

your get_max_f1_cutoff() function returns an int, and you are treating it's output as an array.
