### ISSUE TITLE
Do we need to normalize input value?

### ISSUE THREAD

**Issue by ThyrixYang** [fmfn/BayesianOptimization#198]
For example, we have parameter x1 within range(-10, 10) and x2 within range(-0.1, 0.1), do we need to normalize both x1 and x2 to e.g. range(-1.0, 1.0) for better performance?

I found that some parameter stuck on an ending point in the very beginning and never change after that, is this an outcome of different scale of input paramters?

**Comment by raff7** [comment]
I don't think normalizing the parameters is necessary becaue the kernel's length scale is optimized with the inputs, so it will automatically deal with different scale in inputs, what I foud is crucial tho is to normalize the output of the function f(x) (because the prior assumes a variance of 1, which is way to small if the output function has a range like -100 to 100 ). I'd appreciate somebody else's feedback!

**Comment by Arktius** [comment]
I'm trying to optimize deep autoencoders and I had the following issue. After evaluating 150 random parameter setups, I used optimizer.suggest(utility) to get the next point to probe. What then happened was that I almost always got either the lower or upper limits for each parameter. I've used UCB and with kappa = 5,10,15.
I did some quick research about Gaussian Processes(GP) and found out that the data should be either standardized or normalized. I don't know the underlying maths behind this, but for the moment, my answer would be 'Yes, parameters with different scales need to be in the same range'.

**Comment by fmfn** [comment]
[Data is already being normalized before given to internal GP](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L79). The obsession with the edges happens sometimes and is often mitigated by increasing UCB's `kappa`, GP's `alpha`, adding more random iterations steps, changing the range, or a combination of all above.

**Comment by virtualclone** [comment]
@fmfn, "Data is already being normalized before given to internal GP." 
I see that only y (output) is normalized in GaussianProcessRegressor.
So, input isn't normalized, right?
