### ISSUE TITLE
not working if objective function score is negative

### ISSUE THREAD

**Issue by nchos88** [fmfn/BayesianOptimization#199]
-714 is better than -1 with -1 * rmse  score

what is problem? 

![bay](https://user-images.githubusercontent.com/36718545/72235702-f96be680-3616-11ea-9a22-105e41396bdd.png)

score function is calculated like below 
`result = -1 * mean_squared_error(ytest, pred)`

**Comment by raff7** [comment]
Hi, I gave a good look to this. It is not a bug, it's just a formatting issue. the -1.079e+0 is not -1.079, the line was cut short and it was probably something like -1.079e+03, which indeed is smaller then -714.
In no case you will get a e+0 output, if you see that be aware that there is some other part missing

**Comment by masoudMZB** [comment]
does this library have any minimize method? in that case there is no need to -1 * rmse
