### ISSUE TITLE
Examples fail with new version of scikit-learn

### ISSUE THREAD

**Issue by mpearmain** [fmfn/BayesianOptimization#2]
Testing examples with latest version of scikit-learn, scipy and numpy the examples fail

import sklearn as sk
sk.__version__
'0.16.1'

import numpy as np
np.__version__
'1.9.2'

import scipy as sp
sp.__version__
'0.16.0'

**Comment by fmfn** [comment]
Hum, thanks for letting me know. I'll investigate what's happening, in the mean time, do you mind sharing more details of what is happening, like, the error message you get?

**Comment by mpearmain** [comment]
Sure

Running sklearn example:

Initializing function at point:  {'C': 0.001, 'gamma': 0.001} | result: 0.667377
Initializing function at point:  {'C': 0.01, 'gamma': 0.01} | result: 0.672580
Initializing function at point:  {'C': 0.1, 'gamma': 0.1} | result: 0.667377
Initializing function at point:  {'C': 93.618927021851661, 'gamma': 0.047491978272029771} | result: 0.906071
Initializing function at point:  {'C': 61.732592095876811, 'gamma': 0.005739499246811503} | result: 0.925864
Initializing function at point:  {'C': 50.202721312204552, 'gamma': 0.096671502528878087} | result: 0.779066
Initializing function at point:  {'C': 50.819923230048033, 'gamma': 0.062876659906857285} | result: 0.884052
Initializing function at point:  {'C': 1.0952913999608358, 'gamma': 0.033743101147419303} | result: 0.923517


Traceback (most recent call last):
  File "/Users/michael.pearmain/Library/Python/2.7/lib/python/site-packages/IPython/core/interactiveshell.py", line 2883, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-3-d60e755e4967>", line 38, in <module>
    svcBO.maximize()
  File "/Users/michael.pearmain/gitpackages/BayesianOptimization/bayesian_optimization.py", line 316, in maximize
    gp.fit(self.X[ur], self.Y[ur])
  File "/usr/local/lib/python2.7/site-packages/sklearn/gaussian_process/gaussian_process.py", line 338, in fit
    self._arg_max_reduced_likelihood_function()
  File "/usr/local/lib/python2.7/site-packages/sklearn/gaussian_process/gaussian_process.py", line 729, in _arg_max_reduced_likelihood_function
    iprint=0)
  File "/usr/local/lib/python2.7/site-packages/scipy/optimize/cobyla.py", line 177, in fmin_cobyla
    **opts)
  File "/usr/local/lib/python2.7/site-packages/scipy/optimize/cobyla.py", line 244, in _minimize_cobyla
    f = c['fun'](x0, *c['args'])
  File "/usr/local/lib/python2.7/site-packages/sklearn/gaussian_process/gaussian_process.py", line 706, in <lambda>
    log10t[i] - np.log10(self.thetaL[0, i]))
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by fmfn** [comment]
Ok. The new scipy broke something, I will figure out what happened.

**Comment by tbsexton** [comment]
Just wanted to chime in, we're getting this same error here: https://github.com/tbsexton/SkynetOrbital 

In the main file, running it will lead to an identical error since scipy 0.16.... 0.15 was working. It seems to be a problem in the cobyla usage of the constraint functions. The lambda is getting called on a list with only one row and 5 columns. so, calling log10t[i] does not exist.

**Comment by fmfn** [comment]
Thank you. I haven't had the chance to investigate it this past weekend, will do so in the next couple of days.

**Comment by fmfn** [comment]
Problem solved (avoided). Something is happening between sklearn's GP and scipy 0.16 when you pass upper and lower bound for the parameters theta. I changed slightly the GP object inside this module, so it should work just fine from now on.

See commit ad67b00

**Comment by mpearmain** [comment]
Did you have any plans on a re-vamp with the new 0.17 release of scikit and the fully revamped GP objects?

**Comment by fmfn** [comment]
Was it revamped? I didn't see any mention to GPs on the release notes. But yes, I would like to make some changes, I might give it a go in the next couple of weeks.

**Comment by mpearmain** [comment]
Sorry - Revamped bad wording, but with v0.17 there are deprecation warning using examples/usage.py

/usr/local/lib/python2.7/site-packages/sklearn/utils/validation.py:386: DeprecationWarning: Passing 1d arrays as data is deprecated in 0.17 and willraise ValueError in 0.19. Reshape your data either using X.reshape(-1, 1) if your data has a single feature or X.reshape(1, -1) if it contains a single sample.
  DeprecationWarning)
