### ISSUE TITLE
 Dealing with discrete parameters (Advanced Tour) - Why is 'w' still of type float sometimes?

### ISSUE THREAD

**Issue by Arktius** [fmfn/BayesianOptimization#201]
Hey folks, I'm halfway through with the advanced tour and a question came up. They cast the parameter w to int, but the optimizer saved it as float anyways. 

![image](https://user-images.githubusercontent.com/31614164/73921300-5893e280-48c7-11ea-99bb-9790d1b3d45f.png)

Why can't one use the approach from the 1st paragraph Suggest-Evaluate-Register Paradigm and alter the suggested point before handing it in? 

```
optimizer = BayesianOptimization(
    f=None,
    pbounds={'x': (-10, 10), 'y': (-10, 10), 'w': (0, 5)},
    verbose=2,
    random_state=1,
)
from bayes_opt import UtilityFunction
utility = UtilityFunction(kind="ucb", kappa=2.5, xi=0.0)

next_point_to_probe = optimizer.suggest(utility)
next_point_to_probe.update({'w':int(next_point_to_probe['w']}) 

target = black_box_function(**next_point_to_probe)
print("Found the target value to be:", target)


optimizer.register(
    params=next_point_to_probe,
    target=target,
)
```

Am I overlooking something?

**Comment by ben-arnao** [comment]
@Arktius AFAIK the BO still works only in floats. You are more or less providing a wrapper that truncates variables before into enters your actual target function. Since this is the case you will also need to truncate your discrete variables after it goes through BO. I don't think this is the best way to deal with discrete params but it is what it is.

**Comment by Arktius** [comment]
What else could you recommend? I'm using truncated variables for my target function and the actual floating value for the BO. If your model is deterministic and you try to visualize it, one could think of a constant region in your target function.

**Comment by ben-arnao** [comment]
I mean I would rather the optimizer take care of deal with discrete
variables for me but just truncating isn't wrong, just maybe a bit
confusing.
