### ISSUE TITLE
Very high noise: how to get expectation for max, rather than point max?

### ISSUE THREAD

**Issue by MilesCranmer** [fmfn/BayesianOptimization#204]
Hi,

I have a very noisy model I'm optimizing, and I'm wondering how I can get the GP's prediction for the expectation[max] rather than the recorded max? The recorded max should vary wildly since there is so much noisy, but I think the expectation value for the max should be informative of the best parameters.

Thanks!
Miles

**Comment by ben-arnao** [comment]
If you have a lot of noise i believe you can increase `alpha` to help with that

bayes_opt/bayesian_optimization.py

```
...
# Internal GP regressor
        self._gp = GaussianProcessRegressor(
            kernel=Matern(nu=2.5),
            alpha=1e-6,
            normalize_y=True,
            n_restarts_optimizer=5,
            random_state=self._random_state,
        )
```

**Comment by fmfn** [comment]
> I can get the GP's prediction for the expectation[max] rather than the recorded max?

Use `optimizer._gp` to manipulate the internal GP and get your expectation surface. Making this a **useful** user facing feature is not trivial and I believe is beyond the scope of this package. PRs are always welcome though.
