### ISSUE TITLE
Suggested number of iterations

### ISSUE THREAD

**Issue by valerios1910** [fmfn/BayesianOptimization#209]
I'm looking for a "good" number of iterations relative to the dimensions, e.g. iterations = 50*dimensions. Yet I cannot find anything no matter where I look. Do you have any recommendations, or it is very problem- and algorithm-dependent?

Thanks

**Comment by ben-arnao** [comment]
I've 3 times the number if dimensions be used for initialize points.

**Comment by fmfn** [comment]
Definitely problem dependent, you can use rate of improvement as a guidance, but ultimately is up to you and how much time/effort you want to put in.
