### ISSUE TITLE
Verbose when logging

### ISSUE THREAD

**Issue by samyip123** [fmfn/BayesianOptimization#211]
When using the logger, the verbose is turned off with no output (verbose=0), is there any way to turn it back on

```
optimizer = BayesianOptimization(f=model,
                                     pbounds=pbounds,
                                     verbose=2,  # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
                                     random_state=1)
#Create Logger
logger = JSONLogger(path = './file_name.json')
#Update Logger for each hyperparameter combination
optimizer.subscribe(Events.OPTIMIZATION_STEP, logger)
optimizer.maximize(init_points=10, n_iter=10)
```

**Comment by fmfn** [comment]
Use `ScreenLogger(verbose=verbose)`, and subscribe to `start`, `step`, and `end` events.
In fact, that's what's going on by default when verbose is set: https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L147
