### ISSUE TITLE
book or resource that explains the math

### ISSUE THREAD

**Issue by nyck33** [fmfn/BayesianOptimization#215]
I am watching this lecture:  https://www.youtube.com/watch?v=vz3D36VXefI

I can sort of follow but are there any other resources for an undergrad CS student to learn the underlying math and principles?

**Comment by fmfn** [comment]
There are three other resources linked in the references section, two papers and one book, that cover this topic in extensive detail. I suggest starting there.
Bayesian stats and Gaussian Processes are really all you need to know.
