### ISSUE TITLE
TypeError: Dimension value must be integer or None or have an __index__ method

### ISSUE THREAD

**Issue by Kamalnor** [fmfn/BayesianOptimization#217]
Hi, I am doing a Bayesian Optimization to select hyperparameters for my LSTM network. I cannot understand the error given:

|   iter    |  target   |   batch   | dropout1  |  epochs   |  hidden1  |    lr     |   size1   |
-------------------------------------------------------------------------------------------------
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-143-f622304582cf> in <module>
     11 )
     12 
---> 13 optimizer.maximize(init_points=100, n_iter=100,)
     14 
     15 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bayes_opt\bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
    172                 iteration += 1
    173 
--> 174             self.probe(x_probe, lazy=False)
    175 
    176         self.dispatch(Events.OPTIMIZATION_END)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bayes_opt\bayesian_optimization.py in probe(self, params, lazy)
    110             self._queue.add(params)
    111         else:
--> 112             self._space.probe(params)
    113             self.dispatch(Events.OPTIMIZATION_STEP)
    114 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\bayes_opt\target_space.py in probe(self, params)
    192         except KeyError:
    193             params = dict(zip(self._keys, x))
--> 194             target = self.target_func(**params)
    195             self.register(x, target)
    196         return target

<ipython-input-142-f09a2564f2df> in fit_with(batch, dropout1, epochs, hidden1, lr, size1)
      2 
      3     # Create the model using a specified hyperparameters.
----> 4     model = get_model(input_shape, hidden1, size1, dropout1)
      5 
      6     # Train the model for a specified number of epochs.

<ipython-input-141-416f7e1dd46e> in get_model(input_shape, hidden1, size1, dropout1)
      4 def get_model(input_shape, hidden1, size1, dropout1):
      5     model2 = tf.keras.Sequential()
----> 6     model2.add(LSTM(hidden1,input_shape=input_shape, activation = 'sigmoid', recurrent_activation = 'tanh', kernel_regularizer = regularizers.l2(0.0001), recurrent_regularizer = regularizers.l2(0.0001), return_sequences=True))
      7     model2.add(Dense(size1, activation = 'sigmoid', kernel_regularizer = regularizers.l2(0.0001)))
      8     model2.add(Dropout(dropout1))

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\tracking\base.py in _method_wrapper(self, *args, **kwargs)
    455     self._self_setattr_tracking = False  # pylint: disable=protected-access
    456     try:
--> 457       result = method(self, *args, **kwargs)
    458     finally:
    459       self._self_setattr_tracking = previous_value  # pylint: disable=protected-access

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\sequential.py in add(self, layer)
    183           # and create the node connecting the current layer
    184           # to the input layer we just created.
--> 185           layer(x)
    186           set_inputs = True
    187 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py in __call__(self, inputs, initial_state, constants, **kwargs)
    642 
    643     if initial_state is None and constants is None:
--> 644       return super(RNN, self).__call__(inputs, **kwargs)
    645 
    646     # If any of `initial_state` or `constants` are specified and are Keras

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in __call__(self, inputs, *args, **kwargs)
    746           # Build layer if applicable (if the `build` method has been
    747           # overridden).
--> 748           self._maybe_build(inputs)
    749           cast_inputs = self._maybe_cast_inputs(inputs)
    750 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in _maybe_build(self, inputs)
   2114         # operations.
   2115         with tf_utils.maybe_init_scope(self):
-> 2116           self.build(input_shapes)
   2117       # We must set self.built since user defined build functions are not
   2118       # constrained to set self.built.

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py in build(self, input_shape)
    562     if isinstance(self.cell, Layer):
    563       if not self.cell.built:
--> 564         self.cell.build(step_input_shape)
    565 
    566     # set or validate state_spec

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\utils\tf_utils.py in wrapper(instance, input_shape)
    304     if input_shape is not None:
    305       input_shape = convert_shapes(input_shape, to_tuples=True)
--> 306     output_shape = fn(instance, input_shape)
    307     # Return shapes from `fn` as TensorShapes.
    308     if output_shape is not None:

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\layers\recurrent.py in build(self, input_shape)
   2299         regularizer=self.kernel_regularizer,
   2300         constraint=self.kernel_constraint,
-> 2301         caching_device=default_caching_device)
   2302     self.recurrent_kernel = self.add_weight(
   2303         shape=(self.units, self.units * 4),

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer.py in add_weight(self, name, shape, dtype, initializer, regularizer, trainable, constraint, partitioner, use_resource, synchronization, aggregation, **kwargs)
    444         synchronization=synchronization,
    445         aggregation=aggregation,
--> 446         caching_device=caching_device)
    447     backend.track_variable(variable)
    448 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\training\tracking\base.py in _add_variable_with_custom_getter(self, name, shape, dtype, initializer, getter, overwrite, **kwargs_for_getter)
    742         dtype=dtype,
    743         initializer=initializer,
--> 744         **kwargs_for_getter)
    745 
    746     # If we set an initializer and the variable processed it, tracking will not

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\keras\engine\base_layer_utils.py in make_variable(name, shape, dtype, initializer, trainable, caching_device, validate_shape, constraint, use_resource, collections, synchronization, aggregation, partitioner)
    127   # TODO(apassos,rohanj) figure out how to remove collections from here so we
    128   # can remove the V1.
--> 129   variable_shape = tensor_shape.TensorShape(shape)
    130   return tf_variables.VariableV1(
    131       initial_value=init_val,

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py in __init__(self, dims)
    769         self._dims = [as_dimension(dims)]
    770       else:
--> 771         self._dims = [as_dimension(d) for d in dims_iter]
    772 
    773   @property

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py in <listcomp>(.0)
    769         self._dims = [as_dimension(dims)]
    770       else:
--> 771         self._dims = [as_dimension(d) for d in dims_iter]
    772 
    773   @property

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py in as_dimension(value)
    714     return value
    715   else:
--> 716     return Dimension(value)
    717 
    718 

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\tensorflow_core\python\framework\tensor_shape.py in __init__(self, value)
    198             TypeError("Dimension value must be integer or None or have "
    199                       "an __index__ method, got {!r}".format(value)),
--> 200             None)
    201       if self._value < 0:
    202         raise ValueError("Dimension %d must be >= 0" % self._value)

c:\users\user\appdata\local\programs\python\python37\lib\site-packages\six.py in raise_from(value, from_value)

TypeError: Dimension value must be integer or None or have an __index__ method, got 1237.2369876220855

**Comment by ben-arnao** [comment]
If you want us to help you really should put in the effort to format your post properly (neat code block, full stack trace)

**Comment by Kamalnor** [comment]
Hi. Sorry. Im really a newbie in Github. By the way, I had solved this issue. Sorry again.
