### ISSUE TITLE
Problem to define objective function in numpy array

### ISSUE THREAD

**Issue by calm85** [fmfn/BayesianOptimization#22]
Hi!
I have some real value inputs (in numpy array) and also the corresponding observation from a black box function (also in numpy). How can construct in appropriate form in BayesianOptimization? In tutorial notebook there is an analytical function which I think is for illustration goal.

Thanks for help!

**Comment by fmfn** [comment]
Are you able to pass inputs to your blackbox function and get one output back? All you need to make this work is to be able to define a function with named inputs:

    f = lambda x, y: any_function_that_returns_a_real_number(x, y)
    bo = BayesianOptimization(f, {'x': (-1, 1), 'y': (-1, 2)})
    bo.maximize()

Don't mind the analytical-ness of the example function, as far as the algorithm is concerned, that function is blackbox.
