### ISSUE TITLE
working with Big Data

### ISSUE THREAD

**Issue by sbhadade** [fmfn/BayesianOptimization#222]
we are using Bayesian optimisation with big data params tuning . the bayesian parameters running function breaks if data is more than 100 kb. can you guide which libraries can accelerate the training and bayesian optimisation function to run on big data like 100mb - 1 gb of data .

![Screenshot 2020-04-25 at 18 11 12](https://user-images.githubusercontent.com/50355387/80280193-408e6b00-8720-11ea-8a73-987502dfec6e.png)

**Comment by fmfn** [comment]
This is not a memory problem, your data has missing values (read the trace).

**Comment by sbhadade** [comment]
hi fmfn how to speed the running function fast or bayesian_opt fast to process big data ?
