### ISSUE TITLE
Iteration time increases

### ISSUE THREAD

**Issue by jjstarn-usgs** [fmfn/BayesianOptimization#223]
I'm simulating a 4-parameter model and using 256 initial probings and 1,000 iterations after that.  It's a very nonlinear problem.  The first iteration executes in about 2 secs.  the progress slows as the number of iterations increases, up to about 60 seconds per iteration.  The underlying model does not increase execution time.  Is there something in the code that increases the iteration time?  Is it the complexity of the objective function surface?  Is there something that can be set to reduce  the time?  I'm using the UCB acquisition function.

**Comment by fmfn** [comment]
> Is there something in the code that increases the iteration time?

Yes. This method fits a gaussian process (GP(params) -> objective) to estimate the objective function surface. GPs are cubic in the number of data points.

> Is there something that can be set to reduce the time?

You can play around with [GP params](https://scikit-learn.org/stable/modules/generated/sklearn.gaussian_process.GaussianProcessRegressor.html) using `set_gp_params`. It's [default values](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L79) could be made a bit less computationally intensive.

**Comment by jjstarn-usgs** [comment]
Thank you for your response!  Any suggestions as to what GP params could be modified?  I assume the delay is due to inverting a large matrix.  Are there quicker methods?

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________

**Comment by fmfn** [comment]
`n_restarts_optimizer` is the main one (change it to 1).

> Are there quicker methods?

There are, take a look at sklearn's parameter optimization module.

**Comment by jjstarn-usgs** [comment]
Thanks again.  You're code is generally working very well for me.

Jon Jeffrey Starn Ph.D.
Research hydrologist
USGS New England Water Science Center
101 Pitkin Street
East Hartford, CT 06108
________________________________
