### ISSUE TITLE
Hyperparameter optimization

### ISSUE THREAD

**Issue by 1Reinier** [fmfn/BayesianOptimization#23]
Hi,

Just a quick question: I couldn't immediately spot in the code whether the gaussian process in this library optimizes its own hyperparameters. Do I have to pass in the length scale that suits my problem as an argument or will it do bayesian hyperparameter optimization here too?

Thanks!

-Reinier

**Comment by fmfn** [comment]
GP's covariance is definitely optimized, see [internal GP definition](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L157), however its hyper-parameters are not.

And yes, you should perform appropriate transformations to your parameters before optimizing as this implementation will not try to figure it out for you.
