### ISSUE TITLE
Limit how close parameters are sampled from a previous one

### ISSUE THREAD

**Issue by deeplearningrobotics** [fmfn/BayesianOptimization#235]
I am optimizing some parameters for a robotics system. From the system design I know that picking parameters which are very close together does not make a relevant difference in system behavior.

When running Bayesian optimization I see though that parameters are picked which are very very close together.

Is there an option to either specify to resample if a parameter is too close or to otherwise change the probability distribution to space out samples more?

**Comment by ben-arnao** [comment]
That's the purpose of the` kappa` argument

```
optimizer.maximize(
    init_points=2,
    n_iter=3,
    kappa=2.576,
)
```

Higher value = favors spaces that are least explored.
Lower value = favors spaces where the regression function is the highest.

**Comment by bwheelz36** [comment]
The other factor may be the length scales, which tell the optimiser how correlated you expect points of a certain distance
