### ISSUE TITLE
Can the black box function have strong noises and discrete inputs at the same time?

### ISSUE THREAD

**Issue by RangerChu** [fmfn/BayesianOptimization#236]
Hi,

Can the black box function have strong noises and discrete inputs at the same time? It means that the same input gets different outputs. 

![image](https://user-images.githubusercontent.com/16542762/84613997-5be34e80-aef7-11ea-96c3-f6423017f6b4.png)

![image](https://user-images.githubusercontent.com/16542762/84614104-a8c72500-aef7-11ea-9094-cb5e3fd4084f.png)

![image](https://user-images.githubusercontent.com/16542762/84614118-b2e92380-aef7-11ea-9575-431565891df0.png)

I want to optimize a discrete variable with Bayes, and the function value corresponding to each variable value has strong randomness.But when I tried to call optimizer.probe with the same input repeatedly, it seemed to detect the same variable value only once.

**Comment by RangerChu** [comment]
Thanks in advice!

**Comment by RangerChu** [comment]
![image](https://user-images.githubusercontent.com/16542762/84616084-715b7700-aefd-11ea-83df-ac1646b9ab5f.png)
If I change this function and return different value of y for the same x, will the algorithm still work?

**Comment by RangerChu** [comment]
In order to deal with the above problems, I wrote such a program. And I'm not sure if this program is appropriate, but the program seems stuck at one point.
```

from bayes_opt import BayesianOptimization
from bayes_opt.logger import JSONLogger
from bayes_opt.event import Events
from bayes_opt.util import load_logs
import random


def func_with_discrete_params(x):
    # Simulate necessity of having d being discrete.
    assert type(x) == int
    return 1 - x ** 2 + random.uniform(1,2)

def black_box_function(x):
    x = int(x)
    return func_with_discrete_params(x)

if __name__ == '__main__':
    pbounds = {'x': (0, 10)}
    optimizer = BayesianOptimization(
        f=black_box_function,
        pbounds=pbounds,
        verbose=2,  # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
        random_state=1,
    )
    optimizer.maximize(
        init_points=2,
        n_iter=1000,
        alpha=1e-3,
    )

```
![image](https://user-images.githubusercontent.com/16542762/84785813-854aca00-b01e-11ea-9302-232dc076391b.png)

**Comment by jiwoongim** [comment]
Could you share the results? What is the conclusion here? :)

**Comment by RangerChu** [comment]
Which result do you mean? I have two main questions.
1. Does the Bayesian optimization limit one input corresponding to one output in the black box function? Can one input correspond to multiple outputs? 
2. Is the program for the discrete inputs and strong noises reasonable? Is the value of alpha appropriate? And is there a better solution for the discrete inputs and strong noises?

**Comment by sharpe5** [comment]
If the function returns different results each time, here is a possible solution:
* Run the internal function N times.
* Return mean - (3x standard deviation) of results.

This smooths out the results so the gradient can be followed more easily, and also penalises inputs which result in a high variance on the output.
