### ISSUE TITLE
Passing Integer Params

### ISSUE THREAD

**Issue by hcohenHEP** [fmfn/BayesianOptimization#24]
Hi,

Great package, just one thing that bother me is the option for integer input optimization. For my function i've got about 4 integers and 1 float, currently i'm doing param1=int(param1) in my function to overcome this, but, i'm wasting steps since it tries various times with 4.2, 4.1, 4.24 which are all actually 4 in my code.

Is there a way around it?

Thank you

**Comment by fmfn** [comment]
This issue has been brought up a few times and to my knowledge there is no simple, standard way to do it. 

Your solution is a simple one that works for many cases. However, if you're finding that it is not serving  your needs, I'm afraid you will have to come up with something else, or perhaps look in the literature for what other may have done.

ps: I do find that adding a bit of noise to the GP (`alpha` parameter in sklearn 1.18) helps when dealing with discrete variables, the added flexibility compensates for the ill-defined continuous variable.
