### ISSUE TITLE
Outdated Anaconda package

### ISSUE THREAD

**Issue by bacalfa** [fmfn/BayesianOptimization#241]
The latest version is 1.2.0, but in Anaconda it's 1.1.0: https://anaconda.org/conda-forge/bayesian-optimization.

**Comment by volpatto** [comment]
Sorry, the package is now up-to-date. Updated [here](https://github.com/conda-forge/bayesian-optimization-feedstock/pull/3). Please let me know if you still can not install the most recent version.

**Comment by till-m** [comment]
@volpatto it seems that while the merge went through, conda-forge is still not updated. See [here](https://anaconda.org/conda-forge/bayesian-optimization), where it is still listed as 1.1.0 -- any idea why this could be the case?

**Comment by volpatto** [comment]
Thanks for pointing this out, @till-m. Somehow the feedstock was not rendered, maybe I have missed something while enabling the automerging there. I'll have a look.

**Comment by volpatto** [comment]
@till-m I hope it is fixed now. Please let me know if it is not working properly.

**Comment by till-m** [comment]
Seems to work! Thanks for taking care of this, @volpatto.

@bwheelz36 I think this can be closed now :)

**Comment by bwheelz36** [comment]
Cool :-)
