### ISSUE TITLE
sklearn decorator

### ISSUE THREAD

**Issue by VincentGatien** [fmfn/BayesianOptimization#242]
Hi,

I would like to contribute to the project.

I have a script that combines some features from the BayesianOptimization package
to optimize hyperparameters of a model with a sklearn interface.

Here is joined the python script with examples of how it would be used.

Link to the gist -> [bo_decorator.py](https://gist.github.com/VincentGatien/882b3bbd81ff98b426ac418c45cfc1bd)

Let me know what you think about it!

**Comment by patrikcarreira** [comment]
Hi, 

I've tried your snippet of code and it works like a charm. 

Thanks!

**Comment by alanAguiar** [comment]
Hi,

Similarly to @VincentGatien , I also wrote a piece of code to facilitate the usage of this lib by someone used to the sklearn API.

In my case, I wrote a class that inherits from sklearn's [BaseSearchCV](https://github.com/scikit-learn/scikit-learn/blob/fd237278e895b42abe8d8d09105cbb82dc2cbba7/sklearn/model_selection/_search.py#L400), making the usage very similar to other search methods such as GridSearchCV or RandomSearchCV.

Link to the gist: [bo_searchCV](https://gist.github.com/alanAguiar/64ff3004a45ca1e35e003c511ee117cb)

I was going to open a new issue proposing this contribution, but I felt like the topics were close enough to keep the discussion right here.

**Comment by fmfn** [comment]
Thank you both @VincentGatien and @alanAguiar for the suggestions. You are more than welcome to open a PR with these nice features. I think we could offer such extended functionality as part of the `util` module, or potentially a `sklearn_helper` module or something.
