### ISSUE TITLE
Suggesting already evaluated values

### ISSUE THREAD

**Issue by jackureu** [fmfn/BayesianOptimization#244]
I'm using BayesianOptimization optimize my function `func`

The challenge I have is that I already evaluated this function in many input X values and have their corresponding Y values.
I want to somehow "input" that into the module and allow it to use this information, so it can achieve a better result more quickly.

**Comment by haw230** [comment]
I'm not 100% sure if this library supports it but as a work around you can wrap another function, let's say `func2` around it.

```python
def func2(**params):
  for evaluation in already_evaluated:
    if params == evaluation["params"]:
      return evaluation["f(x)"]
  return func(**params)
```

**Comment by haw230** [comment]
Actually you can use `space.add_observation`. This is in `target_space.py`.

**Comment by bwheelz36** [comment]
check out the advanced tour notebook, this can be achieved through the optimiser.register function
