### ISSUE TITLE
Support for passing in extra arguments to a function

### ISSUE THREAD

**Issue by hgandhi2411** [fmfn/BayesianOptimization#249]
Hi, is there a way to pass in fixed extra arguments to the black box function?
These arguments may be crucial to the calculation happening in the function but should not be changed/optimized during the optimization process. For example:
``` python
def black_box_function(x, y, a, b, c):
    # only x and y are tunable and a, b, c are constants given by the user which should not be tuned
    return (x+a)*(y/b)**c
```

If there is a way to deal with this, please kindly direct me to an example.

**Comment by ben-arnao** [comment]
As fmfn mentioned before, 've used partial functions and it's worked well for me.

**Comment by hgandhi2411** [comment]
Thanks @ben-arnao for the suggestion. I didn't want to use partial functions, so I tried using a lambda function with the optimizer and that also worked well. An example:
``` python
optimizer = BayesianOptimization(f = lambda x, y: black_box_function(x, y, a = 2, b =3, c=4), pbounds = {'x': (0., 1.), 'y': (2., 4.)})
optimizer.maximize(n_iter = 5, init_points = 3)
```
