### ISSUE TITLE
multi-input and multi-output

### ISSUE THREAD

**Issue by plzhai** [fmfn/BayesianOptimization#252]
My black-box-function is like, 

[out1, out2] = f(in1,in2,in3), but in2 and in3 are not the hyperparameters i want to search.

How should i handle this kind of problem?

**Comment by osullivryan** [comment]
For the additional parameters you could do something like this:

```python
optimizer = BayesianOptimization(
    f=lambda in1: f(in1, in2=SOMETHING, in3=SOMETHING_ELSE),
    pbounds=pbounds,
    random_state=1,
)
```

Or if you don't want `lambdas` then:

```python
def f(in1, in2, in3) -> float:
    ...

def function_to_optimize(in1) -> float:
    in2 = SOMETHING
    in3 = SOMETHING_ELSE
    return f(in1, in2, in3)

optimizer = BayesianOptimization(
    f=function_to_optimize,
    pbounds=pbounds,
    random_state=1,
)
```

Multi-objectives are a different story. Can you use a weighted-sum to turn it in to a single objective? For example:

```python
def f(in1, in2, in3) -> float:
    weight1 = 10
    weight2 = 1
    out1 = in1 + in2
    out2 = in2 * in3
   return weight1 * out1 + weight2 * out2
```
The weights could both be the same, based on intuition, or a function of the order of magnitude of each `out`.

**Comment by fmfn** [comment]
Thank you for the answer @osullivryan , that's precisely correct. Multi-output is not supported and I don't have plans to do so either, so a weighted sum, or some other strategy, is the way to go.
