### ISSUE TITLE
Verbose output is displayed faulty

### ISSUE THREAD

**Issue by julian-belina** [fmfn/BayesianOptimization#257]
I was trying to use the example Code as follows:

def black_box_function(x, y):
    """Function with unknown internals we wish to maximize.

    This is just serving as an example, for all intents and
    purposes think of the internals of this function, i.e.: the process
    which generates its output values, as unknown.
    """
    return -(x ** 2) - (y - 1) ** 2 + 1

from bayes_opt import BayesianOptimization

"Bounded region of parameter space"
pbounds = {"x": (2, 4), "y": (-3, 3)}

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    random_state=1,
)

optimizer.maximize(init_points=2, n_iter=3)

But the output looks like this:
|   iter    |  target   |     x     |     y     |
-------------------------------------------------
| ?[0m 1       ?[0m | ?[0m-7.135   ?[0m | ?[0m 2.834   ?[0m | ?[0m 1.322   ?[0m |
| ?[0m 2       ?[0m | ?[0m-7.78    ?[0m | ?[0m 2.0     ?[0m | ?[0m-1.186   ?[0m |
| ?[95m 3       ?[0m | ?[95m-7.11    ?[0m | ?[95m 2.218   ?[0m | ?[95m-0.7867  ?[0m |
| ?[0m 4       ?[0m | ?[0m-12.4    ?[0m | ?[0m 3.66    ?[0m | ?[0m 0.9608  ?[0m |
| ?[95m 5       ?[0m | ?[95m-6.999   ?[0m | ?[95m 2.23    ?[0m | ?[95m-0.7392  ?[0m |
=================================================

I have installed Version 1.1.0 via PIP on a Windows 10 machine using 
Python 3.7.8
numpy  1.18.5
scikit-learn 0.23.2
scipy 1.5.2

**Comment by pjnr1** [comment]
Looks like some ascii color encoding not being displayed correctly. What are you using to run the program, e.g. terminal, iTerm, pyCharm, etc.?

**Comment by windowshopr** [comment]
Am having this issue myself. Running it in Windows PowerShell window (Python 3.11) gives this output with verbose 1 and 2.

![image](https://user-images.githubusercontent.com/40477419/202875002-18b903c7-881d-47e2-a2ab-71f1a77200b4.png)

If the code is run within Visual Studio Code's terminal, it displays fine.

![image](https://user-images.githubusercontent.com/40477419/202875007-c71217b3-bd36-4893-9786-71864b79e41f.png)
