### ISSUE TITLE
ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s)

### ISSUE THREAD

**Issue by CandiceWu123** [fmfn/BayesianOptimization#259]
--> 167         self._target = np.concatenate([self._target, [target]])

Tracing back to the line above,I have no clue what caused this error, it's so confusing!

**Comment by sen0zk** [comment]
me too... in my case this problem shows up when I modified my black box function from one single output, my objective value, to multiple output. So my view is that by strictly following the format in the documentation should get it working

**Comment by CandiceWu123** [comment]
Yeah, I found just the same reason a few days ago.I was working on neural network and I returned multiple validation loss instead of one.Turned out&nbsp; this was the cause, thank you for sharing with me!&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "fmfn/BayesianOptimization"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年10月12日(星期一) 下午2:33
收件人:&nbsp;"fmfn/BayesianOptimization"<BayesianOptimization@noreply.github.com&gt;;
抄送:&nbsp;"Coco^_^"<2298813504@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [fmfn/BayesianOptimization] ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 1 dimension(s) and the array at index 1 has 2 dimension(s) (#259)





 
me too... in my case this problem shows up when I modified my black box function from one single output, my objective value, to multiple output. So my view is that by strictly following the format in the documentation should get it working
