### ISSUE TITLE
What is the kernel function in the example？Can I use other functions？

### ISSUE THREAD

**Issue by Lorisyy** [fmfn/BayesianOptimization#261]
Did you guys applied * Radial Basis Function * as default kernel function ?
This seems like no specifications for the kernel function in the docs.

RBF: [https://en.wikipedia.org/wiki/Radial_basis_function_kernel](url)

**Comment by fmfn** [comment]
Default kernel is [Matern 2.5](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L116) as suggested by the literature. You are free to change it by invoking the `set_gp_params` method which calls `set_params` from sklearn's GP.
