### ISSUE TITLE
Accessing optimization iteration number from black_box_function

### ISSUE THREAD

**Issue by raphslalom** [fmfn/BayesianOptimization#262]
Hello,

Is it possible to access the optimization iteration id from within the `black_box_function`?
What I call the "optimization iteration id " is the integer in the column `iter` printed by `optimizer.maximize()`

```

|   iter    |  target   |     x     |     y     |
-------------------------------------------------
|  1        | -7.135    |  2.834    |  1.322    |
|  2        | -7.78     |  2.0      | -1.186    |
|  3        | -19.0     |  4.0      |  3.0      |
|  4        | -16.3     |  2.378    | -2.413    |
|  5        | -4.441    |  2.105    | -0.005822 |
=================================================
```

Ex:
```python
def black_box_function(x, y):
    iteration_id = some_bayes_opt_voodoo_giving_the_iteration_id()
    print(iteration_id)
    return -x ** 2 - (y - 1) ** 2 + 1
```

To give some context: my `black_box_function` writes to disk, I would like to include `iteration_id ` in the path to ensure the bb function writes to a different location for each optimization iteration.

Thanks!

**Comment by raphslalom** [comment]
I am going to go with a quick and dirty usage of environment variables:

```python
def black_box_function(x, y):
    try:
        print('Current iteration=' + os.environ["BO_IT"])
        os.environ["BO_IT"] = str(int(os.environ["BO_IT"]) + 1)
    except:
        pass
    return -x ** 2 - (y - 1) ** 2 + 1
```

Then:

```python
os.environ["BO_IT"] = "1"

# Optimize
optimizer.maximize(
    init_points=1,
    n_iter=18,
)
```

But I am guessing Observers / Callbacks could be the way to this properly?

**Comment by fmfn** [comment]
> But I am guessing Observers / Callbacks could be the way to this properly?

Exactly. This extra functionality, while totally justified, is best left for the user as to maintain the library as lean as possible.
