### ISSUE TITLE
How to search for a large number of hyperparameters?

### ISSUE THREAD

**Issue by AlfheimLe** [fmfn/BayesianOptimization#264]
Dear author

I want to use this method to search for 50 hyperparameters. My question is how to define the black function and the pounds if I need to search a large number of hyperparameters? Or I need to write a black function with 50 parameters and give the bound of each hyperparameter such as black_box(x1,x2,x3,.....).  

Best

**Comment by fmfn** [comment]
You need to write a function with 50 parameters and pass the corresponding bounds.
