### ISSUE TITLE
How to introduce relationship constraints between two parameters?

### ISSUE THREAD

**Issue by hammer-wang** [fmfn/BayesianOptimization#266]
I have two parameters x1 and x2 to optimize. They need to satisfy a condition that x1 must be greater than x2. I'm wondering how to incorporate this relationship constraint using this package? Thanks a lot!

**Comment by jdmoore7** [comment]
I was wondering about this, too. Not a developer on this repo, but my best guess would be to incorporate these constraints into the black box function. For example, if x cannot be greater than y, then if this condition is not met return an arbitrarily penalty. For example:
```python
def f(x,y):
    if x > y:
       return -1 * np.inf
    else:
       <insert action>
```
