### ISSUE TITLE
Is there a way to make the black_box_function receive an array as a parameter?

### ISSUE THREAD

**Issue by LuisFJS04** [fmfn/BayesianOptimization#268]
I would like to work with arbitraries numbers of parameters for a function rather than having to call them by name. For example, if I have a black_box_function() that takes, let's say 20 parameters, is there a way of calling it:

black_box_function(x)

where len(x)=20 and then len(pbounds)=20, or something similar?

**Comment by KhanhThiVo** [comment]
Hi, I have the similar question. Could you share how you solved it?

**Comment by LuisFJS04** [comment]
Hi Thi Vo,

This was a while ago so I don't remember all the specific details right now, but In the end what I did was write a wrapper function wrapper_for_bayesian_optimization(**x), if I recall correctly. 

I hope this idea sends you in the right direction (it worked for me, at least). If it doesn't let me know and I'll try to remember exactly what I did, but I can't make any promises.

**Comment by KhanhThiVo** [comment]
Hi Luis,

thank you so much for your help. It also worked for me.
