### ISSUE TITLE
Too many indices for array

### ISSUE THREAD

**Issue by vkuznet** [fmfn/BayesianOptimization#27]
Hi,
I"m not sure if it is this package or sklearn problem, but I'm getting this type of error when I use BayesianOptimization with XGBRegressor:

```
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.py:427: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'warnflag': 2, 'task': 'ABNORMAL_TERMINATION_IN_LNSRCH', 'grad': array([-0.00010668]), 'nit': 3, 'funcalls': 48}
  " state: %s" % convergence_dict)
/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/sklearn/gaussian_process/gpr.py:427: UserWarning: fmin_l_bfgs_b terminated abnormally with the  state: {'warnflag': 2, 'task': 'ABNORMAL_TERMINATION_IN_LNSRCH', 'grad': array([ -4.25553349e-05]), 'nit': 5, 'funcalls': 52}
  " state: %s" % convergence_dict)
Traceback (most recent call last):
  File "./bopt.py", line 119, in <module>
    mbo.maximize()
  File "build/bdist.macosx-10.10-x86_64/egg/bayes_opt/bayesian_optimization.py", line 245, in maximize
  File "build/bdist.macosx-10.10-x86_64/egg/bayes_opt/helpers.py", line 35, in acq_max
```

I'm not sure which part should be fixed, but I'll be interested to know your feedback.
Thanks,
Valentin.

**Comment by fmfn** [comment]
I need more details, can you share the script? Or at least the data format and your definition and call to BO?

**Comment by vkuznet** [comment]
Here is a script:
https://gist.github.com/vkuznet/10b9ac81da353256d701f4c9651f3a5e

**Comment by ternaus** [comment]
Not directly related, but I can add script that performs optimization for xgboost if there is interest:

https://github.com/ternaus/kaggle_allstate/blob/7642e58c895782eb70f73c2d19e17f7c182e4752/src/xgb_baysian.py

**Comment by fmfn** [comment]
@vkuznet Ok, I see what's happening. The parameter dict takes the parameter name as key, and a tuple with lower and upper bounds of search as value.

So you should instead define them as follows: `eta = (0.01, 0.02)`, and so on. The gaussian process is in charge of deciding where to look within these bounds.

Notice that if your are dealing with scale parameters you should optimize for their log, instead of actual value. Something like `log_eta = (-2, 1)`, and inside the function you have something like `...eta=10**log_eta`.

**Comment by mpearmain** [comment]
Checkout bayesboost 
Also referenced from xgb

**Comment by ternaus** [comment]
bayesboost looks outdated. Basically, in the provided examples there is no easy way to add early_stopping in a way that it would be consistent among different folds. Although these examples can be easily extended to include  xgboost.cv method that allows it.

**Comment by mpearmain** [comment]
This is nicer, using the native xgb version over sklearn version as you can change optimiser as well.

**Comment by vkuznet** [comment]
@fmfn , thanks for pointing to the root of the problem. I think issue can be closed but other comments are also useful. I'll be interested to see native xgb support as well.
