### ISSUE TITLE
What is the default prior when using a specified function space?

### ISSUE THREAD

**Issue by KaleabTessera** [fmfn/BayesianOptimization#273]
I am using BayesOpt to optimize params of a function. I have 10 varibles with bounds `(0,1)`.  What is the proir set on this function space by BayesOpt? I can't set to find the defaults anywhere. I believe you can use probe to set a prior, but what is the default for the search space above? Is it the max/min of the space?

**Comment by bwheelz36** [comment]
- the prior in general is a gaussian process model
- before seeing any data, I think this model has something like a mean of 0 and a variance of 1 (you can check but it's something like that). 
- in terms of assumptions of the prior: basically the assumption is that points close enough together have similar values and the OF will vary smoothly between them. What is 'close enough' is defined by the length scales.
