### ISSUE TITLE
How to define the parameter "pbounds" if no bounds

### ISSUE THREAD

**Issue by ZYblend** [fmfn/BayesianOptimization#274]
I don't have bounds for the inputs of a function, how can i define "pbounds" . And also my inputs will be in a large dimension, how can define "pbound"? i cannot just define one by one.

**Comment by bwheelz36** [comment]
(sorry for the slow reply, going through and closing issues and thought I should add an answer for posterity)

1. Use large values. you could even try np.inf, but realistically there will be some bounds on the variables. Solving the problem over a huge domain makes your life much harder than it needs to be.
2. If you really have that many inputs, this may not be the right code - this style of optimization is appropriate for up to ~20 variables or so.
