### ISSUE TITLE
Parameter Bounds Constraint Support

### ISSUE THREAD

**Issue by Duppils** [fmfn/BayesianOptimization#276]
Hi, I found this tool very useful for my weight optimization scheme. It was very easy to setup usage of the tool, but there was one feature that was missing for me. I would like to not just set the parameter bounds, but additional constraints, such as the following:

Any given weight (parameter) should not be larger than 90% or smaller than 10% of the total weight (parameter sum).

I believe adding constraint support for parameter bounds could be beneficial to the tool overall, as it allows the developer to constrain the optimizer in a way that invalidates parameter configs that don't make sense in the context of the function.

Have a nice day!

Edit: there are some workarounds for this like returning 0 from the function if the parameters fail any given constraint, which is how I will solve it for now. I just thought I'd post the idea here as well.

**Comment by ystow1** [comment]
Would also be interested in this - #95 looks into this using an older version of the tool which I haven't been able to get up and running. 

@Duppils please can you show me your workaround.
