### ISSUE TITLE
JSONLogger logs wrong optimization iterations for existing data points

### ISSUE THREAD

**Issue by kylelyk** [fmfn/BayesianOptimization#277]
Here's my current setup:
```Python
optimizer = bayes_opt.BayesianOptimization(
    f=call_input,
    pbounds=bounds,
    verbose=2,
    random_state=1
)

if not os.path.exists(OPTIMIZE_JSON):
    os.makedirs(os.path.dirname(OPTIMIZE_JSON), exist_ok=True)
    with open(OPTIMIZE_JSON, 'w'):
        pass
bayes_opt.util.load_logs(optimizer, logs=[OPTIMIZE_JSON])
logger = bayes_opt.JSONLogger(path=OPTIMIZE_JSON, reset=True)
optimizer.subscribe(bayes_opt.Events.OPTIMIZATION_STEP, logger)

optimizer.maximize(
    init_points=3,
    n_iter=15
)
```

I'm trying to set the library up so that I can resume optimizing from the OPTIMIZE_JSON file since the script tends to be pretty buggy when first developing what `call_input` does. However, what happens is that `JSONLogger.update()` uses the last element of the instance.res, which means that it will repeatedly use the last optimizing step when loading the previous optimization steps. 

So suppose that the JSON file starts with:
```
{"target": 42, "params": {"foo": 1}}
{"target": 43, "params": {"foo": 2}}
{"target": 44, "params": {"foo": 3}}
```

Running the program turns the JSON file into:
```
{"target": 44, "params": {"foo": 3}}
{"target": 44, "params": {"foo": 3}}
{"target": 44, "params": {"foo": 3}}
```
before continuing the optimization process. So the first 2 datapoints are actually lost and have to be computed the next time the script is run.

If I change `reset=False` when creating JSONLogger, it kind of works, but makes the JSON file messy:
```
{"target": 42, "params": {"foo": 1}}
{"target": 43, "params": {"foo": 2}}
{"target": 44, "params": {"foo": 3}}
{"target": 44, "params": {"foo": 3}}
{"target": 44, "params": {"foo": 3}}
{"target": 44, "params": {"foo": 3}}
```
since it's logging optimization steps that aren't really running the `call_input` function but rather just loading it from a file.

So it doesn't seem like it's possible to append new optimization steps to a JSON file (while using the existing steps to initialize the optimizer) without messing up the file a bit. Is there a better way to do this?

**Comment by bwheelz36** [comment]
Does this thread answer your question (sorry for slow reply, trying to triage all these open issues)

https://github.com/fmfn/BayesianOptimization/issues/159

If this is still a problem can you open a new issue please :-)
