### ISSUE TITLE
Is there a way to cache results?

### ISSUE THREAD

**Issue by ternaus** [fmfn/BayesianOptimization#28]
Is there a way to run optimization for N iterations, save results and next time continue from the same point?

Or maybe run optimization on different computers, combine results together and continue from this combined set of data points?

**Comment by fmfn** [comment]
With the `initialize` method you can pass points in the parameter space for which you know the function's value and optimize from there.

The only caveat is that the API of initialize is not so great (see issue #25 for reference). It is an easy fix, I just haven't got around doing it. But if you read the method implementation you should be able to extend it by manipulating the object's internal parameters directly.

**Comment by ternaus** [comment]
As I understand, calling after training `res` returns points that were used during optimization, but it does not return results that were obtained during initialization. Am I right?
