### ISSUE TITLE
Import failure on google colab

### ISSUE THREAD

**Issue by shahidzk1** [fmfn/BayesianOptimization#280]
I try to install the bayesian-optimization package on google colab with the following code
''''
%%capture
#!pip install bayesian-optimization
'''' 

then import is using
'''
from bayes_opt import BayesianOptimization
'''
it fails

**Comment by alonfnt** [comment]
```
 #!pip install bayesian-optimization
```
you have a `#` before your shell command. Removing it does install `bayesian-optimization` and the import works.

**Comment by sourabh69733** [comment]
`!pip install bayesian-optimization`

Then import 
`from bayes_opt import BayesianOptimization`


You can close it now.
