### ISSUE TITLE
What should I do when I want to find the optimal parameters of blackbox that can only get value online.

### ISSUE THREAD

**Issue by linghuix** [fmfn/BayesianOptimization#281]
What should I do when I want to find the optimal parameters of blackbox that can only get value online. For example, find the optimal walking speed to have lowest energy consumption. I am very confused about how to use this repository. I would be very appreciated if anyone can help me out.

**Comment by alonfnt** [comment]
Not sure if I understand, but if you create a function with just one input parameter and that returns the energy consumption (negative since you are going to maximize the function), something like:
```
def compute_energy_cons(walking_speed):
    # Get value from online run
    consumption = ...
    return -1 * consumption
```

and then perform minimization on that wrapper function.
```
pbounds = {'walking_speed': (1, 300)}

optimizer = BayesianOptimization(
    f=compute_energy_cons,
    pbounds=pbounds,
    random_state=42,
)

optimizer.maximize(
    init_points=2,
    n_iter=3,
)
```
