### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by celinekattenberg** [fmfn/BayesianOptimization#283]
When the range for a parameter's bounds are two equal numbers, like:

'phi1': (1, 1)

a runtime warning is thrown: 
RuntimeWarning: invalid value encountered in true_divide

**Comment by bwheelz36** [comment]
...why are you sending the code a parameter that can never change? just set it as a constant?

**Comment by ckattenberg** [comment]
I know I could set it as a constant but still, why is there a warning? I don't think there should be one.

**Comment by suanrong** [comment]
> ...why are you sending the code a parameter that can never change? just set it as a constant?

I want to get a suggestion with a fixed parameter.
