### ISSUE TITLE
can't run demo code in Advanced tour notebook 

### ISSUE THREAD

**Issue by Haiqian-MA** [fmfn/BayesianOptimization#288]
when I try to run the demo code in the Suggest-Evaluate-Register Paradigm's part of maximum loop, I get such error: ValueError: array must not contain infs or NaNs
![屏幕截图 2021-06-24 145228](https://user-images.githubusercontent.com/47879901/123216260-ec397380-d4fb-11eb-963e-0e7b5964c2d2.png)
![屏幕截图 2021-06-24 145245](https://user-images.githubusercontent.com/47879901/123216270-ed6aa080-d4fb-11eb-891f-35ddf0d985fc.png)

**Comment by Haiqian-MA** [comment]
it's very strange cause I can't use the Suggest-Evaluate-Register Paradigm

**Comment by Haiqian-MA** [comment]
ok, I find it, its because new version skearn can not run a gpregressor on 1 sample, hope u can fix it, thx
![image](https://user-images.githubusercontent.com/47879901/123219327-5acc0080-d4ff-11eb-800d-2e960e2d721a.png)

**Comment by Haiqian-MA** [comment]
update my sklearn to 0.24.2 can handle this problem

**Comment by sourabh69733** [comment]
If your issue is solved, then you can close this issue. 

else paste your notebook link or optimizer code or utility variable
