### ISSUE TITLE
RECOMMENDATION Use Github to host GIF files

### ISSUE THREAD

**Issue by zwelz3** [fmfn/BayesianOptimization#290]
The repo is 17MB on clone, and 16 of that is a single GIF. 

It would be great if the GIF was just hosted on an issue and embedded in the README. This would allow it to work the same (except for locally inspecting the README), and save a significant amount of data. 

[From this answer on SO
](https://stackoverflow.com/a/61540780/3925204)

> If you do not intend to store any images in your repository, you can always use this https://user-images.githubusercontent.com/
> 
> To host your images in user-images subdomain you can do the following
> 
> Click New Issue this will open up the issue creator.
> Drag and Drop or Upload your image in the body content
> Wait for upload completion and copy the URL for the image.
> Cancel the issue creation and continue.
> But you will not have access to these images once uploaded, you cannot delete them. You can always contact GitHub Support if required to delete.

You can actually create the issue (I call mine "IMAGES") and then you can add new images as you update the repo. I would recommend compressing the GIF a bit either way to save on load time. 

Just a friendly suggestion!

**Comment by bwheelz36** [comment]
hey, just closing this
