### ISSUE TITLE
Multi input problem

### ISSUE THREAD

**Issue by A-ep93** [fmfn/BayesianOptimization#291]
Hello,
I am dealing with a multi input problem, however the bayesianoptimization is not accurate enough.
I appreciate if someone can give me hints to increase the accuracy.
`pbounds = {'x': (xl,xh), 'y': (yl, yh),'z': (zl, zh)}`

`optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=1, 
    random_state=10,
)`

`optimizer.maximize(
    init_points=500,
    n_iter=3000,
)`
    
    
   Also, what is the meaning of random_state?

**Comment by A-ep93** [comment]
Any ideas about this?

**Comment by bwheelz36** [comment]
Hi,
You haven't given enough information for anyone to help you; what do you mean 'not accurate enough'. If you have a problem the first step is to provide sufficient information for someone to understand it, and ideally reproduce it. 

You can google 'random_state python' to figure out what that means.
