### ISSUE TITLE
Function minimize?

### ISSUE THREAD

**Issue by L-u-d-0-v-i-c** [fmfn/BayesianOptimization#296]
Hello everyone,

Is there a function that can be used to minimize metrics like RMSE or MAPE for instance?
When I use the library to optimize metrics like MAPE, I get bad results since the algorithm select parameters with the highest MAPE values.

Thanks,

Ludovic

**Comment by andregraubner** [comment]
I don't know much about this library (just checking it out for the first time), but you should always be able to just invert your values in order to turn the problem into a maximising problem! So instead of minimising RMSE, maximise -RMSE.
