### ISSUE TITLE
Different bayesian searching iteration

### ISSUE THREAD

**Issue by bloodlee** [fmfn/BayesianOptimization#301]
Hi,

I have a question about the iterations of searching.
I deployed the same implementation on different server. With the same dataset and random_state=0, I saw the iterations were different for a RandomForest model.

Any idea on it?

Thanks a lot!

Regards,
Yongqiang

**Comment by bwheelz36** [comment]
I guess you mean the parameters chosen for each iteration were different?

- does your objective function contain noise?
- I'm not sure if one should actually expect that random state is consistent across different computers or not - some quick googling suggests this is tricky to enforce? 
- did the model at least converge to a similar point? this is the main issue. For me if my optimization consistently gets to for example ~5% of the same point I am happy.
