### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by ccg-ahagen** [fmfn/BayesianOptimization#305]
When calling the maximize function everything seems to work correctly.  It prints out the optimized parameters but I am then hit with this error of handling the exception.

StopIteration                             Traceback (most recent call last)
/local_disk0/.ephemeral_nfs/envs/pythonEnv-00df00c6-2291-468c-ad4f-8ce61b2708c6/lib/python3.8/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    178             try:
--> 179                 x_probe = next(self._queue)
    180             except StopIteration:

/local_disk0/.ephemeral_nfs/envs/pythonEnv-00df00c6-2291-468c-ad4f-8ce61b2708c6/lib/python3.8/site-packages/bayes_opt/bayesian_optimization.py in __next__(self)
     24         if self.empty:
---> 25             raise StopIteration("Queue is empty, no more objects to retrieve.")
     26         obj = self._queue[0]

StopIteration: Queue is empty, no more objects to retrieve.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)

<local-file-path> in bayes_hyper_tune(self)
     76         x = self.df_data_set[self.finalized_feat_list]
     77         y = self.df_data_set[self.target]
---> 78         return bayes_parameter_optimize_lgb(x, y, init_round=15, opt_round=25, n_folds=10, random_seed=6)
     79 
     80     def generate_optimal_model_params(self):

<local-file-path> in bayes_parameter_optimize_lgb(x, y, init_round, opt_round, n_folds, random_seed)
    190     lgb_bayes_optimizer = BayesianOptimization(lgb_evaluation, config.BAYES_OPTIMIZATION_PARAMS_GRID, random_state=200)
    191 
--> 192     lgb_bayes_optimizer.maximize(init_points=init_round, n_iter=opt_round)
    193 
    194     # return best parameters

/local_disk0/.ephemeral_nfs/envs/pythonEnv-00df00c6-2291-468c-ad4f-8ce61b2708c6/lib/python3.8/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    180             except StopIteration:
    181                 util.update_params()
--> 182                 x_probe = self.suggest(util)
    183                 iteration += 1
    184 

/local_disk0/.ephemeral_nfs/envs/pythonEnv-00df00c6-2291-468c-ad4f-8ce61b2708c6/lib/python3.8/site-packages/bayes_opt/bayesian_optimization.py in suggest(self, utility_function)
    129 
    130         # Finding argmax of the acquisition function.
--> 131         suggestion = acq_max(
    132             ac=utility_function.utility,
    133             gp=self._gp,

/local_disk0/.ephemeral_nfs/envs/pythonEnv-00df00c6-2291-468c-ad4f-8ce61b2708c6/lib/python3.8/site-packages/bayes_opt/util.py in acq_max(ac, gp, y_max, bounds, random_state, n_warmup, n_iter)
     63 
     64         # Store it if better than previous minimum(maximum).
---> 65         if max_acq is None or -res.fun[0] >= max_acq:
     66             x_max = res.x
     67             max_acq = -res.fun[0]

TypeError: 'float' object is not subscriptable

**Comment by louisphilippev** [comment]
This error was addressed in a previous issue (see #300 ) and is due to the most recent version of scipy (1.8.0).
