### ISSUE TITLE
[Feature Request] Add a CITATION.cff file

### ISSUE THREAD

**Issue by scrunguss** [fmfn/BayesianOptimization#312]
A CITATION.cff file should be added to the project so that this library can be properly referenced in research.

**Comment by bwheelz36** [comment]
Although it is not in a .cff file, the readme states how to cite this work.

"
If you used this package in your research and is interested in citing it here's how you do it:

```
@Misc{,
    author = {Fernando Nogueira},
    title = {{Bayesian Optimization}: Open source constrained global optimization tool for {Python}},
    year = {2014--},
    url = " https://github.com/fmfn/BayesianOptimization"
}
```
"
