### ISSUE TITLE
ERROR: "'float' object is not subscriptable"

### ISSUE THREAD

**Issue by ClueChaser** [fmfn/BayesianOptimization#313]
Python 3.8.12.final.0
Conda 4.12.0
Code exactly the same as in the given notebook, but cannot run BayesianOptimization() due to an error "'float' object is not subscriptable".

This can be fixed with changing -res.fun[0] to -res.fun on 65 and 67 lines in ~\anaconda3\lib\site-packages\bayes_opt\util.py

**Comment by bwheelz36** [comment]
thanks! This is the same issue as #300.
there is PR that fixes this, just hasn't been incorporated into code yet 
https://github.com/fmfn/BayesianOptimization/pull/303
