### ISSUE TITLE
cannot import name 'BayesianOptimization'

### ISSUE THREAD

**Issue by wudlike** [fmfn/BayesianOptimization#314]
'BayesianOptimization' and 'UtilityFunction' cannot be imported after installed bayes_opt by
```python
pip install bayesian-optimization
```
while bayes_opt can be imported.
![image](https://user-images.githubusercontent.com/46318462/163673073-9c1c290a-4bf7-4129-8581-7db52c9f808c.png)

**Comment by alonfnt** [comment]
What version of `bayesian-optimzation` are you running? I just created a virtual environemnt and installed 1.2.0 with `pip install bayesian-optimization` and I can't reproduce this issue.
```
In [1]: from bayes_opt import BayesianOptimization, UtilityFunction

In [2]: import pkg_resources

In [3]: pkg_resources.require('bayesian-optimization')[0].version
Out[3]: '1.2.0'
```
