### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by ayushvrma** [fmfn/BayesianOptimization#315]
I'm using the code from one of the tutorial notebooks in the repo:
My target function is:
```
def target(x):
    return np.exp(-(x - 2)**2) + np.exp(-(x - 6)**2/10) + 1/ (x**2 + 1)

x = np.linspace(-2, 10, 10000).reshape(-1, 1)
y = target(x)

plt.plot(x, y);
```
and my optimiser is defined as follows:

```
optimizer = BayesianOptimization(f=target, pbounds={'x': (-2, 10)}, random_state=27)
optimizer.maximize(init_points=2, n_iter=2, kappa=5)
```

it works well when number of iterations = 0, I'm new to the codebase could someone help me solve the issue?

**Comment by bwheelz36** [comment]
Hey, please see #300 - you need to use a lower version of scipy, or else you can edit the source code as described below.
https://github.com/fmfn/BayesianOptimization/pull/303
Sorry, hopefully this will be fixed by default in the near future
