### ISSUE TITLE
Extracting analytical expressions for Gaussian processes

### ISSUE THREAD

**Issue by JinfengM** [fmfn/BayesianOptimization#316]
First, thank you for your great work, it really has helped me calibrate a complex model.
My question here  is how can I extract the analytical expressions of GP, since BO use Gaussion processes.
I mean, I want to get GP's polynomials and its coefficients explicitly,  to construct a surrogate for trying other optimization purposes.

**Comment by bwheelz36** [comment]
In terms of accessing an existing model, see #295 
In terms of getting explicit analytic representation of the gaussian process model: I have never tried to do that. 
The GPM we are using comes from [scikit learn](https://scikit-learn.org/stable/modules/gaussian_process.html), to be honest I think this is more a question for them or maybe it is already covered in their docs, I'm not sure...

**Comment by JinfengM** [comment]
@bwheelz36 Thank you for your timely reply. It really helps. I turn to scikit learn  see if it will tell me the answer
