### ISSUE TITLE
MAINT: `bayes_opt.util.acq_max` Lacking Some Forward Compatibility with Scipy L-BFGS-B Minimizer

### ISSUE THREAD

**Issue by ngupta20** [fmfn/BayesianOptimization#320]
## Description
Scipy made a change starting in version 1.7.2 that ensures the attribute `.fun` of an `OptimizeResult` object returned by `_minimize_lbfgsb` is scalarized (from a low/zero-dimensional `np.ndarray` to a `float`). The pertinent change in `scipy.optimize._differentiable_functions` can be viewed [here](https://github.com/scipy/scipy/commit/2fcb4a0632f5f45f78c7503ea9bbb592e18deebf#diff-ba80708854272881568d3fa00b923e4fca777063153255c1003f445f357c60adR135-R138).

## Reproduction
I happened upon the effects of the new scipy version when running a standard register-suggest on an updated environment.
This [notebook](https://nbviewer.org/github/ngupta20/XAI/blob/main/notebooks/BayesianOptimization.ipynb) contains the error reproduction and a view of the stack trace.

## Suggested Change
I posted a low-impact, version-gnostic, and backwards compatible PR (https://github.com/fmfn/BayesianOptimization/pull/319). Apologies in advance if this breaks a style requirement.

This PR is an explicit variant of https://github.com/fmfn/BayesianOptimization/pull/303.

## A Note
Thank you all for `BayesianOptimization`, it's a fantastic contribution!

Thanks,

Nandish Gupta
Data Science Engineer, [SolasAI](https://www.solas.ai/)
<a href="https://www.solas.ai/">
    <img src="https://user-images.githubusercontent.com/51298907/160751179-3b05cd9c-9130-4427-a023-4e2c9ce010c1.png" width="200"/>

**Comment by bwheelz36** [comment]
thanks, as noted on the pull request #319 I used #303 simply because it was submitted first.
