### ISSUE TITLE
Is there a way to get the next n best points from the acquisition function?

### ISSUE THREAD

**Issue by simonmb** [fmfn/BayesianOptimization#327]
In the case of parallel evaluation it would be interesting to get the next n best points from the acquisition function, then run them in parallel and then do it again? Is this easily doable?

**Comment by bwheelz36** [comment]
hmm good question.
Well typically we are dealing with continuous variables, so the next best point is likely to be a point almost exactly next the best point. But you could for instance discretize the space in to N regions and get the n best regions back. 
But I think the answer is, it might not be easy with the current implementation. 

I'm not sure if you've already looked at [this example](https://github.com/fmfn/BayesianOptimization/blob/master/examples/async_optimization.py). It does something a bit different but not totally unrelated, it looks like it runs three optimzers somewhat independently if I've understood correctly. But that may be an alternative: start N different optimization processes at quite different locations, and update them all with available information from the other optimizers.

I'm curious to see if anyone can provide a better answer.
