### ISSUE TITLE
Making the algorithm faster?

### ISSUE THREAD

**Issue by sguysc** [fmfn/BayesianOptimization#329]
The package works great, I'm using it with the utility-suggest paradigm to suggest a new point, and call my function to get the target value.
Is there a way to make this faster?  E.g., in acq_max, why is n_warmup so large (=10000)?
Looking for tips to accelerate the functions.

**Comment by bwheelz36** [comment]
This package is normally used with expensive objective functions, so the internal run time of this code is rarely the main bottle neck in overall run times. E.g. for me each time I sample my objective function it takes 10 minutes. If your objective function is so cheap (fast) to sample, then this may not be the fastest package.

Having said that, you could profile the code and check if there are any obvious bottle necks.

**Comment by sguysc** [comment]
Oh yes, I see your point. I just checked it on a simple proxy objective I have, though I am planning to eventually use a more elaborate objective.
Thanks!
