### ISSUE TITLE
Can't run the main example: ValueError: Invalid parameter corr for estimator GaussianProcessRegressor. Check the list of available parameters with `estimator.get_params().keys()`.

### ISSUE THREAD

**Issue by amelio-vazquez-reina** [fmfn/BayesianOptimization#33]
I just tried the example in this notebook in Python 3.5:
``` python
from bayes_opt import BayesianOptimization

def target(x):
    return np.exp(-(x - 2)**2) + np.exp(-(x - 6)**2/10) + 1/ (x**2 + 1)

x = np.linspace(-2, 10, 1000)
y = target(x)

plt.plot(x, y)

bo = BayesianOptimization(target, {'x': (-2, 10)})

gp_params = {'corr': 'cubic'}
bo.maximize(init_points=2, n_iter=0, acq='ucb', kappa=5, **gp_params)
```

but the last step fails with:
```
ValueError: Invalid parameter corr for estimator GaussianProcessRegressor. 
Check the list of available parameters with `estimator.get_params().keys()`.
```

**Comment by amelio-vazquez-reina** [comment]
This was all from `master` (i.e. I just run `pip install git+https://github.com/fmfn/BayesianOptimization.git`). On OS X 64.

**Comment by fmfn** [comment]
Oh, crap, yes, I updated sklearn's version and forgot to change the examples. The optimizer works fine, if you comment `gp_params = {'corr': 'cubic'}` out it should run.

Sorry about that, will sort it out soon.

**Comment by xuyiqiang-learn** [comment]
I have the same problem?!

**Comment by xuyiqiang-learn** [comment]
I have the same problem, how can  I fix it?

**Comment by xuyiqiang-learn** [comment]
I have the same problem, how can I fix it?

**Comment by fmfn** [comment]
As I said, change `bo.maximize(init_points=2, n_iter=0, acq='ucb', kappa=5, **gp_params)` to `bo.maximize(init_points=2, n_iter=0, acq='ucb', kappa=5)`, and it should work. I change the notebook now.

**Comment by chandanusair87** [comment]
Hi there, may I please know how you plotted the whole acquisition function at different iterations, I am only able to plot the objective functions as I get acq_max values from .points_to_csv() method? Thanks and appreciate your response.
