### ISSUE TITLE
'float' object is not subscriptable

### ISSUE THREAD

**Issue by djj067** [fmfn/BayesianOptimization#333]
'float' object is not subscriptable also pop up when i reach the 5th iteration of bayesian optimization.

def modify_model(lr,dropout):

    model = Sequential()
    model.add(Conv2D(4,3,padding="same", activation="relu", input_shape=(108,107,3)))
    model.add(MaxPooling2D())

    model.add(Conv2D(8, 3, padding="same", activation="relu"))
    model.add(MaxPooling2D())

    model.add(Flatten())
    model.add(Dense(64,activation="relu"))
    model.add(Dropout(dropout))
    model.add(Dense(2, activation="softmax"))

    model.compile(
        optimizer=Adam(learning_rate=lr),
        loss="categorical_crossentropy",
        metrics=["accuracy"],
    )
    model.fit(x=np.array(X_train),y=np.array(y_train),batch_size=16,epochs=6,validation_data=(np.array(X_test),np.array(y_test)))
    result=model.evaluate(np.array(X_test),np.array(y_test),batch_size=16)
    return result[1]

from bayes_opt import BayesianOptimization
pbounds = {
    'lr':(0.0007,0.0013),
    'dropout':(0.3,0.8)
  

}
optimizer = BayesianOptimization(
    f=modify_model,
    pbounds=pbounds,
    verbose =2,
    random_state=1,

)
optimizer.maximize(init_points=5,n_iter=10,)
print(optimizer.max)

Output exceeds the [size limit](command:workbench.action.openSettings?[%22notebook.output.textLineLimit%22]). Open the full output data[ in a text editor](command:workbench.action.openLargeOutput?5eaa21d6-c560-4702-9850-04b8ba9c4ce7)
|   iter    |  target   |  dropout  |    lr     |
-------------------------------------------------
Epoch 1/6
6/6 [==============================] - 1s 108ms/step - loss: 46.9435 - accuracy: 0.5581 - val_loss: 20.3844 - val_accuracy: 0.4828
Epoch 2/6
6/6 [==============================] - 0s 39ms/step - loss: 36.0230 - accuracy: 0.4767 - val_loss: 11.9461 - val_accuracy: 0.5172
Epoch 3/6
6/6 [==============================] - 0s 39ms/step - loss: 8.7953 - accuracy: 0.5116 - val_loss: 1.3492 - val_accuracy: 0.5517
Epoch 4/6
6/6 [==============================] - 0s 39ms/step - loss: 1.5003 - accuracy: 0.5814 - val_loss: 1.2717 - val_accuracy: 0.5172
Epoch 5/6
6/6 [==============================] - 0s 40ms/step - loss: 0.6019 - accuracy: 0.6860 - val_loss: 1.1761 - val_accuracy: 0.5172
Epoch 6/6
6/6 [==============================] - 0s 40ms/step - loss: 0.6208 - accuracy: 0.6279 - val_loss: 0.8973 - val_accuracy: 0.5862
2/2 [==============================] - 0s 20ms/step - loss: 0.8973 - accuracy: 0.5862
|  1        |  0.5862   |  0.5085   |  0.001132 |
Epoch 1/6
6/6 [==============================] - 1s 81ms/step - loss: 83.4050 - accuracy: 0.5814 - val_loss: 34.4569 - val_accuracy: 0.5172
Epoch 2/6
6/6 [==============================] - 0s 39ms/step - loss: 14.6938 - accuracy: 0.6047 - val_loss: 8.1343 - val_accuracy: 0.4828
Epoch 3/6
6/6 [==============================] - 0s 39ms/step - loss: 5.1442 - accuracy: 0.5000 - val_loss: 1.0616 - val_accuracy: 0.5517
Epoch 4/6
6/6 [==============================] - 0s 39ms/step - loss: 0.7693 - accuracy: 0.6860 - val_loss: 0.8589 - val_accuracy: 0.6207
Epoch 5/6
...
Epoch 6/6
6/6 [==============================] - 0s 39ms/step - loss: 0.3828 - accuracy: 0.8023 - val_loss: 0.6525 - val_accuracy: 0.7586
2/2 [==============================] - 0s 17ms/step - loss: 0.6525 - accuracy: 0.7586
|  5        |  0.7586   |  0.4984   |  0.001023 |
Output exceeds the [size limit](command:workbench.action.openSettings?[). Open the full output data [in a text editor](command:workbench.action.openLargeOutput?c636fb1c-dd43-4ad1-b1ba-c4db2fd75a78)
---------------------------------------------------------------------------
StopIteration                             Traceback (most recent call last)
File c:\Users\jdong2\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py:179, in BayesianOptimization.maximize(self, init_points, n_iter, acq, kappa, kappa_decay, kappa_decay_delay, xi, **gp_params)
    178 try:
--> 179     x_probe = next(self._queue)
    180 except StopIteration:

File c:\Users\jdong2\AppData\Local\Programs\Python\Python310\lib\site-packages\bayes_opt\bayesian_optimization.py:25, in Queue.__next__(self)
     24 if self.empty:
---> 25     raise StopIteration("Queue is empty, no more objects to retrieve.")
     26 obj = self._queue[0]

StopIteration: Queue is empty, no more objects to retrieve.

During handling of the above exception, another exception occurred:

TypeError                                 Traceback (most recent call last)
c:\Users\jdong2\OneDrive - Exyte\Desktop\Untitled-1.ipynb Cell 45' in <cell line: 15>()
      [2](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=1) pbounds = {
      [3](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=2)     'lr':(0.0007,0.0013),
      [4](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=3)     'dropout':(0.3,0.8)
      [5](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=4)   
      [6](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=5) 
      [7](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=6) }
      [8](vscode-notebook-cell:/c%3A/Users/jdong2/OneDrive%20-%20Exyte/Desktop/Untitled-1.ipynb#ch0000051?line=7) optimizer = BayesianOptimization(
...
---> 65 if max_acq is None or -res.fun[0] >= max_acq:
     66     x_max = res.x
     67     max_acq = -res.fun[0]

**TypeError: 'float' object is not subscriptable**

**Comment by bwheelz36** [comment]
pretty sure this is #300

**Comment by djj067** [comment]
> pretty sure this is #300

yes bro, i sloved it after i moved model to colab lol
