### ISSUE TITLE
How could I obtain 2 or more observation points at a single iteration?

### ISSUE THREAD

**Issue by UCASAlbert** [fmfn/BayesianOptimization#340]
Dear guys:
        I found that the function "next_point_to_probe = optimizer.suggest(utility)" can only give one suggesting observation point. However, in my experiment, I want 5 observation points during each iteration.  
        How could I fix that?
![1658910645017(1)](https://user-images.githubusercontent.com/86953517/181200563-0b5ee234-1623-4e0e-b38c-9da25788499e.png)

**Comment by bwheelz36** [comment]
interesting question, which was also asked in #327 (I closed that because no one was writing back but possibly should have left it open!).
I think maybe at the moment you can't do this. 

In principle you could add a parameter to suggest like n_suggest=5, and based on some criteria get back the five best candidates. But figuring out what this criteria should be could be tricky.
One option could be choose the five best points based on increasingly exploratory weighting in the acquisition function... e.g. in UCB, say the user has kappa =5 and requests n_suggestions, you could do something like:

```python
for suggestion in n_suggestions:
    kappa_temp = kappa + some_number
    # now solve acquisition function with kappa temp
```

But it would need some work on this feature, which to be clear I don't have time to do! But pull requests are welcome...

**Comment by UCASAlbert** [comment]
> 

Thanks a lot. I will try this and come back to tell the results.

**Comment by UCASAlbert** [comment]
@bwheelz36 
thanks a lot. I fix this point by writing a new function "acq_max_plus" in the source code util.py as following
def acq_max_plus(ac, gp, y_max, bounds, random_state, n_warmup=10000, n_iter=10, n_suggestion=10):
    # Warm up with random points
    x_tries = random_state.uniform(bounds[:, 0], bounds[:, 1],
                                   size=(n_warmup, bounds.shape[0]))
    x_tries = np.around(x_tries,5)
    ys = ac(x_tries, gp=gp, y_max=y_max)
    # x_max = x_tries[ys.argmax()]
    # max_acq = ys.max()
    acq_list.extend(ys)
    x_list.extend(x_tries)

    # Explore the parameter space more throughly
    x_seeds = random_state.uniform(bounds[:, 0], bounds[:, 1],
                                   size=(n_iter, bounds.shape[0]))
    x_seeds = np.around(x_seeds,5)

    for x_try in x_seeds:
        # Find the minimum of minus the acquisition function
        res = minimize(
            lambda x: -ac(np.around(x,5).reshape(1, -1), gp=gp, y_max=y_max),
                       x_try.reshape(1, -1),
                       bounds=bounds,
                       method="L-BFGS-B"
        )

        # See if success
        if not res.success:
            continue

        acq_list.append(-res.fun[0])
        x_list.append(res.x)

    acq_ind = np.argsort(acq_list)[::-1]
    x_sort = np.asarray(x_list)[acq_ind][:n_suggestion]
    acq_sort = np.asarray(acq_list)[acq_ind]

    return np.clip(x_sort, bounds[:, 0], bounds[:, 1])

the logic is to give out the points with 'top n_suggestion' acquisition function values.

**Comment by UCASAlbert** [comment]
@bwheelz36
thanks a lot. I fix this point by writing a new function "acq_max_plus" in the source code util.py as following



def acq_max_plus(ac, gp, y_max, bounds, random_state, n_warmup=10000, n_iter=10, n_suggestion=10):
# Warm up with random points
x_tries = random_state.uniform(bounds[:, 0], bounds[:, 1],
size=(n_warmup, bounds.shape[0]))
x_tries = np.around(x_tries,5)
ys = ac(x_tries, gp=gp, y_max=y_max)
# x_max = x_tries[ys.argmax()]
# max_acq = ys.max()
acq_list.extend(ys)
x_list.extend(x_tries)

# Explore the parameter space more throughly
x_seeds = random_state.uniform(bounds[:, 0], bounds[:, 1],
                               size=(n_iter, bounds.shape[0]))
x_seeds = np.around(x_seeds,5)

for x_try in x_seeds:
    # Find the minimum of minus the acquisition function
    res = minimize(
        lambda x: -ac(np.around(x,5).reshape(1, -1), gp=gp, y_max=y_max),
                   x_try.reshape(1, -1),
                   bounds=bounds,
                   method="L-BFGS-B"
    )

    # See if success
    if not res.success:
        continue

    acq_list.append(-res.fun[0])
    x_list.append(res.x)

acq_ind = np.argsort(acq_list)[::-1]
x_sort = np.asarray(x_list)[acq_ind][:n_suggestion]
acq_sort = np.asarray(acq_list)[acq_ind]

return np.clip(x_sort, bounds[:, 0], bounds[:, 1])
the logic is to give out the points with 'top n_suggestion' acquisition function values.

**Comment by UCASAlbert** [comment]
@bwheelz36
thanks a lot. I fix this point by writing a new function "acq_max_plus" in the source code util.py as following:

```
def acq_max_plus(ac, gp, y_max, bounds, random_state, n_warmup=10000, n_iter=10, n_suggestion=10):
# Warm up with random points
x_tries = random_state.uniform(bounds[:, 0], bounds[:, 1],
size=(n_warmup, bounds.shape[0]))
x_tries = np.around(x_tries,5)
ys = ac(x_tries, gp=gp, y_max=y_max)
# x_max = x_tries[ys.argmax()]
# max_acq = ys.max()
acq_list.extend(ys)
x_list.extend(x_tries)

# Explore the parameter space more throughly
x_seeds = random_state.uniform(bounds[:, 0], bounds[:, 1],
                               size=(n_iter, bounds.shape[0]))
x_seeds = np.around(x_seeds,5)

for x_try in x_seeds:
    # Find the minimum of minus the acquisition function
    res = minimize(
        lambda x: -ac(np.around(x,5).reshape(1, -1), gp=gp, y_max=y_max),
                   x_try.reshape(1, -1),
                   bounds=bounds,
                   method="L-BFGS-B"
    )

    # See if success
    if not res.success:
        continue

    acq_list.append(-res.fun[0])
    x_list.append(res.x)

acq_ind = np.argsort(acq_list)[::-1]
x_sort = np.asarray(x_list)[acq_ind][:n_suggestion]
acq_sort = np.asarray(acq_list)[acq_ind]

return np.clip(x_sort, bounds[:, 0], bounds[:, 1])
```

the logic is to give out the points with 'top n_suggestion' acquisition function values.

**Comment by bwheelz36** [comment]
ok, glad it worked - I will close this now then :-)

**Comment by bwheelz36** [comment]
Hey @UCASAlbert see #347 - I hadn't thought of this but essentially you could create a temporary acquisition function and use the kappa decay functionality to get multiple suggestions

**Comment by means-to-meaning** [comment]
Perhaps a silly question, but my first go to idea would not be to use 5 different kappas, but take _n_ local maxima from the given utility function. This would not work in later stages of the optimization where there is one dominant candidate location though..

**Comment by bwheelz36** [comment]
Hey  @means-to-meaning,
the underlying gaussian process has both an estimate and and uncertainty for the objective function at each point. kappa defines how you choose to trade off these two things - you can choose a highly uncertain point (high kappa) or ignore uncertainty and pick a point with a high predicted value (low kappa). The other issue with "n local maxima" is that n local maxima may not exist. 

Having said this, ultimately this behavior only makes sense if you are able to do parallel optimization, and in that case you should see #347 for a much better thought out approach.
