### ISSUE TITLE
How can I remove some value in the optimizer?

### ISSUE THREAD

**Issue by zdcao121** [fmfn/BayesianOptimization#341]
Hi, it's a nice project. I setup a BO object like the following code and iterate several steps:  

  `optimizer = BayesianOptimization(target, {'x': (-2, 10)}, random_state=27)`

the values of targets and parameters are stored in the `optimizer.res` attribute.  Then I want to remove some values in the `optimizer.res`, but it shows that

  `AttributeError: can't set attribute`.

So could you tell me how can I remove some observation (targets and parameters) in the `optimizer` ?

**Comment by bwheelz36** [comment]
Hey, not sure off the top of my head - can I ask why you would want to do that?

If you really want to hack it, you may be able to remove some points from `optimizer._space.params` and `optimizer._space.targe` and call `optimizer._gp.fit(optimizer._space.params, optimizer._space.target)`

I'm not sure this will remove those points from optimizer.res though.

**Comment by zdcao121** [comment]
Because sometimes the `optimizer` would step into some regions that are not acceptable in physics. While it happens, we skip the calculation and return senseless values to penalize the algorithm. But these values would be added into the `optimizer.res` and have a non-negligible influence on the iterations. So I want to remove these values in the `optimizer` and reset the bound.

**Comment by bwheelz36** [comment]
I see. I would handle this by returning a low (I.e. bad) value to the optimiser, signalling that this is not an interesting region to search. I dont think you should need to remove it.

**Comment by zdcao121** [comment]
Maybe the bad value I set in my program is inappropriate. The objective function is around 0, but the bad value is set to be -50.

**Comment by bwheelz36** [comment]
well you control the objective function right? so add in a line:

```python
if OF<bad_value:
    OF = better_value_thats_still_bad

return OF
```

**Comment by zdcao121** [comment]
Thanks for your reply.
