### ISSUE TITLE
RuntimeWarning: invalid value encountered in true_divide

### ISSUE THREAD

**Issue by freekeys** [fmfn/BayesianOptimization#342]
Hello! Thanks for this great package. I've suddenly started getting this error when I run this (nothing has changed in my code or data). Any idea what this could be please? Anyone else seeing this?

/usr/local/lib/python3.7/dist-packages/scipy/optimize/_numdiff.py:579: RuntimeWarning: invalid value encountered in true_divide
  J_transposed[i] = df / dx

**Comment by till-m** [comment]
Hi @freekeys, thanks for reporting this bug. Could you provide a minimal working example so that I can reproduce your problem?

**Comment by bwheelz36** [comment]
hey @freekeys is still an issue for you?
