### ISSUE TITLE
Add Issue templates

### ISSUE THREAD

**Issue by till-m** [fmfn/BayesianOptimization#343]
I think adding issue templates to this repository might be a good idea.

Currently users often submit bug reports with problem descriptions that are not particularly helpful. Adding issue templates would encourage users to equip their bug reports with information that should speed-up diagnosis. It might also help add some structure to feature requests.
I've made a draft (mostly based around the default github templates), which can be previewed [here](https://github.com/till-m/BayesianOptimization/issues/new/choose), but I think there are many ways to skin this particular cat (and most of them are better than not having templates).

**Comment by bwheelz36** [comment]
good idea!

**Comment by bwheelz36** [comment]
unfortunately I can't do this - I don't have access to the repository settings as a maintainer :-(

**Comment by till-m** [comment]
Sorry, things are a bit hectic on my end at the moment, I will investigate when I can.

**Comment by bwheelz36** [comment]
ah - doh!
thanks for double checking and resolving, that should be a massive improvement.
