### ISSUE TITLE
Doesn't work with *args or **kwargs in case you want to include many inputs

### ISSUE THREAD

**Issue by abdullahmsalama** [fmfn/BayesianOptimization#349]
Doesn't work with *args or **kwargs. I want to be able to optimize around 300 variables, I cannot just write them in the function input as they exceed python maximum, but when I try to add *args, it conflicts because the input variable to be explicitly mentioned in pbounds. So I receive one of two errors: 

1- "TypeError: cost_function() got an unexpected keyword argument 'input1'" or
2- "TypeError: cost_function() keywords must be strings"

**To Reproduce**

```python
from bayes_opt import BayesianOptimization
from past.builtins import xrange

#cost_function (to be maximized)
def cost_function(*args):
    sum = 0
    for x in args:
        sum = sum + x
     return sum

# Bounded region of parameter space
pbounds = {}
for i in xrange(10):
    pbounds['input' + str(i + 1)] = (0, 100)

optimizer = BayesianOptimization(
    f = cost_function,\
    pbounds = pbounds,\
    random_state = 1,
)

optimizer.maximize(
    init_points = 2,
    n_iter = 1,
)
```

**Comment by till-m** [comment]
While I think that this is a valid point in general and the issue should probably be adressed, please note that (at least to the extent of my knowledge) BO does not perform particularly well when optimizing functions over high-dimensional spaces and it may be worth considering other approaches instead.

**Comment by bwheelz36** [comment]
Hey, I can get this to run by changing the objective function as below. Does this solve this problem?

```python
def cost_function(**args):
    sum = 0
    for x in args:
        sum = sum + args[x]
    return sum
```

**Comment by abdullahmsalama** [comment]
Yes, that solved it, it worked with **kwargs, I don't know how I missed but I glad it works. Thanks @bwheelz36!

**Comment by Deepyman** [comment]
> Yes, that solved it, it worked with **kwargs, I don't know how I missed it but I glad it works. Thanks @bwheelz36!

Hi, did you solve your 300 variables problem? The dimension is too high.....

**Comment by abdullahmsalama** [comment]
@Deepyman, no, I was just trying something out with the function. But ofc the dimension is too high so it takes ages.
