### ISSUE TITLE
Strange search results

### ISSUE THREAD

**Issue by Serhiy-Shekhovtsov** [fmfn/BayesianOptimization#35]
I am trying to use Bayesian hyperparameter optimization and the points selected by this algorithm looks really weird to me. Here is an example:
![Bayesian hyperparameter optimization](http://image.prntscr.com/image/323ff805961049bb9956ac045dc7c039.png)
and an other one:
![Bayesian hyperparameter optimization](http://image.prntscr.com/image/58e04fab47c24da49d6b18e0878fe0d7.png)
There were only these two parameters being optimized, so it's not a problem of dimentions. 
It looks like it sticks to some values and doesn't try neighbor points. Is it an expected behavior?
I used [this example](https://github.com/fmfn/BayesianOptimization/blob/master/examples/xgb_example.py) as a base.

**Comment by fmfn** [comment]
Care to share the code?

**Comment by Serhiy-Shekhovtsov** [comment]
Sure, I will put some pieces here and also I am going to push all my code to this repository as usage examples, when a kaggle competition is over.

```python
from pylightgbm.models import GBMRegressor

num_rounds = 5000
early_stopping_rounds = 25

def getRegressor():
    return GBMRegressor(
        config='',
        application='regression',
        num_iterations=num_rounds,
        early_stopping_round=early_stopping_rounds,
        learning_rate=0.01,
        num_threads=8,
        metric='l1',
        feature_fraction_seed=RANDOM_STATE,
        bagging_seed=RANDOM_STATE,
        verbose=False)

fixed_params = {
    # gives score 1133.7647
    'max_bin': 840,
    'num_leaves': 99,
    
    # to be checked later
    'bagging_fraction': 0.8,
    'bagging_freq': 100
}

# checking now
params = {
    'min_data_in_leaf': (1, 1000), # int[1 : 3000, 100]
    'feature_fraction': (0.01, 0.9), # float[0.0 : 1.0, 1.0]
}
```

```python
search_log_file = output_folder + 'light-GBM-optimization-5.csv'
search_log_cols = list(params.keys()) + ['target']
search_log = pd.DataFrame(columns=search_log_cols)

def xgb_evaluate(**kwargs):
    global search_log
    
    # set params we've found
    new_x = {}
    new_x.update(fixed_params)
    
    # set params we are checking right now
    new_x.update(kwargs)
    
    # fix decimal places and ranges
    new_x['max_bin'] = int(new_x['max_bin'])
    new_x['num_leaves'] = int(new_x['num_leaves'])
    new_x['min_data_in_leaf'] = int(new_x['min_data_in_leaf'])
    new_x['feature_fraction'] = max(min(new_x['feature_fraction'], 1), 0)
    new_x['bagging_fraction'] = max(min(new_x['bagging_fraction'], 1), 0)
    new_x['bagging_freq'] = int(new_x['bagging_freq'])
    
    print('starting cv with parameters: ' + str(new_x))

    search_log.drop_duplicates(search_log_cols[:-1], inplace=True)
    
    # add row with new parameters to log
    i = search_log.shape[0]
    search_log.loc[i] = pd.DataFrame([new_x], columns=search_log_cols).loc[0]
    
    # if we already tested these parameters then drop last row and return existing result
    # ...
    
    # train and validate    
    scores = []
    for i, (train_index, test_index) in enumerate(cv_folds):        
        gbmr = getRegressor()
        gbmr.param.update(new_x)
        
        X_train, X_val = X_train_scaled.iloc[train_index], X_train_scaled.iloc[test_index]
        y_train, y_val = Y_train.iloc[train_index], Y_train.iloc[test_index]

        gbmr.fit(X_train, y_train)
        y_pred = gbmr.predict(X_val)
        cv = evalerrorGridSearch(y_val, y_pred)
        
        scores.append(cv)

    result = np.array(scores).mean()
    print('CV score: ' + str(result))
    
    # save new score to last row of the log
    last_item_i = search_log.shape[0] - 1
    search_log.loc[last_item_i][-1] = result
    
    # save to file
    search_log.to_csv(search_log_file, index=None)
    
    return -result
```

```python
num_iter = 25
init_points = 8

xgbBO = BayesianOptimization(xgb_evaluate, params)

xgbBO.maximize(init_points=init_points, n_iter=num_iter)
```

**Comment by Serhiy-Shekhovtsov** [comment]
As it's been suggested in [this thread](https://www.kaggle.com/c/allstate-claims-severity/forums/t/25905/bayesian-optimization-is-misbehaving) there are two things worth trying: increasing number of init points and increasing kappa parameter. I am trying first one then will check the second and will let you know.
Do you have any other suggestions?

**Comment by fmfn** [comment]
Use `acq='ucb'` (maximize parameter), tends to perform much better than `ei`, which sometimes performs weirdly. If using UCB, Kappa will certainly help it explore more. I'm actually going to make the default method now.

I think it would make sense to transform both your parameters to a log scale. Instead of `min_data_in_leaf: (1, 1000)`, use `log10_min_data_in_leaf: (1, 3)`, and inside the `xgb_evaluate` function you transform back to `int( 10 ** new_x['min_data_in_leaf'] )`.

I'm not sure what kind of variance your CV shows, but tinkering with the GP parameters `alpha` can help when the target variable is noisy. You can pass `{'alpha': 1e-4}` or any other value, to the maximize method.

**Comment by Serhiy-Shekhovtsov** [comment]
This plot contains 20 points generated using grid search and then Bayesian optimization started with `acq='ucb'`
![Grid Search and Bayesian optimization](http://image.prntscr.com/image/608701ca0df2483c8e05ad4b78bea14f.png)

**Comment by fmfn** [comment]
The impact of changing `min_data_in_leaf` from 1 to 2 or to 10 is much greater than if it were changed from 999 to 1000.
