### ISSUE TITLE
bayes_op&lightGBM

### ISSUE THREAD

**Issue by JiHong1235676** [fmfn/BayesianOptimization#352]
[LightGBM] [Warning] Using self-defined objective function
Traceback (most recent call last):
  File "D:\Conda\anzhuang\lib\site-packages\bayes_opt\target_space.py", line 191, in probe
    target = self._cache[_hashable(x)]
KeyError: (0.4224347626508457,)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "E:\During_DR\PYradar\1_paper\git_bys.py", line 118, in <module>
    LGB_BO.maximize(init_points=2, n_iter=2)
  File "D:\Conda\anzhuang\lib\site-packages\bayes_opt\bayesian_optimization.py", line 185, in maximize
    self.probe(x_probe, lazy=False)
  File "D:\Conda\anzhuang\lib\site-packages\bayes_opt\bayesian_optimization.py", line 116, in probe
    self._space.probe(params)
  File "D:\Conda\anzhuang\lib\site-packages\bayes_opt\target_space.py", line 194, in probe
    target = self.target_func(**params)
  File "E:\During_DR\PYradar\1_paper\git_bys.py", line 110, in LGB_CV
    return -MSE(pf, PF)
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\utils\validation.py", line 63, in inner_f
    return f(*args, **kwargs)
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\metrics\_regression.py", line 335, in mean_squared_error
    y_type, y_true, y_pred, multioutput = _check_reg_targets(
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\metrics\_regression.py", line 88, in _check_reg_targets
    check_consistent_length(y_true, y_pred)
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\utils\validation.py", line 316, in check_consistent_length
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\utils\validation.py", line 316, in <listcomp>
    lengths = [_num_samples(X) for X in arrays if X is not None]
  File "D:\Conda\anzhuang\lib\site-packages\sklearn\utils\validation.py", line 259, in _num_samples
    raise TypeError("Singleton array %r cannot be considered"
TypeError: Singleton array 0.15225424981522542 cannot be considered a valid collection.

**Comment by JiHong1235676** [comment]
This is code:


`#_author:Administrator
#date:2022/9/7


#_author:Administrator
#date:2022/9/7


import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split, cross_val_score
from sklearn.metrics import roc_auc_score,accuracy_score,confusion_matrix
import lightgbm as lgb
from scipy.misc import derivative
import scipy.io as scio
import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)
from sklearn.metrics import mean_squared_error as MSE
import time
from datetime import datetime

train=pd.read_csv(r'E:\During_DR\PYradar\1_paper\NCUALL20_2.csv',encoding='gb2312' ,index_col=0)

Xtrain=train.drop(['label'],axis=1)
Ytrain=train['label']

test=pd.read_csv(r'E:\During_DR\PYradar\1_paper\wr_lightgbm\feture2_3.csv',encoding='gb2312' ,index_col=0)
test.dropna(axis=0,how='all')
Xtest=test.drop(['label'],axis=1)
Ytest=test['label']
Xtest=np.array(Xtest)



def focal_loss_lgb(y_pred, dtrain, alpha, gamma):
    a, g = alpha, gamma
    # print('alpha={}；gamma={}'.format(alpha,gamma))
    y_true = dtrain.label

    def fl(x, t):
        p = 1 / (1 + np.exp(-x))

        return -(a * t + (1 - a) * (1 - t)) * ((1 - (t * p + (1 - t) * (1 - p))) ** g) * (t * np.log(p) + (1 - t) * np.log(1 - p))
    partial_fl = lambda x: fl(x, y_true)
    grad = derivative(partial_fl, y_pred, n=1, dx=1e-6)
    hess = derivative(partial_fl, y_pred, n=2, dx=1e-6)
    return grad, hess

def focal_loss_lgb_eval_error(y_pred, dtrain, alpha, gamma):
    a, g = alpha, gamma

    y_true = dtrain.label
    p = 1 / (1 + np.exp(-y_pred))
    loss = -(a * y_true + (1 - a) * (1 - y_true)) * ((1 - (y_true * p + (1 - y_true) * (1 - p))) ** g) * (y_true * np.log(p) + (1 - y_true) * np.log(1 - p))

    return 'focal_loss', np.mean(loss), False


def timer(start_time=None):
    if not start_time:
        start_time = datetime.now()
        return start_time
    elif start_time:
        thour, temp_sec = divmod(
            (datetime.now() - start_time).total_seconds(), 3600)
        tmin, tsec = divmod(temp_sec, 60)
        print('\n Time taken: %i hours %i minutes and %s seconds.' % (thour, tmin, round(tsec, 2)))


def LGB_CV(alpha_0):
    PF = 1
    focal_loss = lambda x, y: focal_loss_lgb(x, y, alpha_0, 0)  ###0.7
    eval_error = lambda x, y: focal_loss_lgb_eval_error(x, y, alpha_0, 0)  ##3
    lgtrain = lgb.Dataset(
        Xtrain, Ytrain,
        free_raw_data=False)
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'binary',
        # 'objective': 'regression',
        'metric': {'binary_logloss'},
        'max_depth': 11,
        'num_leaves': 25,
        'num_trees': 80,
        'learning_rate': 0.2,
        # 'num_threads':40,
        'feature_fraction': 0.9,
        'bagging_fraction': 0.9,
        'bagging_freq': 5,
        'verbose': 0
    }
    t0 = time.time()
    model = lgb.train(
        params,
        lgtrain,
        # valid_sets=[lgvalid],
        fobj=focal_loss,
        feval=eval_error
    )
    preds = model.predict(Xtrain, num_iteration=model.best_iteration)
    def sigmoid(x): return 1. / (1. + np.exp(-x))
    preds = sigmoid(preds)
    y_pred = [int(p > 0.5) for p in preds]
    confusion_matrix1 = confusion_matrix(Ytrain, y_pred)  # ,labels=[0,1]
    TP = confusion_matrix1[1, 1]
    FP = confusion_matrix1[0, 1]
    pf = FP / (TP + FP)

    return -MSE(pf, PF)


pbounds={'alpha_0':(0.01,0.999)}
from bayes_opt import BayesianOptimization
LGB_BO = BayesianOptimization(LGB_CV,
                              pbounds=pbounds,
                              random_state=1,)
LGB_BO.maximize(init_points=2, n_iter=2)
print(LGB_BO.max)`

**Comment by JiHong1235676** [comment]
`def LGB_CV(alpha_0):
    PF = 1
    focal_loss = lambda x, y: focal_loss_lgb(x, y, alpha_0, 0)  ###0.7
    eval_error = lambda x, y: focal_loss_lgb_eval_error(x, y, alpha_0, 0)  ##3
    lgtrain = lgb.Dataset(
        Xtrain, Ytrain,
        free_raw_data=False)
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'binary',
        # 'objective': 'regression',
        'metric': {'binary_logloss'},
        'max_depth': 11,
        'num_leaves': 25,
        'num_trees': 80,
        'learning_rate': 0.2,
        # 'num_threads':40,
        'feature_fraction': 0.9,
        'bagging_fraction': 0.9,
        'bagging_freq': 5,
        'verbose': 0
    }
    t0 = time.time()
    model = lgb.train(
        params,
        lgtrain,
        # valid_sets=[lgvalid],
        fobj=focal_loss,
        feval=eval_error
    )
    preds = model.predict(Xtrain, num_iteration=model.best_iteration)
    def sigmoid(x): return 1. / (1. + np.exp(-x))
    preds = sigmoid(preds)
    y_pred = [int(p > 0.5) for p in preds]
    confusion_matrix1 = confusion_matrix(Ytrain, y_pred)  # ,labels=[0,1]
    TP = confusion_matrix1[1, 1]
    FP = confusion_matrix1[0, 1]
    pf = FP / (TP + FP)

    return -MSE(pf, PF)


pbounds={'alpha_0':(0.01,0.999)}
from bayes_opt import BayesianOptimization
LGB_BO = BayesianOptimization(LGB_CV,
                              pbounds=pbounds,
                              random_state=1,)
LGB_BO.maximize(init_points=2, n_iter=2)
print(LGB_BO.max)`

**Comment by JiHong1235676** [comment]
`This is code `
`def LGB_CV(alpha_0):
    PF = 1
    focal_loss = lambda x, y: focal_loss_lgb(x, y, alpha_0, 0)  ###0.7
    eval_error = lambda x, y: focal_loss_lgb_eval_error(x, y, alpha_0, 0)  ##3
    lgtrain = lgb.Dataset(
        Xtrain, Ytrain,
        free_raw_data=False)
    params = {
        'task': 'train',
        'boosting_type': 'gbdt',
        'objective': 'binary',
        # 'objective': 'regression',
        'metric': {'binary_logloss'},
        'max_depth': 11,
        'num_leaves': 25,
        'num_trees': 80,
        'learning_rate': 0.2,
        # 'num_threads':40,
        'feature_fraction': 0.9,
        'bagging_fraction': 0.9,
        'bagging_freq': 5,
        'verbose': 0
    }
    t0 = time.time()
    model = lgb.train(
        params,
        lgtrain,
        # valid_sets=[lgvalid],
        fobj=focal_loss,
        feval=eval_error
    )
    preds = model.predict(Xtrain, num_iteration=model.best_iteration)
    def sigmoid(x): return 1. / (1. + np.exp(-x))
    preds = sigmoid(preds)
    y_pred = [int(p > 0.5) for p in preds]
    confusion_matrix1 = confusion_matrix(Ytrain, y_pred)  # ,labels=[0,1]
    TP = confusion_matrix1[1, 1]
    FP = confusion_matrix1[0, 1]
    pf = FP / (TP + FP)

    return -MSE(pf, PF)


pbounds={'alpha_0':(0.01,0.999)}
from bayes_opt import BayesianOptimization
LGB_BO = BayesianOptimization(LGB_CV,
                              pbounds=pbounds,
                              random_state=1,)
LGB_BO.maximize(init_points=2, n_iter=2)
print(LGB_BO.max)`

**Comment by till-m** [comment]
Hi @JiHong1235676,

I can't run your code because a few things are missing (imports, etc). Please also try to wrap long codeblocks with triple backticks \`\`\` so that indentation is preserved and the code remains readable.
By just analyzing the stack trace, I think that the problem occurring here does not stem from this package. Rather, the error seems to be produced by one of the arguments of `MSE` being a singleton array.

This means that an `np.ndarray` was generated like this
```python
a = np.array(3.141)
```
and not wrapped in an iterable
```python
a = np.array([3.141])
```

something you could try is to replace the line `return -MSE(pf, PF)` with
```python
return -MSE(np.atleast_1d(pf), np.atleast_1d(PF))
```
I hope this helps. Let me know if it works.

**Comment by JiHong1235676** [comment]
Thank you very much, and I'll debug my code this way. Since the data I use is private, it is not convenient to upload.

**Comment by JiHong1235676** [comment]
> Hi @JiHong1235676,
> 
> I can't run your code because a few things are missing (imports, etc). Please also try to wrap long codeblocks with triple backticks ``` so that indentation is preserved and the code remains readable. By just analyzing the stack trace, I think that the problem occurring here does not stem from this package. Rather, the error seems to be produced by one of the arguments of `MSE` being a singleton array.
> 
> This means that an `np.ndarray` was generated like this
> 
> ```python
> a = np.array(3.141)
> ```
> 
> and not wrapped in an iterable
> 
> ```python
> a = np.array([3.141])
> ```
> 
> something you could try is to replace the line `return -MSE(pf, PF)` with
> 
> ```python
> return -MSE(np.atleast_1d(pf), np.atleast_1d(PF))
> ```
> 
> I hope this helps. Let me know if it works.

Thank you for solving my problem! I changed the MSE function into subtraction. The code runs successfully.

**Comment by till-m** [comment]
> Since the data I use is private, it is not convenient to upload

I understand, ideally in this case you would provide toy data.

> Thank you for solving my problem!

No problem, feel free to open another issue in case you run into trouble again :)

@bwheelz36 I think this can be closed.
