### ISSUE TITLE
New version in PyPi

### ISSUE THREAD

**Issue by chibai** [fmfn/BayesianOptimization#354]
**Is your feature request related to a problem? Please describe.**
Why the last version in PyPi is May 16, 2020
That is 2 year ago

**Describe the solution you'd like**
Can you release the most fresh version in PyPi

**References or alternative approaches**
Just release the code in PyPi

**Additional context**
I want to use the most fresh version in PyPi

**Are you able and willing to implement this feature yourself and open a pull request?**
Thank you very much!!!

**Comment by bwheelz36** [comment]
please see #339 and https://github.com/pypa/pypi-support/issues/2144 - we are doing our best!

**Comment by bwheelz36** [comment]
PS, as noted in the readme you can in the meantime use:

pip install git+https://github.com/fmfn/BayesianOptimization

not ideal I know but a workable solution
