### ISSUE TITLE
Constraint Error

### ISSUE THREAD

**Issue by YouHyin** [fmfn/BayesianOptimization#356]
I really want to put a constraint on Bayesian optimization. 
So I followed **[BayesianOptimization](https://github.com/fmfn/BayesianOptimization)/[examples](https://github.com/fmfn/BayesianOptimization/tree/master/examples)/constraints.ipynb**

![오류](https://user-images.githubusercontent.com/113442395/192304164-9d916cfa-bb36-4176-8f23-937d4b169f4f.png)

There is an error like this in the picture, how should I solve it?

I really need your help.Please help me.

Thank you!

**Comment by till-m** [comment]
Hi @YouHyin,

how did you install `BayesianOptimization`? There is some trouble with updating the package on PyPI and conda, so if you installed through normal distribution channels you will be using an old version that doesn't yet support constraints.

**Comment by qup20** [comment]
I would like to ask a question. I used the new version and adding the constraint has no effect, it still fetches the points that are not accepted, why is that? Also, the new version of logger will prompt me: TypeError: Object of type bool_ is not JSON serializable.
