### ISSUE TITLE
Why is  the result of  function 'optimizer.suggest(utility)' changed without  any update of the registered points?? 

### ISSUE THREAD

**Issue by UCASAlbert** [fmfn/BayesianOptimization#360]
dear guys:
       there occurs something during my work, let me simplify my question. The following is my code:

![image](https://user-images.githubusercontent.com/86953517/194708957-a0ad4ca9-d49f-49eb-a8c1-a9566628b2aa.png)

the result is:
the next point to probe in the 0th time run: {'x': 2.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 1th time run: {'x': 4.0, 'y': 3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 2th time run: {'x': 2.0, 'y': 3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 3th time run: {'x': 2.0, 'y': 3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 4th time run: {'x': 2.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 5th time run: {'x': 4.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 6th time run: {'x': 2.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 7th time run: {'x': 4.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 8th time run: {'x': 4.0, 'y': 3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]
the next point to probe in the 9th time run: {'x': 2.0, 'y': -3.0} with the resgitered points: [{'target': 5.0, 'params': {'x': 3.0, 'y': 0.0}}]

here, the parameters of the optimizer keep unchanged, however, the result of  optimizer.suggest(utility) changes even no new point is registered, which makes me quite confused. 
Another question: the suggested points in the 0th and 1th run are different. Which one should I choose to observe next? or they can be both be chosen?

**Comment by bwheelz36** [comment]
1. it is much easier to help if you use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead of pictures of your code
2. Since the model has only seen one point, it predicts the same mean value everywhere. so basically you are asking to find the maximum of a flat line, plus the uncertainty which is symmetric around the single registered point. To see what the model is doing, you could append the following code the bottom of your example, which will produce the attached plot.
You can see that in this single dimension, there are two points which would have the same value in the acquisition function. Over two dimensions I think there will be four points, which I think is what you are seeing.

```python
from matplotlib import pyplot as plt
x_predict = np.linspace(pbounds['x'][0], pbounds['x'][1], 100)
y_predict = np.ones(x_predict.shape) * initial_para['y']
points_to_predict = np.stack([x_predict, y_predict])
predicted_target, predicted_std = optimizer._gp.predict(points_to_predict.T, return_std=True)

plt.figure()
plt.plot(x_predict, predicted_target)
plt.fill_between(x_predict, predicted_target + predicted_std, predicted_target - predicted_std, alpha=0.5, color='C0')
plt.grid()
plt.show()
```
![Figure_1](https://user-images.githubusercontent.com/64300337/194787664-7822657a-2395-4963-85ac-f9ac26cf34c2.png)

**Comment by UCASAlbert** [comment]
> 1. it is much easier to help if you use [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks) instead of pictures of your code
> 2. Since the model has only seen one point, it predicts the same mean value everywhere. so basically you are asking to find the maximum of a flat line, plus the uncertainty which is symmetric around the single registered point. To see what the model is doing, you could append the following code the bottom of your example, which will produce the attached plot.
>    You can see that in this single dimension, there are two points which would have the same value in the acquisition function. Over two dimensions I think there will be four points, which I think is what you are seeing.
> 
> ```python
> from matplotlib import pyplot as plt
> x_predict = np.linspace(pbounds['x'][0], pbounds['x'][1], 100)
> y_predict = np.ones(x_predict.shape) * initial_para['y']
> points_to_predict = np.stack([x_predict, y_predict])
> predicted_target, predicted_std = optimizer._gp.predict(points_to_predict.T, return_std=True)
> 
> plt.figure()
> plt.plot(x_predict, predicted_target)
> plt.fill_between(x_predict, predicted_target + predicted_std, predicted_target - predicted_std, alpha=0.5, color='C0')
> plt.grid()
> plt.show()
> ```
> 
> ![Figure_1](https://user-images.githubusercontent.com/64300337/194787664-7822657a-2395-4963-85ac-f9ac26cf34c2.png)

Thanks a lot! 
Now I have understood.  Thank you ！
