### ISSUE TITLE
Bump version

### ISSUE THREAD

**Issue by till-m** [fmfn/BayesianOptimization#362]
The version of this package has been on 1.2.0 since over two years -- I think with bugs cropping up & getting patched and new features being added, it might be time to increase the version number.

**Comment by till-m** [comment]
Tangentially related sidenote: @bwheelz36 If you can sticky issues, it might be good to sticky something that tells people to install from github if they encounter problems. Users installing old versions from PyPI/Conda seems to be a source of problems.

**Comment by bwheelz36** [comment]
I guess I was hoping to tie the version update to an actual pypi release, but you are probably right.
so, 1.3.0?
not sure how to create a sticky issue (are you?) but we could add this note to the issue template?

**Comment by till-m** [comment]
1.3.0 sounds good to me!

> not sure how to create a sticky issue (are you?) but we could add this note to the issue template?

Sorry, looks like I mixed up the name, but assuming you have the permissions it should be fairly straightforward, see [here](https://docs.github.com/en/issues/tracking-your-work-with-issues/pinning-an-issue-to-your-repository).
