### ISSUE TITLE
New users read this! Please install directly from this repo

### ISSUE THREAD

**Issue by bwheelz36** [fmfn/BayesianOptimization#366]
As outlined in #339, the PyPi release is unfortunately lagging behind the development version of this repo.
In particular, the PyPi release will not work with scipy >= 1.8.0.

To overcome this, please install directly from this repo like this:

 ```pip install git+https://github.com/fmfn/BayesianOptimization```

**Comment by bwheelz36** [comment]
@bwpriest, please note we have now fixed the pypi version :-)

**Comment by bwpriest** [comment]
> @bwpriest, please note we have now fixed the pypi version :-)

Great! Thanks very much!
