### ISSUE TITLE
How to make the acquisition function work?

### ISSUE THREAD

**Issue by YouHyin** [fmfn/BayesianOptimization#369]
https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb 
Looking at the example here, I tried to create my target function and visualize bayesian optimization.
However, looking at the results, the acquistion function does not work at all.
![Figure_123](https://user-images.githubusercontent.com/113442395/197333103-c90aa184-a860-4bae-8c4b-2d98bd296022.png)

What should I do to plot acquistion function graph?

I'll put the code below.

import pybamm
import numpy as np
import matplotlib.pyplot as plt
from matplotlib import gridspec
from bayes_opt import BayesianOptimization
from bayes_opt import UtilityFunction

def fortemplimit(x,k,a) :
    model = pybamm.lithium_ion.DFN({"thermal": "lumped"})
    parameter_values = model.default_parameter_values
    experiment = pybamm.Experiment(
        [
            (
                "Charge at " + str(x) + " C for " + str(a) + " seconds",
                "Rest for " + str(k) + " seconds",
                "Hold at 4.1 V until 50 mA",
            )
        ]
        ,
        termination="80% capacity",
    )
    sim = pybamm.Simulation(
        model, experiment=experiment, solver=pybamm.CasadiSolver("fast with events"),parameter_values=parameter_values,
    )
    sim.solve()
    solution = sim.solution
    return (-1) * solution["Time [s]"].entries[-1]

def experiment_func(x):
    model = pybamm.lithium_ion.DFN({"thermal": "lumped"})
    parameter_values = model.default_parameter_values
    #fast_solver = pybamm.CasadiSolver(atol=1e-3, rtol=1e-3, mode="fast")
    vmax = 4.1
    experiment = pybamm.Experiment(
        [
            (
                "Charge at " + str(x) + " C until 4.1 V",
                "Hold at 4.1 V until 50 mA",

            )
        ]
        ,
        termination="80% capacity",
    )
    sim = pybamm.Simulation(
        model, experiment=experiment, solver=pybamm.CasadiSolver("fast with events"),parameter_values=parameter_values,
    )
    sim.solve()
    solution = sim.solution
    Times=[]

    for t in range(int(solution["Time [s]"].entries[-1])) :
        if solution["Volume-averaged cell temperature [K]"](t) >= 298.66154 :
            Times.append(t)

    if not Times :
        return (-1) * (solution["Time [s]"].entries[-1])

    else :
        k=max(Times)-min(Times)
        a=min(Times)
        return fortemplimit(x,k,a)

#print(experiment_func(2.7))

x = np.linspace(1, 3, 30)
real_x=x.reshape(-1,1)

Y=[]
for i in x :
    Y.append(experiment_func(i))
real_Y=np.array(Y).reshape(-1,1)

optimizer = BayesianOptimization(
    f=experiment_func,
    pbounds={"x": (1, 3)},
    verbose=1,
    random_state=987234,
)

optimizer.maximize(init_points=7, n_iter=10, acq="ei", xi=1e-01)
print(optimizer.max)

def posterior(optimizer, x_obs, y_obs, grid):
    optimizer._gp.fit(x_obs, y_obs)

    mu, sigma = optimizer._gp.predict(grid, return_std=True)
    return mu, sigma

def plot_gp(optimizer, x, y):
    fig = plt.figure(figsize=(16, 10))
    steps = len(optimizer.space)
    fig.suptitle(
        'Gaussian Process After {} Steps'.format(steps),
        fontdict={'size': 25}
    )

    gs = gridspec.GridSpec(2, 1, height_ratios=[3, 1])
    axis = plt.subplot(gs[0])
    acq = plt.subplot(gs[1])

    x_obs = np.array([[res["params"]["x"]] for res in optimizer.res])
    y_obs = np.array([res["target"] for res in optimizer.res])

    mu, sigma = posterior(optimizer, x_obs, y_obs, x)
    axis.plot(x, y, linewidth=3, label='Target')
    axis.plot(x_obs.flatten(), y_obs, 'D', markersize=8, label=u'Observations', color='r')
    axis.plot(x, mu, '--', color='k', label='Prediction')

    axis.fill(np.concatenate([x, x[::-1]]),
              np.concatenate([mu - 1.9600 * sigma, (mu + 1.9600 * sigma)[::-1]]),
              alpha=.6, fc='c', ec='None', label='95% confidence interval')

    axis.set_xlim((1, 3))
    axis.set_ylim((None, None))
    plt.gca().invert_yaxis()
    axis.set_ylabel('Objective value of charging time (second)', fontdict={'size': 15})
    axis.set_xlabel('Applied Current rate (C)', fontdict={'size': 15})
    plt.show()
    utility_function = UtilityFunction(kind="ei", kappa=0, xi=1e-01)
    utility = utility_function.utility(x, optimizer._gp, 0)
    acq.plot(x, utility, label='Utility Function', color='purple')
    acq.plot(x[np.argmax(utility)], np.max(utility), '*', markersize=15,
             label=u'Next Best Guess', markerfacecolor='gold', markeredgecolor='k', markeredgewidth=1)
    acq.set_xlim((1, 3))
    acq.set_ylim((0, np.max(utility) + 0.5))
    acq.set_ylabel('Utility', fontdict={'size': 20})
    acq.set_xlabel('x', fontdict={'size': 20})

    axis.legend(loc=2, bbox_to_anchor=(1.01, 1), borderaxespad=0.)
    acq.legend(loc=2, bbox_to_anchor=(1.01, 1), borderaxespad=0.)
    plt.show()
plot_gp(optimizer, real_x, real_Y)

**Comment by bwheelz36** [comment]
Hi, I'm happy to help but I'm not going to spend 30 minutes getting this example to run. 
can you please place the code you would like us to look at between three back ticks like this:

![image](https://user-images.githubusercontent.com/64300337/197420617-510d71ec-cd41-45f5-8e8a-c89f31c131c8.png)

If you give us an example that we can quickly run, we will be happy to help.

**Comment by YouHyin** [comment]
Looking at the graph, the acquisition function is not drawn at all. 
If you look at the graph I uploaded, the range of the axis of the acquisition function is from 0 to 1. 
This is precisely why I believe there is an error. 
I set the range of the axis of the acquisition function from 1 to 3 
-> axis.set_xlim((1, 3)). 
But the graph is from 0 to 1. What should I do to resolve this error?

**Comment by YouHyin** [comment]
First of all, thank you so much for watching. Sorry for taking so long to execute the code. Reducing the init points and n_iter in the optimization process will shorten the code execution time, but it will still take about 10 minutes. I'm so sorry. 
I think an error appears in the axis setting problem of the acquisition function. I definitely set the x-axis from 1 to 3, but in the actual graph, the x-axis from 0 to 1 is set. It would be nice if this part could be solved.

**Comment by bwheelz36** [comment]
Like I said: I cannot run the code you posted. That makes it difficult for me to help you.
Please post the code the way I suggested, maybe have a read of this [github article on posting code](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks).

The acquisition function is working perfectly, notice in your top points that you are getting an increasing number of samples near the maximum. What is not working is your plot; if you post useable code I will be able to tell you why.

**Comment by YouHyin** [comment]
Thanks to your answer, it was solved. Thank you vert much!
