### ISSUE TITLE
Multi-objective-bayesian-optimization

### ISSUE THREAD

**Issue by YouHyin** [fmfn/BayesianOptimization#374]
Is there a way to optimize two objective functions that you want to optimize at the same time? 
Is multi-objective Bayesian optimization possible?
I would appreciate it if you could tell me what to do.
Please help me.

**Comment by bwheelz36** [comment]
Hi, this is possible but at the moment (and for the foreseeable future) not supported by this package. 
[PyMoo](https://pymoo.org/algorithms/index.html) is a python library for multi objective optimization. I've never used it but I think it looks good. It doesn't have a bayesian algorithm however.
