### ISSUE TITLE
Register got an unexpected keyword argument constraint_value, or missing constraint_value when not added

### ISSUE THREAD

**Issue by aegonwolf** [fmfn/BayesianOptimization#377]
**Describe the bug**
Hi, I am trying to use my own loop.
When I initialize the optimizer like this:

```
optimizer = BayesianOptimization(
    f=None,
    pbounds={'x': (-2, 2), 'y': (-3, 3)},
    constraint = constraint,
    verbose=2,
    random_state=1,
)
```

and try to add a new observation:
```
optimizer.register(
    params=next_point_to_probe,
    target=target, constraint_value = -1.5,
)
```

I get:
`TypeError: register() got an unexpected keyword argument 'constraint_value'`
When I do:

```
optimizer.register(
    params=next_point_to_probe,
    target=target, 
)
```

instead, I get:

`TypeError: register() missing 1 required positional argument: 'constraint_value'`

Which is very confusing.

**Comment by aegonwolf** [comment]
I was able to circumvent it by calling optimizer._space.register() directly, however, it seems the Constraint_Model is then not updated.

**Comment by till-m** [comment]
See #375
