### ISSUE TITLE
Segmentation fault(Core dumped) when iteration starts

### ISSUE THREAD

**Issue by dheeraj-pant** [fmfn/BayesianOptimization#384]
Hi I was doing bayesian optimization using bayes_opt on a custom model but I was getting a strange error Segmentation Fault (Core Dumped) when I set n_iter to some value.

optimizer = BayesianOptimization(f = hyperparameter_tuning,
                                 pbounds = pbounds, verbose = 2,
                                 random_state = 4)
optimizer.maximize(init_points = 4, n_iter = 0)

This above code will run just fine. 

optimizer = BayesianOptimization(f = hyperparameter_tuning,
                                 pbounds = pbounds, verbose = 2,
                                 random_state = 4)
optimizer.maximize(init_points = 4, n_iter = 1)

However, in the above code when I set n_iter to some value it throws error.

Initially I thought its a memory issue but memory is enough and it seems like bayes_opt is crashing.

**Comment by till-m** [comment]
HI @dheeraj-pant,

can you please post a complete, minimal working example?

**Comment by bwheelz36** [comment]
I would guess this is not happening within this package, which is pure python so to my understanding unlikely to cause segmentation faults. Happy to be proved wrong with an example though :-)

**Comment by e96031413** [comment]
Hi, @dheeraj-pant, if you used pytorch inside the hyperparameter_tuning function, your could try to downgrade your pytorch version. If not, maybe you could downgrade the package version you used inside the hyperparameter_tuning function.
