### ISSUE TITLE
ImportError: cannot import name 'just_fix_windows_console'

### ISSUE THREAD

**Issue by schreini1** [fmfn/BayesianOptimization#387]
Hey guys,

sorry for the low level question, I'm just at the beginning. I wanted to import:
from bayes_opt import BayesianOptimization
and it throws an importError:
ImportError: cannot import name 'just_fix_windows_console'
<img width="379" alt="2022-12-02 08_15_47-JupyterLab " src="https://user-images.githubusercontent.com/119655340/205237976-e86a39f5-7c13-4a64-847c-51c0c33884f7.png">

These are the installed versions:
bayesian:
<img width="637" alt="bayesian_versions " src="https://user-images.githubusercontent.com/119655340/205237953-3c1310fa-3fa9-4b48-be5f-96d8d72ce39a.png">

Python 3.6.12

What do I miss?

**Comment by till-m** [comment]
Hi @schreini1,

could you try on python 3.7+?

**Comment by bwheelz36** [comment]
If you reinstall, you should get a version compatible with your python code

**Comment by nicrie** [comment]
Just as a info - I get the same error. I'm on Python 3.9 and did the installation via `conda`.

**Comment by till-m** [comment]
Hey @nicrie, I made an effort to fix the bug. If it's not too much of an issue, could you reinstall from conda and see if the problem is solved?

Thanks!

**Comment by nicrie** [comment]
Thanks @till-m :) Just tested it again in a fresh conda environment with Python 3.9 using `conda` (actually `mamba`) and it work like a charm! 

btw: cool & useful package, thanks for sharing!

**Comment by till-m** [comment]
Thanks for testing, I appreciate it!
> btw: cool & useful package, thanks for sharing!

I just do housekeeping here ;)

**Comment by 2258324319** [comment]
you need at least colorama==0.4.6， but it does not work on python36 and lower versions.
If you just want to solve the "unique point" bug, try 1.4.0
