### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by hossam955** [fmfn/BayesianOptimization#392]
Hello, i tried to import bayes_opt using both the following methods:
from bayes_opt import BayesianOptimization
import bayes_opt

But i get the following error for both methods:
ImportError: cannot import name 'BayesianOptimization' from partially initialized module 'bayes_opt' (most likely due to a circular import)

Any idea how i can proceed?

**Comment by bwheelz36** [comment]
hi, 
what process did you use to install?

**Comment by hossam955** [comment]
@bwheelz36 
I am using Anaconda. I tried installing using both the following:

pip install bayesian-optimization
conda install -c conda-forge bayesian-optimization

Still no luck.

**Comment by till-m** [comment]
Hi @hossam955,

I think this can also be related to the name of the file/files you're executing or that are in the directory you are executing from. Could you maybe show the contents of the folder?

**Comment by hossam955** [comment]
Yup, you are definitely correct @till-m. I named my python file bayes_opt.py, that's why the circular import occured. Surprisingly, it didn't occur one year ago when i first used this package :D

@till-m @bwheelz36 Thanks a lot for your time and input.

**Comment by till-m** [comment]
Glad to hear :)
