### ISSUE TITLE
Change the table size

### ISSUE THREAD

**Issue by xihajun** [fmfn/BayesianOptimization#395]
Hi thanks for the lovely tool! I wonder if it is possible to make the table a bit larger to show longer variable name?

```
|   iter    |  target   | batch_... | schedu... |
```

**Comment by xihajun** [comment]
https://github.com/fmfn/BayesianOptimization/blob/202dc3cc133d5fc5e787762863490acc101ef8e7/bayes_opt/logger.py#L14
could change here I reckon

**Comment by till-m** [comment]
Hey @xihajun,

off the top of my head, something like this would work:

```python
from bayes_opt import BayesianOptimization

def black_box_function(a_very_long_variable_name, y):
    """Function with unknown internals we wish to maximize.

    This is just serving as an example, for all intents and
    purposes think of the internals of this function, i.e.: the process
    which generates its output values, as unknown.
    """
    return -a_very_long_variable_name ** 2 - (y - 1) ** 2 + 1

pbounds = {'a_very_long_variable_name': (2, 4), 'y': (-3, 3)}

from bayes_opt.logger import ScreenLogger
from bayes_opt.event import Events

logger = ScreenLogger()
logger._default_cell_size = 20

optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=2, # verbose = 1 prints only when a maximum is observed, verbose = 0 is silent
    random_state=1,
)

for event in [Events.OPTIMIZATION_START, Events.OPTIMIZATION_STEP, Events.OPTIMIZATION_END]:
    optimizer.subscribe(event, logger)

optimizer.maximize(
    init_points=2,
    n_iter=3,
)

```
Output:
```
|         iter         |        target        | a_very_long_varia... |          y           |
---------------------------------------------------------------------------------------------
| 1                    | -7.135               | 2.834                | 1.322                |
| 2                    | -7.78                | 2.0                  | -1.186               |
| 3                    | -7.11                | 2.218                | -0.7867              |
| 4                    | -12.4                | 3.66                 | 0.9608               |
| 5                    | -6.999               | 2.23                 | -0.7392              |
=============================================================================================
```

Of course you can modify your local version of this package to adjust the cell size, as you have discovered.

**Comment by xihajun** [comment]
Thank you so much! @till-m 

I will close issue then :)

Alternative way was change the default value here: `/lib/python3.8/site-packages/bayes_opt/logger.py` at line 14

**Comment by xihajun** [comment]
Hi @till-m, I wonder if there is a way that we can change the table's target to another name `result`?

**Comment by xihajun** [comment]
maybe I can try to make a pull request if you think might be helpful?

**Comment by till-m** [comment]
Hey @xihajun,

this name is currently hardcoded: https://github.com/fmfn/BayesianOptimization/blob/202dc3cc133d5fc5e787762863490acc101ef8e7/bayes_opt/logger.py#L96

It would be possible to set it as an (underscore-prepended) property of the model, e.g. `ScreenLogger._target_column_title`. While I can't imagine that many people need to change the column names, I would not oppose this change since it is very minor. I probably wouldn't opt for adding a setter method though.

@bwheelz36 do you have an opinion on this matter?

**Comment by bwheelz36** [comment]
I agree, that change would not be a problem but I also wouldn't imagine it being used often.
