### ISSUE TITLE
Optimization with a noisy objective?

### ISSUE THREAD

**Issue by Falkenjack** [fmfn/BayesianOptimization#40]
In "A Tutorial on Bayesian Optimization of Expensive Cost Functions, with Application to Active User Modeling and Hierarchical Reinforcement Learning" ( http://arxiv.org/pdf/1012.2599v1.pdf ), linked to in the README.md, it says:

> Bayesian optimization is a powerful strategy for finding the extrema of objective
> functions that are expensive to evaluate.  It is applicable in situations where one
> does not have a closed-form expression for the objective function, but where one
> can obtain observations (possibly noisy) of this function at sampled values.  It
> is particularly useful when these evaluations are costly, when one does not have
> access to derivatives, or when the problem at hand is non-convex.

I have a problem where I can only obtain noisy observations of the objective function with reasonable evaluation cost. However, I'm not sure how to go about that using `BayesianOptimization`.

What I would like to do is to add some noise to the GP, such that the GP does not over-estimate the reliability of the objective function value, but I did not find any way to do that. If I understand it correctly, `sklearn` adds noise to GPs by adding a `WhiteKernel` to the main kernel. However, the GP settings in the `BayesianOptimization` class seems to be hard coded in `__init__` as:

```
self.gp = GaussianProcessRegressor(
            kernel=Matern(),
            n_restarts_optimizer=25,
)
```

Is there some other way to handle a noisy objective function or do I need to modify `__init__`? Is any acquisition function more suitable when working with noisy objective functions?

**Comment by fmfn** [comment]
You've got the right idea. The answer to your question is not properly documented, but if you scroll down [further](https://github.com/fmfn/BayesianOptimization/blob/master/bayes_opt/bayesian_optimization.py#L254) you see that when calling the `maximize` method you have the option to pass `**gp_params` which will then be passed back to `self.gp`. So, if you want to change the kernel, you may simply pass `kernel=RBF()` to `bo.maximize()`.

Now, when it comes to noisy regression, the most straightforward way of going about it is to simply increase the GP's parameter `alpha` (isotropic noise). Adding the `WhiteKernel` is similar to adding an array of alphas, which allows you model non-isotropic noise.

As far as acquisition functions goes, I usually prefer UCB.
