### ISSUE TITLE
Can we have a feature of ignoring the NaN y values come across for certain hyperparameter configurations

### ISSUE THREAD

**Issue by RuqiShi12** [fmfn/BayesianOptimization#411]
My optimization stopped in the middle of  iterations, and returned this error: ValueError: Input y contains NaN. I tried to fix it but then realized that I couldn't narrow my hyperparameter searching space such that I can be sure there will be no NaN value generated by a certain parameter configuration in this space.

Thus I would really appreciate that if you could add a feature that can ignore the Nan y values in the optimization process and still let the optimization continue even NaN y-value appears.

**Comment by till-m** [comment]
If I'm understanding right, this is not a bug in our code, but your target function potentially returning `NaN`(?)


In that case there are many ways you could avoid the problem, e.g. using the suggest-evaluate-register technique demonstrated in the [advanced notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) or by optimizing a surrogate function that catches the `NaN`s before returning them.

**Comment by RuqiShi12** [comment]
> If I'm understanding right, this is not a bug in our code, but your target function potentially returning `NaN`(?)
> 
> In that case there are many ways you could avoid the problem, e.g. using the suggest-evaluate-register technique demonstrated in the [advanced notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) or by optimizing a surrogate function that catches the `NaN`s before returning them.



> If I'm understanding right, this is not a bug in our code, but your target function potentially returning `NaN`(?)
> 
> In that case there are many ways you could avoid the problem, e.g. using the suggest-evaluate-register technique demonstrated in the [advanced notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/advanced-tour.ipynb) or by optimizing a surrogate function that catches the `NaN`s before returning them.

Thanks! Indeed, you understand right, I will try the advice you provided. If my problem is solved I will close this issue;)

**Comment by RuqiShi12** [comment]
> 

After using the suggest-evaluate-register technique, I still got error: ValueError: Input y contains NaN.

I might not have mastered the idea of SER technique, could you help me look at my code? My code is here:

```

    optimizer = BayesianOptimization(
        f=None,
        pbounds=pbounds,
        verbose=2,
        random_state=12,
    )

    from bayes_opt import UtilityFunction

    utility = UtilityFunction(kind="ucb", kappa=2.5, xi=0.0)

    next_point_to_probe = optimizer.suggest(utility)
    print("Next point to probe is:", next_point_to_probe)

    target = objective_function(**next_point_to_probe)
    print("Found the target value to be:", target)

    optimizer.register(
        params=next_point_to_probe,
        target=target,
    )
    obj_value = []
    configuration = []
    n_iter=100
    
    for _ in range(n_iter):
        next_point = optimizer.suggest(utility)
        target = objective_function(**next_point)
        optimizer.register(params=next_point, target=target)
        
        obj_value.append(target)
        configuration.append(next_point)
    
    # print(optimizer.max)

    with open('Bayes_opt_output/BO_G{}.csv'.format(ins_index[i]), 'w') as file:

        writer = csv.writer(file)
        writer.writerow(['Cut', 'Configuration Hyperparameter'])
        for i in range(len(obj_value)):
            writer.writerow([obj_value[i], configuration[i]])


```

**Comment by bwheelz36** [comment]
you should never pass a NaN to the model. write an objective like this:

```python
import numpy as np

def objective():
    
    objective = some_function():
    if np.isnan(objective):
        return 0  # or whatever you want 
    else:
        return objective

```

**Comment by RuqiShi12** [comment]
> 

Thanks! Now it works!
