### ISSUE TITLE
Can I use it for timeseries optimization, like I want to come out a control trajectory(96 steps), so the input will be 96 high dimension....So two questions: 1) is it suitable for 96 dimension optimization and 2) how to pass a np.array to the function, do I have to define in X1, X2,...X96? I really appreciate for any kind help!

### ISSUE THREAD

**Issue by Deepyman** [fmfn/BayesianOptimization#414]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

**Describe the solution you'd like**

**References or alternative approaches**
If this feature was described in literature, please add references here. Additionally, feel free to add descriptions of any alternative solutions or features you've considered.

**Additional context**

**Are you able and willing to implement this feature yourself and open a pull request?**
- [ ] Yes, I can provide this feature.

**Comment by till-m** [comment]
Generally speaking, bayesian optimization is probably not the best for optimizing over high-dimensional spaces. You can try it, of course, for that see @bwheelz36's comment in #349.

**Comment by Deepyman** [comment]
> Generally speaking, bayesian optimization is probably not the best for optimizing over high-dimensional spaces. You can try it, of course, for that see @bwheelz36's comment in #349.

Thank you! I also tried GA, but it can't solve 96 dimension problem. I think I should reduce the dimension. Do you have some suggestion like what solver might work or the maximum available dimension of BO solver? Or it depends on the complexity of the problem. Appreciate for your help

**Comment by bwheelz36** [comment]
20 dimensions is often stated as a rule of thumb for BO. of course it just depends very strongly on the problem.

how long does it take to evaluate your objective function? is it really a function of 96 independent variables?? I wonder if multi criteria optimization might be a better choice. then you can define multiple objective functions independently.
