### ISSUE TITLE
Question about whether a set of dictionary parameters can be used as independent variables in visualization.

### ISSUE THREAD

**Issue by jdzhu19** [fmfn/BayesianOptimization#421]
Hello! I have read the [visualization.ipynb](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb), and I wonder whether a set of dictionary parameters can be used as independent variables(or in other words, replace the "x" in the example) in visualization.

**Comment by till-m** [comment]
Hey @jdzhu19,

I don't think I understand exactly what you mean. The answer to your question is most likely yes, but if you can be a bit mroe specific I could give a better answer.

**Comment by jdzhu19** [comment]
> Hey @jdzhu19,
> 
> I don't think I understand exactly what you mean. The answer to your question is most likely yes, but if you can be a bit mroe specific I could give a better answer.

Hi! Thanks for your very quick reply, sorry I may not have made it clear what I meant was that the independent variables (that is, represented by the x-axis) in the plots drawn in the visualization.ipynb and other notebooks of this project are only the number x, not a set of dictionaries, for example, a set of dictionaries with keys params_key = {"a", "b", "c", "d"}, so when the case is passing in such a set of dictionaries to black_box_function, I wonder if it is still possible to visualize the curves predicted by the acquisition function and predicted curve and its confidence. I hope this clears up any confusion you may have had about my question.

**Comment by jdzhu19** [comment]
Another question if I may, after I called `bounds_transformer = SequentialDomainReductionTransformer(minimum_window=0.5)` and tried to do domain reduction, I got an error: `ValueError: Global bounds are not compatible with the minimum window size` and this error occurs even when I set minimum_window to 1. Here are my settings for bounds: `pbounds = {'a': (8, 10), 'b': (2, 4), 'c': (1, 1.5), 'd': (0.15, 0.2), 'e': (0.05, 0.1), 'f': (0, 2), 'g': (7, 9), 'h': (1, 2), 'i': (4, 5), 'j': (0, 5)}`. Does this mean that this function cannot simultaneously handle a set of dictionary parameters with different boundary settings?

**Comment by bwheelz36** [comment]
Hi @jdzhu19 

> Hello! I have read the [visualization.ipynb](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb), and I wonder whether a set of dictionary parameters can be used as independent variables(or in other words, replace the "x" in the example) in visualization.

So I'm also not sure I understand. But obviously visualization of 1 variable is easy. So is 2, as shown on the readme of this repo. Beyond this it gets tricky. What I sometimes do is hold all variables except for one at the current optimum, and produce a series of 1D plots. you can see an example if you scroll down [here](https://acrf-image-x-institute.github.io/TopasOpt/ApertureOptimisation.html#interpreting-the-results). If something like this is what you are trying to do, you can build off the code [here](https://github.com/ACRF-Image-X-Institute/TopasOpt/blob/8cf62900fb6439d58d779a5c3850d873c29f0ff3/TopasOpt/Optimisers.py#L885)

In general, this library does not include visualization, it is up to users to write their own visualization routines.

For your second question, can you create a separate issue and post code that allows us to reproduce the error?

**Comment by jdzhu19** [comment]
> Hi @jdzhu19
> 
> > Hello! I have read the [visualization.ipynb](https://github.com/fmfn/BayesianOptimization/blob/master/examples/visualization.ipynb), and I wonder whether a set of dictionary parameters can be used as independent variables(or in other words, replace the "x" in the example) in visualization.
> 
> So I'm also not sure I understand. But obviously visualization of 1 variable is easy. So is 2, as shown on the readme of this repo. Beyond this it gets tricky. What I sometimes do is hold all variables except for one at the current optimum, and produce a series of 1D plots. you can see an example if you scroll down [here](https://acrf-image-x-institute.github.io/TopasOpt/ApertureOptimisation.html#interpreting-the-results). If something like this is what you are trying to do, you can build off the code [here](https://github.com/ACRF-Image-X-Institute/TopasOpt/blob/8cf62900fb6439d58d779a5c3850d873c29f0ff3/TopasOpt/Optimisers.py#L885)
> 
> In general, this library does not include visualization, it is up to users to write their own visualization routines.
> 
> For your second question, can you create a separate issue and post code that allows us to reproduce the error?

Ok thanks for the advice, I wrote a visual program before but it didn't show as much as what you gave, I will read it carefully.
And I have opened a new issude, please check it out.
