### ISSUE TITLE
Error occurs when trying to do a domain reduction

### ISSUE THREAD

**Issue by jdzhu19** [fmfn/BayesianOptimization#422]
Since my previous file was reading parameters and results from a dataset that would be troublesome, I tried to modify a new sample code to restore the problem. Just run the python file. func is arbitrary but I guess it doesn't matter in this case, the code works fine after commenting out the bounds_transformer related code, but when there is a bounds_transformer part, I get a `ValueError: Global bounds are not compatible with the minimum window size.`
[BO_for_reproducing.zip](https://github.com/fmfn/BayesianOptimization/files/11459819/BO_for_reproducing.zip)

```python
from bayes_opt import BayesianOptimization
from bayes_opt import UtilityFunction
from bayes_opt import SequentialDomainReductionTransformer
import re
import os
import shutil
import matplotlib.pyplot as plt
from matplotlib.ticker import MultipleLocator
import numpy as np
import subprocess





# 定义一个黑盒函数来最大化
def black_box_function(**params):  # 接受任意数量的关键字参数并保存在字典params中
    global iteno
    print(f"\033[32m\n————————————Iteration No.{iteno}————————————\033[m")
    print(f"Parameters: {params}")
    func = params["A"] * params["B"] / params["C"] + params["D"] - params["E"] * params["F"] + params["G"]
    print("Func:", func, "\n")
    iteno += 1
    return func

params = {'A': 10, 'B': 4, 'C': 1, 'D': 0.2, 'E': 0.05, 'F': 2, 'G': 8}
pbounds = {'A': (8, 10), 'B': (2, 4), 'C': (1, 1.5), 'D': (0.15, 0.2), 'E': (0.05, 0.1), 'F': (0, 2), 'G': (7, 9)}

initial_param = {'A': 10, 'B': 4, 'C': 1, 'D': 0.2, 'E': 0.05, 'F': 2, 'G': 8}

iteno = 1

utility = UtilityFunction(kind="ucb", kappa=2.5, xi=0, kappa_decay=1.5, kappa_decay_delay=0)

bounds_transformer = SequentialDomainReductionTransformer(minimum_window=1)

# 创建优化器对象
optimizer = BayesianOptimization(
    f=black_box_function,
    pbounds=pbounds,
    verbose=2,
    random_state=1234,
    bounds_transformer=bounds_transformer
)


optimizer.set_gp_params(alpha=1e-3, n_restarts_optimizer=2)
# 执行贝叶斯优化以最大化黑盒函数
optimizer_result = optimizer.maximize(
    init_points=1,  # 指定了在开始Bayesian Optimization之前, 要进行多少次随机探索, 随机探索可以帮助扩大探索空间
    n_iter=30,  # 指定了要执行多少次Bayesian Optimization迭代, 每次迭代都会拟合高斯过程并使用采集函数选择下一个采样点
    acquisition_function = utility
    # 默认使用UCB作为acquisition function(kind='ucb', kappa=2.576, xi=0),指定EI作为acquisition function(已在/home/jzhu484/anaconda3/envs/dse/lib/python3.9/site-packages/bayes_opt/util.py中进行修改)  # TODO
)
```

**Comment by bwheelz36** [comment]
Hi @jdzhu19 
thanks for providing an example to allow us to reproduce the error. just FYI for future, you can post your code in code blocks like this:

```python
your_code_here
```

which is a bit easier than a zip file. [more info here](*https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)

For your problem: the `minimum_window` parameter is an optional parameter that controls the minimum window in each dimension. you have it set to 1, which is already larger than the minimum window in your starting bounds so it crashes straight away.
You can do any of these things to fix this:

- not specify a minimum window (in which case the default is 0)
- specify a much smaller minimum window - smaller than the smallest of your starting parameters
- specify minimum window as a list, one per variable

**Comment by jdzhu19** [comment]
> Hi @jdzhu19 thanks for providing an example to allow us to reproduce the error. just FYI for future, you can post your code in code blocks like this:
> 
> ```python
> your_code_here
> ```
> 
> which is a bit easier than a zip file. more info here
> 
> For your problem: the `minimum_window` parameter is an optional parameter that controls the minimum window in each dimension. you have it set to 1, which is already larger than the minimum window in your starting bounds so it crashes straight away. You can do any of these things to fix this:
> 
> * not specify a minimum window (in which case the default is 0)
> * specify a much smaller minimum window - smaller than the smallest of your starting parameters
> * specify minimum window as a list, one per variable

Thank you for the suggestion. I may have an error in the code, but actually when I set it to minimum_window=0.5, the error is still reported. However, I noticed you mentioned "specify a much smaller minimum window - smaller than the smallest of your starting parameters", so I tried setting it to 0.01, which works but causes the parameter space to shrink rather quickly. I don't understand why it needs to be "smaller than the smallest of your starting parameters", my original understanding was that the parameter space is scaled down, and minimum_window is the ratio of each reduction. Also, maybe I misunderstood the definition of "smallest of your starting parameters", for example, if one of my param's bounds is set to (0,2), is smaller than that smaller than 0.   For example, my parameter range is pbounds = {'A': (8, 10), 'B': (2, 2.1), 'C': (1, 1.5), 'D': (0.15, 0.2), 'E': (0.05, 0.1), 'F': (0, 2), 'G': (7, 9), 'H': (1, 2), 'I': (4, 5), 'J': ( 0, 5)}, and I want to update iterations 300 times, how to set a reasonable minimum_window?
Thanks for your patience!

**Comment by till-m** [comment]
Hi @jdzhu19,

I assume that you have an understanding of how the domain reduction works. If not, please have a look at the [domain reduction notebook](https://github.com/fmfn/BayesianOptimization/blob/master/examples/domain_reduction.ipynb).

Domain reduction can cause the window/search space to become very, very small if both the upper and lower bound converge to the same value. To avoid the search space collapsing, there is a parameter that ensures that the window/search space cannot become smaller than some limit, `minimum_window`. A negative window size does not make sense since the window cannot have a negative size.

However, there are also the global bounds to consider: Those are the bounds that you give when initializing your parameters, i.e. in your example the `pbounds`. As you can see, you provided a `minimum_window` of `1.`, however your pbounds `C`,`D` and `E` are all incompatible with this value since these bounds are smaller than `1.`

I hope it's more clear now what is happening here.

**Comment by till-m** [comment]
> the maximum minimum_window should be the upper limit of the set parameter - the lower limit of the parameter, right?

yes. However, at that point the effects of the Transformer will be greatly reduced since you're not allowing it to zoom. Ideally it should be somewhat lower. You could also experiment with not setting a minimum window you might not actually need one.

**Comment by jdzhu19** [comment]
Yes, I just gave an extreme example to see if I really understood it, thank you very much!

> > the maximum minimum_window should be the upper limit of the set parameter - the lower limit of the parameter, right?
> 
> yes. However, at that point the effects of the Transformer will be greatly reduced since you're not allowing it to zoom. Ideally it should be somewhat lower. You could also experiment with not setting a minimum window you might not actually need one.

Yes, I just gave an extreme example to see if I really understood it, thank you very much!
