### ISSUE TITLE
Why not use Matern 5/2 kernel?

### ISSUE THREAD

**Issue by jinxin0924** [fmfn/BayesianOptimization#43]
Hi @fmfn, I am new to Bayesian Optimization. I found the paper uses Matern 5/2 kernel and you use the Matern 1.5 in scikit-learn. Why?  Thx

**Comment by fmfn** [comment]
Oh yes, that was an oversight of mine when porting from sklearn 0.17 to 0.18.

Thanks for pointing that out, I'll fix it promptly.
