### ISSUE TITLE
Exception: Bad point. Try increasing theta0.

### ISSUE THREAD

**Issue by stmax82** [fmfn/BayesianOptimization#5]
I had the optimization running for about 600 iterations when suddenly this exception happend in bo.maximize():

---------------------------------------------------------------------------
Exception                                 Traceback (most recent call last)
<ipython-input-20-c8bbc73a75bb> in <module>()
      5     sys.stdout.flush()
      6 
----> 7     bo.maximize(n_iter=1)
      8 
      9     plt.hist(bo.res["all"]["values"], bins=50)

D:\...\pyenv\lib\site-packages\bayes_opt\bayesian_optimization.py in maximize(self, init_points, restarts, n_iter, acq, **gp_params)
    292         # Find unique rows of X to avoid GP from breaking
    293         ur = unique_rows(self.X)
--> 294         gp.fit(self.X[ur], self.Y[ur])
    295 
    296         # Finding argmax of the acquisition function.

D:\...\pyenv\lib\site-packages\sklearn\gaussian_process\gaussian_process.py in fit(self, X, y)
    352                 self.reduced_likelihood_function()
    353             if np.isinf(self.reduced_likelihood_function_value_):
--> 354                 raise Exception("Bad point. Try increasing theta0.")
    355 
    356         self.beta = par['beta']

Exception: Bad point. Try increasing theta0.

**Comment by stmax82** [comment]
I just noticed that this problem was already reported (and "closed") a few months ago here:
https://github.com/fmfn/BayesianOptimization/issues/4

I'm not yet sure what exactly causes the problem, but executing maximize() once again worked (and kept working until I stopped it a few 100 iterations later), so I guess the error occurred due to some bad randomly chosen values.

Maybe this could be handled within maximize() by simply retrying?

**Comment by fmfn** [comment]
This is a problem with the Gaussian Process object. It usually happens when the function you are fitting the GP to is too jagged and the kernel you are using can't handle it. 

This is relatively common when running this method against scale parameters, where the difference between setting, say, C=e-6 and C=e-5, (could be) is just as meaningful as the difference between C=1 and C=10. If this is the case, you may benefit from maximizing against the logarithm of the parameter.

**Comment by stmax82** [comment]
hmm I don't have parameters where log would make sense, but some of my parameters need to be cast to integers - I guess that could cause the problem because casting floats to ints creates a step function with very steep changes at the transition points from one integer to the next?

One of the integer parameters is max_depth of sklearn's GradientBoostingClassifier. Its bounds are set to (1.0, 3.99), so it can only become 1, 2 or 3 when cast to int.

Is there something I can do about that?

**Comment by fmfn** [comment]
Yes, I forgot to mention that, casting to integer creates the step function. I think the most sensible solution would be to increase the `nugget` parameter of the GP object, which, essentially allows the possibility of observing noise labels.

From the documentation:
> Introduce a nugget effect to allow smooth predictions from noisy data. If nugget is an ndarray, it must be the same length as the number of data points used for the fit. The nugget is added to the diagonal of the assumed training covariance; in this way it acts as a Tikhonov regularization in the problem. In the special case of the squared exponential correlation function, the nugget mathematically represents the variance of the input values. Default assumes a nugget close to machine precision for the sake of robustness (nugget = 10. * MACHINE_EPSILON).

**Comment by stmax82** [comment]
I thought about setting the nugget parameter before but didn't because I wasn't sure what value to set it to. Is there a way to come up with a reasonable nugget value when optimizing an unknown function?

For example, trying to optimize the following step function (maximum at x=7) produces the error after about 100 iterations:

```python
def step(x):
    if x <= 7:
        return int(x)
    else:
        return 14-int(x)

bo = BayesianOptimization(f=step, pbounds={"x": (1, 10)}, verbose=True)
bo.maximize(init_points=3, n_iter=1000, restarts=1)
```

Also the noisy step function:

```python
def noisy(x):
    return step(x) + np.random.randn()*0.25

bo = BayesianOptimization(f=noisy, pbounds={"x": (1, 10)}, verbose=True)
bo.maximize(init_points=3, n_iter=1000, restarts=1)
```

Setting the nugget parameter to 0.000001 makes it run for all 1000 iterations without an error - but I only guessed and I'm not sure if this might have any negative affect on the optimization.

**Comment by fmfn** [comment]
I agree it is hard to have good intuition on the nugget values, however you may use this to guide you a bit:
>  In the special case of the squared exponential correlation function, the nugget mathematically represents the variance of the input values.

Increasing its value may slow down the optimization, but it may also help by giving the GP more flexibility. In principle the maximum will always be found, even if it takes forever, but in practice you have to make a judgment call when combining nugget with the parameters of the acquisition function as well.

In the case of a step function I believe you should avoid using the squared exponential kernel and, instead, go for something like the absolute exponential. Square exp. heavily favours smooth functions and can struggle with steps, kinks, and similarly non-differentiable points.
