### ISSUE TITLE
Optimization is very slow

### ISSUE THREAD

**Issue by macwilam** [fmfn/BayesianOptimization#51]
Hi,

I think there is something wrong with the way BO runs at my machine. The BO process is very slow and gets slower with every iteration. I understand that some slowdown can be expected but not this much - from 3 sec to 5 mins.
```
Bayesian Optimization
----------------------------------------------------------------
 Step |   Time |      Value |   colsample_bytree |   subsample | 
    5 | 00m05s |    0.79714 |             0.6500 |      0.9990 | 
    6 | 00m06s |    0.79917 |             0.6500 |      0.6500 | 
    7 | 00m03s |    0.79250 |             0.6500 |      0.8206 | 
    8 | 05m13s |    0.79464 |             0.9990 |      0.9990 |
```

I tried some profiling and see that most of the time i spent here:
```

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
    96854  207.735    0.002  214.026    0.002 basic.py:227(solve_triangular)
```

The CPU i working a lot during this time.

I have all requirements up to date and installed from pip (linux 64 bit)

Is it normal behaviour? If not, any idea how to solve it?

**Comment by fmfn** [comment]
You control the training of the underlying Gaussian Process by passing **gp_params to the maximize method. The default behaviour included 25 rounds of pseudo-likelihood optimization, which happening internally within sklearn's GP.

Is this pattern consistent? GPs are finicky, sometime I find you get odd numerical instabilities throwing you off. Increasing `alpha` usually helps, since it makes the process of inverting the covariance matrix more stable.

**Comment by tachim** [comment]
I'm also seeing this behavior, and increasing alpha doesn't do anything

**Comment by cotterpl** [comment]
I'm also seeing this behavior. Alpha doesn't change anything:

```python
from bayes_opt import BayesianOptimization

def toOptimize(a=0):
    return - a * a

optimizer = BayesianOptimization(toOptimize,{'a': [-5,5]})
optimizer.maximize(n_iter=200)
print(optimizer.res)
```
```
Initialization
-----------------------------------------
 Step |   Time |      Value |         a | 
    1 | 00m00s |  -22.89916 |   -4.7853 | 
    2 | 00m00s |   -1.10813 |    1.0527 | 
    3 | 00m00s |   -0.01665 |    0.1290 | 
    4 | 00m00s |   -4.29761 |    2.0731 | 
    5 | 00m00s |   -0.07172 |    0.2678 | 
Bayesian Optimization
-----------------------------------------
 Step |   Time |      Value |         a | 
    6 | 00m00s |  -25.00000 |    5.0000 | 
    7 | 00m00s |   -0.49688 |   -0.7049 | 
    8 | 00m01s |   -0.03670 |   -0.1916 | 
    9 | 00m02s |   -0.00059 |   -0.0243 | 
   10 | 00m03s |   -0.00044 |    0.0210 | 
```
And it keeps getting slower with each iteration

**Comment by jjiteshh** [comment]
me too! it gets too slow after a while..

**Comment by jtromans** [comment]
I've seen this behavior with other implementations too. My understanding is that the time taken to calculate the GP will scale cubically with the number of observations. However, the actual calculation itself should be relatively quick, especially compared to the black-box function.

**Comment by hofesh** [comment]
Seeing same behaviour. Takes several seconds for each iteration even with a dummy target function.

**Comment by KOLANICH** [comment]
In fact it is the slowest optimizer of all I have ever used. And the results are worse than the ones of the faster optimiz3rs on the same iteration count. So I personally stopped using it in production.

**Comment by nshervt** [comment]
> In fact it is the slowest optimizer of all I have ever used. And the results are worse than the ones of the faster optimiz3rs on the same iteration count. So I personally have never used it in production.

@KOLANICH what other optimiz3rs have you used? any of them do Bayesian optimization?

**Comment by fmfn** [comment]
I resisted intervening here since the optimizer could be made faster by the user. However I decided to bite the bullet and make the changes. See #176

**Comment by KOLANICH** [comment]
>@KOLANICH what other optimizers have you used? any of them do Bayesian optimization?

Here is the list: https://gitlab.com/KOLANICH/UniOpt.py/tree/master/UniOpt/backends

**Comment by louis925** [comment]
I also see the same slow down behavior at around 400+ iterations with 10 parameters to being optimized. Now the 5 fold training of my model take much less than the calculation of Bayesian optimization.
