### ISSUE TITLE
using for multi-dimensional data

### ISSUE THREAD

**Issue by KyonP** [fmfn/BayesianOptimization#54]
i just crash coursing the Gaussian Process with Bayesian Optimization with this code.

and i'm handling some multi-dimensional data look like following.
[  1.59000000e-01   3.10000000e-01   7.00000000e-01   7.00000000e-03
   5.00000000e-03   2.27000000e+00   9.90000000e-01   1.00000000e-02
   2.00000000e-01   4.00000000e-02 ] with target class in real number.

how can i run this code with this data?

i've tried to input this data into your example code, but it was too naive i guess.

**Comment by fmfn** [comment]
Sorry, I do not understand what you mean. Please be more specific regarding what you are trying to do and what problems you are facing.
