### ISSUE TITLE
'numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by jonhilgart22** [fmfn/BayesianOptimization#56]
Hi There,

I am running into issues using an objective function with this BayesianOptimization package.

Here is my objective function. 

```
def hyp_choice_sklearn(hyperparameter_value,hyperparameter_value_two, y_tra = y_train, X_tra = X_train,
                       X_tes = X_test, y_tes = y_test):
    nmse = - mean_squared_error(y_tes,
                                GradientBoostingRegressor(n_estimators=hyperparameter_value,
                                max_depth =hyperparameter_value_two).fit(X_tra.as_matrix()
                                                                         ,y_tra.as_matrix()).predict(
                                    X_tes.as_matrix()))
return nmse
```

Here is my setup of the package

```
bayes_opt_hyp = BayesianOptimization(hyp_choice_sklearn,
                          {'hyperparameter_value': (1, 700),'hyperparameter_value_two':(1,71) }) # the bounds to explore
bayes_opt_hyp .explore({'hyperparameter_value': [int(i) for i in range(1,700,50)],
                        'hyperparameter_value_two':[int(i) for i in range(1,15)]}) # the points to explore, need the same size
```

and here is the results of my search.

<img width="825" alt="screen shot 2017-07-24 at 12 46 50 pm" src="https://user-images.githubusercontent.com/8621935/28541529-3426860c-706e-11e7-969c-431603d074fc.png">

Any help is appreciated.

**Comment by fmfn** [comment]
Both `n_estimators` and `max_depth` and integer fields and expect integer inputs, your objective function does not guarantee that and, since GP na consequently BayesOpt. operate over continuous  space, it tries to probe your object function at some real value point which Grad.B. does not understand. You must make sure you cast the parameter of your estimator to integer within your object function.
```
GradientBoostingRegressor(
    n_estimators=int(hyperparameter_value),
    max_depth=int(hyperparameter_value_two)
)...
```

**Comment by jonhilgart22** [comment]
Thank you!
