### ISSUE TITLE
Want to understand how to extract best parameters for xgboost

### ISSUE THREAD

**Issue by unnir** [fmfn/BayesianOptimization#58]
I tried the xgboost example script and did not get how to extract best parameters for the classifier. 
Can someone please help me?

**Comment by fmfn** [comment]
Your question is a bit too vague for me to help with, as such I suggest you taking a look at the papers linked in the README, and watching the youtube lecture also linked there, to get a feel for the algorithm. Other than that the examples should cover the basic functionally of the package.

**Comment by unnir** [comment]
Sorry for the misunderstanding, next time I would try to explain my question in more details. 

My question has a pure practical background, what I wanted to ask is: 

how to extract the best parameters  from optimizer, f.i. with RandomizedSearchCV from scklearn we can extract parameters very simple:

`RandomizedSearchCV.best_params_ 
`

**Comment by fmfn** [comment]
See `usage.py` in the examples:
```
print(bo.res['max'])
print(bo.res['all'])
```

**Comment by bbennett36** [comment]
@fmfm 

Question on the XGBOOST example - 

```
Will train until test-auc hasn't improved in 50 rounds.
Stopping. Best iteration:
[110]	train-auc:0.927877+0.00199167	test-auc:0.868635+0.00736238

   15 | 00m47s |   -0.86864 |    0.1914 |             0.6810 |    7.8813 |      9.9855 |             1.0001 |      0.7510 | 
```

So the 'value' is coming back as the AUC as a negative value so whenever I use xgbBO.res['max'] it's actually returning the lowest AUC. Why would that be? I'm just confused on why calling 'max' would return the worst params instead of the best?
