### ISSUE TITLE
scipy.optimize.OptimizeResult is not always an array

### ISSUE THREAD

**Issue by raphaelvannson** [fmfn/BayesianOptimization#60]
Hello,

## Thank you

First of all, I want to extend many (many) thanks for putting this wonderful package and the great tutorial together.
I am constructing a small API around this package to make it easy to tune machine learning hyper parameters.

## Summary

When invoking `BayesianOptimization.maximize(init_points=init_points, n_iter=0)`, I have noticed that `helpers.acq_max()` can fail. In particular, the `scipy.optimize.OptimizeResult` object can be a scalar but the code expects an array. As a result, `helpers.acq_max()` can fail on these lines of code:

```
        # Store it if better than previous minimum(maximum).
        if max_acq is None or -res.fun[0] >= max_acq:
            x_max = res.x
            max_acq = -res.fun[0]
```

## Symptom details

```python
bo  = BayesianOptimization(f=obj_fnc, pbounds=hp_range)
bo.maximize(init_points=init_points, n_iter=0)

(...)

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bayes_opt/bayesian_optimization.py in maximize(self, init_points, n_iter, acq, kappa, xi, **gp_params)
    262                         gp=self.gp,
    263                         y_max=y_max,
--> 264                         bounds=self.bounds)
    265 
    266         # Print new header

/Library/Frameworks/Python.framework/Versions/3.4/lib/python3.4/site-packages/bayes_opt/helpers.py in acq_max(ac, gp, y_max, bounds)
     53 
     54         # Store it if better than previous minimum(maximum).
---> 55         if max_acq is None or -res.fun[0] >= max_acq:
     56             x_max = res.x
     57             max_acq = -res.fun[0]

IndexError: too many indices for array
```

## Fix proposal
I was able to solve the issue by cloning this repo, looking into `helpers.acq_max()`, `scipy.optimize.minimize` and `cipy.optimize.OptimizeResult` and replacing `-res.fun[0]` by `-res.fun.min()`.

Here is the fixed code:

```python
        # Store it if better than previous minimum(maximum).
        if max_acq is None or -res.fun.min() >= max_acq:
            x_max = res.x
            max_acq = -res.fun.min()
```

Once these modifications were made and (I changed the imports in my code to use the modified bases_opt package), the initialization step was able to complete successfully:

```
Initialization
-------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |   acc_improvement_factor |   batch_size |   lr_decay_factor |   lr_init |    window | 
    1 | 01m20s |    0.61373 |                   1.0335 |     249.4912 |            0.9903 |    0.0634 |   17.1281 | 
    2 | 01m22s |    0.37705 |                   1.0155 |     180.6748 |            0.9961 |    0.0647 |   14.6763 | 
Bayesian Optimization
-------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |   acc_improvement_factor |   batch_size |   lr_decay_factor |   lr_init |    window | 
```

## Disclaimer

I am new to Bayesian Optimization, `scipy.optimize.minimize` and `cipy.optimize.OptimizeResult` so the fix suggestion might not be correct. Feel free to close this issue as 'user error' if you feel my use case should not occur under normal circumstances (which means I am doing something wrong).

Hit me up if you have any questions or need more details.

Thanks again!

**Comment by fmfn** [comment]
Thanks for using this package and helping making it better. 

1. Can you provide a code snippet I can run to reproduce the issue? I just want to understand what is leading to that.
2. I find it odd that `.min()` works since this is an array method, so if `res.fun` is a float it should fail. Another alternative, which I think is better regardless would be to `try-except IndexError`, since it makes it more explicit, since `.min()` can lead to confusion (why not `.max()`, or some other function?)

You're welcome to make a PR with your changes!

Cheers.

**Comment by raphaelvannson** [comment]
Hello @fmfn,

Many thanks for the quick response!
One of my parameter bound was inverted (*duh...*). I basically provided:`{'x1': (x1_max, x1_min)}`.
This issue is basically a dup of [Issue 41](https://github.com/fmfn/BayesianOptimization/issues/41) and can be closed as 'user error'. 

To answer your questions:

 1. I am not entirely sure how `res.fun` got to be scalar exactly but providing 'inverted' min and max bounds for a parameter certainly seems to trigger the issue.
 2. The rationale behind `.min()`was: if `res.fun` can be either a scalar or an array, then we taking the minimum of `res.fun` would always give us what we want (the min of `-res.fun` would be the max of `Y`.

Thanks again!
Raphael

**Comment by fmfn** [comment]
I see, good to know! Sometimes the flexibility that python gives you with types can come back to hunt you, haha. 

With these two issues in mind I think it makes sense to check for reversed bounds and raise some sort of error, or at the very least a warning. Thanks for taking a careful look at it.
