### ISSUE TITLE
"pip install bayesian-optimization" downloads old version

### ISSUE THREAD

**Issue by a3626a** [fmfn/BayesianOptimization#61]
"pip install bayesian-optimization" downloads old version.

The version downloaded via pip is at least older than this commit :
https://github.com/fmfn/BayesianOptimization/commit/ad5cab5a112c1f0cc25827f902ab26ad2b25f238#diff-76a35035956307f593db1adc0e6fb88e

plz update pip module.
Thank you.

**Comment by fmfn** [comment]
This is a good reminder, completely skipped my mind. I'm reopening the issue so I'll remember to do it.

**Comment by fmfn** [comment]
Ok, I finally got around updating it.
