### ISSUE TITLE
No ../input/train.csv to run the XGBoost example

### ISSUE THREAD

**Issue by tobegit3hub** [fmfn/BayesianOptimization#64]
We want to try the XGBoost code in examples but it fails because of the lack of `../input/train.csv`.

```
def prepare_data():
    train = pd.read_csv('../input/train.csv')
    categorical_columns = train.select_dtypes(include=['object']).columns
```

It would be great if we have more instruction to make it works.

**Comment by fmfn** [comment]
The doc string at the top of the file mentions the example works for the default features for the dataset used in the [Allstate kaggle competition](https://www.kaggle.com/c/allstate-claims-severity/data). There you can find the `train.csv` file.
