### ISSUE TITLE
when use bayes tuning xgboost, is there any need to set scale_pos_weight ?

### ISSUE THREAD

**Issue by StutuPig** [fmfn/BayesianOptimization#73]
if neg/pos is about 45-65, in this case, should we set scale_pos_weight to 1 or neg/pos ?
when i use BayesianOptimization(bayes tuning) to tune xgboost, if i set scale_pos_weight to neg/pos the ks on valid dataset is about 18, but if i set scale_pos_weight to 1, the ks on valid dataset up to 38 ... i don't know why ? can somebody help to explain ..
(Note: if scale_pos_weight ==1, i set feval='ks', or else, i set feval='auc').

**Comment by fmfn** [comment]
Sorry, I'm not sure I understand the question, please rephrase it and give more details.
