### ISSUE TITLE
Specifying the Resolution of input variables

### ISSUE THREAD

**Issue by Dhawgupta** [fmfn/BayesianOptimization#76]
I am trying to optimize some motor angle values using Bayesian optimization, the code takes a continuous state space and resolution of the motor is 1 degree, is there a way to specify the resolution so that we can make the results faster and search space smaller.

**Comment by fmfn** [comment]
No clear way of specifying resolution - or discretizing - parameters. We can try casting it to integer, or applying whatever transformation you deem appropriate within the function to be optimized. While this leads to a non-smooth function if you tune the GP well it should do ok.
