### ISSUE TITLE
Is it possible to specify the parameters should be integers?

### ISSUE THREAD

**Issue by chrism2671** [fmfn/BayesianOptimization#81]
I have a number of cases where the search space is discrete. Is it possible to inform the optimizer of this fact?

Currently I do `int(x)` before passing the trial params into my methods, and I think this makes the target function learnt less accurate/slower to converge.

**Comment by fmfn** [comment]
That's a recurring question, and `int(x)` is the most common solution.  I'm not aware of any simple way to tackle this that would fit the scope of this package. Usually changing the `alpha` parameter of the underlying GP helps with convergence.
