### ISSUE TITLE
Enhancement Request: Pipe verbose logging to text file

### ISSUE THREAD

**Issue by lwaldner** [fmfn/BayesianOptimization#85]
Hey everyone I love this library but I think it would be super super useful to be able to specify an output log (or just have a default one) that the BayesianOptimizer would pipe its progress logs to.

**Comment by fmfn** [comment]
I suppose that could be done. You mean simply specify a file logs should go to? Or something more intricate?

**Comment by fmfn** [comment]
This issue will be fixed in the next release. You can see updates on this specific feature here: https://github.com/fmfn/BayesianOptimization/pull/119
