### ISSUE TITLE
terminate called after throwing an instance of 'std::bad_alloc'

### ISSUE THREAD

**Issue by TMorville** [fmfn/BayesianOptimization#90]
Using the code from the[ xgboost example](https://github.com/fmfn/BayesianOptimization/blob/master/examples/xgboost_example.py) but with my own data, the optimiser quits with this error: 

```
Initialization
---------------------------------------------------------------------------------------------------------------------------
 Step |   Time |      Value |     alpha |   colsample_bytree |     gamma |   max_depth |   min_child_weight |   subsample |
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

My data is ``shape = (370551, 10762)`` with mostly onehot encoded categories. 
Python is ``3.5.2``.

**Comment by fmfn** [comment]
Doesn't look like anything related to this package directly. My guess is either XGBoost or the underlying GP are running out of memory (given you data is pretty wide). Give it a try with a smaller subset of this data and see if you can make it work
