### ISSUE TITLE
Problem with initialize 

### ISSUE THREAD

**Issue by joaosalvado10** [fmfn/BayesianOptimization#92]
Hello,
When I use the Initialize method, I got a key error saying that the data point is not unique. In fact, when I call the maximize method sometimes it is searching for already explored parameters.

**Comment by joaosalvado10** [comment]
I think the problem could be here.
https://github.com/fmfn/BayesianOptimization/blob/317f73577e10853ec4c0f282dbcb11ff3287852a/bayes_opt/bayesian_optimization.py#L87

**Comment by joaosalvado10** [comment]
This problem only occurs if the init_points=1.

**Comment by fmfn** [comment]
Hum... that's odd, let me take a look. In the meantime can you provide an example of it happening?

**Comment by a31314431** [comment]
I just came across a similar issue.. The algorithm was trying to evaluate a point already included in initialization and thus triggered "Data point is not unique" error.

**Comment by linzzzzzz** [comment]
It turns out I have two duplicate records in the dict I used to initialize..
