### ISSUE TITLE
Optimize functions with variable number of arguments

### ISSUE THREAD

**Issue by AsierO** [fmfn/BayesianOptimization#96]
I was wondering if it is possible to optimize a function with a variable number of arguments using BayesianOptimization. 

I would like to run 
`BayesianOptimization(f,param_dic)`
where both have a variable number of arguments. For example, param_dic will look like
`param_dic={}
        for i in range(len(initial_params)):
            param_dic['x'+str(i)]=(-1,1)`
and the function is
`def f(*arg,**kwargs):`

So far I haven't managed to make it work because it demands f to be of the form f(x0,x1,....xn).

**Comment by fmfn** [comment]
Yeah, that's a tough one. There's no out of the box way to do it, nor am I aware of any principled method to approach it. To be honest, unless someone opens a PR solving this in a simple way I don't see this feature being implemented anytime soon.

**Comment by Roadsong** [comment]
Hi @AsierO, I have the exact same issue... Did you ever make it work using other methods?

Hi @fmfn, you mentioned you didn't find any principled method, could you please give me some pointers on those "dirty" methods? 

I am planning to create functions on-the-fly with the form of
```
f(var1, var2, var3), f(var1, var2, var3, var4), ...
```
But the number of arguments is dynamic and undecided yet. I checked out some documents on this but not very sure if this method would work...

Thanks for any help!
