### ISSUE TITLE
Save/restore progress

### ISSUE THREAD

**Issue by rspadim** [fmfn/BayesianOptimization#99]
SOmetime we have a big optimization and it can crash (example, xgboost with gpu and memory limit)

should be nice save progress to file and resume from last position

**Comment by rspadim** [comment]
from kaggle talk, maybe a callback is better than a save/restore only

https://www.kaggle.com/c/home-credit-default-risk/discussion/59195#345409

**Comment by fmfn** [comment]
We already have the notion of `observers` that are capable to handle such functionality. In the new release I will add a default `observer` to save progress and ability to load progress from files as well.
See https://github.com/fmfn/BayesianOptimization/pull/118
